"""MASI: the aggregator, and the guarantee that it never restates a measurement
onto a measured relationship.

The fixture (``tests/fixtures/masi_mini/``, generated by
``tests/fixtures/make_masi_mini.py``, which names every row and its trap) is
loaded through the real prep and the real blueprint alongside **ChEMBL's, and
both screens'**, because the most consequential assertions here are about the
join across all four:

* a MASI substance that is a compound this graph already keys must reach that
  ``Drug`` node by one declared ``SAME_COMPOUND_AS`` edge, and must **not** put
  its curated claim onto ``METABOLISES`` or ``INHIBITS_GROWTH_OF``, where the
  measured screens live;
* ``duplicates_primary_source`` must name, per edge, every loaded screen that
  already measures that pair — 62.5% of the real file's edges;
* a curated refutation must be its own relationship, and a change with no
  direction must be no edge at all;
* the probiotic flag must survive two MASI organisms collapsing onto one taxon,
  which is a data-loss bug this fixture exists to keep fixed.
"""

from __future__ import annotations

import csv
import json
import subprocess
import sys
from pathlib import Path

import pytest

from conftest import MONDO_MINI, TAXDUMP_MINI

kglite = pytest.importorskip("kglite")

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parent / "fixtures"
MASI_MINI = FIXTURES / "masi_mini"
ZIMMERMANN_MINI = FIXTURES / "zimmermann2019_mini"
MAIER_MINI = FIXTURES / "maier2018_mini"
CHEMBL_MINI = FIXTURES / "chembl_mini"
SCRIPTS = ROOT / "scripts"
PREP = SCRIPTS / "prep_masi.py"

sys.path.insert(0, str(SCRIPTS))

for _needed in (
    PREP,
    MASI_MINI / "MASI_v1.0_download_microbesInfo.xlsx",
    MAIER_MINI / "NIHMS76168-supplement-Supplementary_table_3.xlsx",
    ZIMMERMANN_MINI / "41586_2019_1291_MOESM1_ESM.xlsx",
    CHEMBL_MINI / "mechanism.jsonl",
):
    if not _needed.exists():
        pytest.skip(f"{_needed} does not exist yet", allow_module_level=True)

from microbiomekg.conditions import MondoIndex  # noqa: E402
from microbiomekg.ontology import EVIDENCE_LEVEL_VALUES  # noqa: E402
from microbiomekg.ontology.masi import (  # noqa: E402
    CATEGORY_ABUNDANCE,
    CATEGORY_METABOLISM,
    CONTRACT,
    DISEASE_EVIDENCE_LEVEL,
    NOT_METABOLISED_MARKER,
    NO_CHANGE,
    RELATION_ABUNDANCE_CHANGED,
    RELATION_ABUNDANCE_UNCHANGED,
    RELATION_METABOLISES,
    RELATION_NO_METABOLISM,
    RELATION_SAME_COMPOUND,
    direction_of,
    evidence_level_for,
    is_class_substance,
    missing,
    normalise_disease_name,
    publications_of,
    relation_for_abundance,
    relation_for_metabolism,
    substance_variants,
)

SOURCE = "masi"

# --------------------------------------------------------------------------
# Golden values, derived from the fixture by hand and asserted exactly.
# --------------------------------------------------------------------------

RECORDS = 14
EDGES = 10
METABOLISES = 2
NO_METABOLISM = 1
ABUNDANCE_CHANGED = 6
ABUNDANCE_UNCHANGED = 1
SUBSTANCES = 6
SAME_COMPOUND = 4       # two by name, one by salt strip, one non-therapeutic
ASSOCIATIONS = 6        # seven records, one on a microbe that reaches no taxon
DISEASE_NODES = 5
LEDGER_ROWS = 9
UNRESOLVED_TAXA = 2     # the unclassified microbiota, and the orphan microbe
PROBIOTIC_TAXA = 2
ANNOTATED_TAXA = 5
#: Of the ten edges, the seven whose (taxon, compound) pair a loaded screen
#: already measures. On the real file it is 7,161 of 11,456 — 62.5%.
DUPLICATED_EDGES = 7

E_COLI = 562
B_THETA = 818
B_LONGUM = 216816
BLAUTIA = 572511        # the genus the `Blautia spp.` row resolves through
BACTEROIDIA = 200643    # the class the *record* names, against the phylum 976

METFORMIN = "CHEMBL:CHEMBL1431"
AMPICILLIN = "CHEMBL:CHEMBL174"
VANCOMYCIN = "CHEMBL:CHEMBL262777"
ASPIRIN = "CHEMBL:CHEMBL25"

INTERACTION_RELATIONSHIPS = (
    RELATION_METABOLISES, RELATION_NO_METABOLISM,
    RELATION_ABUNDANCE_CHANGED, RELATION_ABUNDANCE_UNCHANGED,
)
#: The relationships the two published screens own. **No MASI edge may carry
#: one of these**, and that is the whole architectural claim of this source.
MEASURED_RELATIONSHIPS = (
    "INHIBITS_GROWTH_OF", "DOES_NOT_INHIBIT_GROWTH_OF",
    "METABOLISES", "DOES_NOT_METABOLISE",
)


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    """ChEMBL, both screens and MASI through their real preps, then the real
    blueprint. The order is the build's own: this prep declares
    ``DEPENDS_ON = ["chembl", "maier2018", "zimmermann2019"]`` because its
    substance join reads the ``drug.csv`` all three write into, and its overlap
    check reads the screens' four edge tables."""
    work = tmp_path_factory.mktemp("masi")
    csv_dir = work / "csv"
    csv_dir.mkdir()

    def run(script, *args):
        proc = subprocess.run(
            [sys.executable, str(script), *args], capture_output=True, text=True,
            cwd=ROOT,
        )
        assert proc.returncode == 0, (
            f"{script.name} failed:\n{proc.stdout}\n{proc.stderr}"
        )
        return proc

    run(
        SCRIPTS / "prep_chembl.py",
        "--chembl", str(CHEMBL_MINI),
        "--taxdump", str(TAXDUMP_MINI),
        "--out", str(csv_dir),
    )
    run(
        SCRIPTS / "prep_maier2018.py",
        "--tables", str(MAIER_MINI),
        "--taxdump", str(TAXDUMP_MINI),
        "--out", str(csv_dir),
    )
    run(
        SCRIPTS / "prep_zimmermann2019.py",
        "--tables", str(ZIMMERMANN_MINI),
        "--taxdump", str(TAXDUMP_MINI),
        "--out", str(csv_dir),
        "--published-matrix", "6,9,5",
    )
    prep = run(
        PREP,
        "--tables", str(MASI_MINI),
        "--taxdump", str(TAXDUMP_MINI),
        "--mondo", str(MONDO_MINI),
        "--out", str(csv_dir),
    )
    run(
        SCRIPTS / "prep_taxonomy.py",
        "--taxdump", str(TAXDUMP_MINI),
        "--out", str(csv_dir),
        "--scope", "cited",
        "--cited-from", str(csv_dir / "cited_taxa.csv"),
    )

    from build_blueprint import compose

    from microbiomekg.ontology import ontology_for, write_json

    sources = [SOURCE, "chembl", "maier2018", "zimmermann2019"]
    blueprint = compose(ROOT / "blueprints", sources)
    settings = blueprint.setdefault("settings", {})
    settings["root"] = str(csv_dir)
    for key in ("output", "output_path", "output_file"):
        settings.pop(key, None)
    write_json(csv_dir / "ontology.json", ontology_for(sources))
    blueprint["ontology"] = str(csv_dir / "ontology.json")
    local = csv_dir / "blueprint.test.json"
    local.write_text(json.dumps(blueprint))

    return kglite.from_blueprint(local, verbose=False, save=False), csv_dir, prep.stdout


@pytest.fixture(scope="module")
def graph(built):
    return built[0]


@pytest.fixture(scope="module")
def csv_dir(built):
    return built[1]


@pytest.fixture(scope="module")
def prep_output(built):
    return built[2]


def rows(graph, query):
    return list(graph.cypher(query))


def one(graph, query):
    result = rows(graph, query)
    assert result, f"query returned no rows:\n{query}"
    return result[0]


def table(csv_dir, name):
    with (csv_dir / name).open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def ledger(csv_dir, kind):
    return [r for r in table(csv_dir, f"unresolved_{SOURCE}.csv")
            if r["kind"] == kind]


# --------------------------------------------------------------------------
# The parsing vocabulary, as unit tests: these run without a graph
# --------------------------------------------------------------------------


def test_absent_is_the_three_characters_n_a_and_not_a_blank():
    """MASI writes `n.a.` for every missing value in all four tables — 12,463
    times in `Metabolism_Enzymes` alone. A reader that only tested for the empty
    string would put those three characters into a node title and a PMID."""
    assert missing("n.a.") and missing("N.A.") and missing("") and missing(None)
    assert not missing("Gut") and not missing("0")


def test_the_metabolism_call_reads_the_category_and_only_qualifies_it():
    """`Metabolism_Effect_on_Drug` is `n.a.` on 3,431 of the 4,295 metabolism
    records. The *category* is the claim; the effect column qualifies it. Reading
    a blank effect as a non-hit would invert 3,431 edges, and only the one exact
    marker string means the microbe did not metabolise the substance."""
    assert relation_for_metabolism(NOT_METABOLISED_MARKER) == RELATION_NO_METABOLISM
    assert relation_for_metabolism("n.a.") == RELATION_METABOLISES
    assert relation_for_metabolism("") == RELATION_METABOLISES
    assert relation_for_metabolism("Increase Toxicity") == RELATION_METABOLISES
    assert relation_for_metabolism("Activation of prodrug") == RELATION_METABOLISES


def test_a_change_with_no_direction_is_no_edge_rather_than_a_guess():
    """`Microbe_Change` is four-valued and two real rows say `delay microbiota
    maturation` — a curated finding with no sign this model can write. Filing it
    as a decrease invents a sign and filing it as "no change" inverts one, so it
    is neither relationship."""
    assert relation_for_abundance("Increase") == RELATION_ABUNDANCE_CHANGED
    assert relation_for_abundance("Decrease") == RELATION_ABUNDANCE_CHANGED
    assert relation_for_abundance(NO_CHANGE) == RELATION_ABUNDANCE_UNCHANGED
    assert relation_for_abundance("delay microbiota maturation") is None
    assert relation_for_abundance("n.a.") is None
    assert direction_of("Increase") == "increased"
    assert direction_of("Decrease") == "decreased"
    assert direction_of(NO_CHANGE) == ""


def test_evidence_level_is_derived_per_row_and_never_defaults_to_in_vitro():
    """The brief every source here answers is Part B's ladder, and this source
    carries two columns that can move it. 2,396 rows leave `Experiment_System`
    at `n.a.` and they must reach `unknown` rather than a plausible-looking
    level; a human in-vivo row is `unknown` too, because nothing in the file says
    the study was observational."""
    assert evidence_level_for("In vitro", "High-throughput incubation assays") == \
        "in-vitro"
    assert evidence_level_for("In vitro", "Human") == "in-vitro"
    assert evidence_level_for("In vivo", "C57BL/6 mouse") == "in-vivo-model"
    assert evidence_level_for("In vivo (Rat); In vitro (Human)", "Rat") == \
        "in-vivo-model"
    # A mixed host cell with one non-human component is in-vivo-model.
    assert evidence_level_for("In vivo", "Human; Mouse") == "in-vivo-model"
    assert evidence_level_for("In vivo", "Human") == "unknown"
    assert evidence_level_for("n.a.", "n.a.") == "unknown"
    assert evidence_level_for("", "") == "unknown"
    for cell in ("In vitro", "In vivo", "n.a."):
        assert evidence_level_for(cell, "Mouse") in EVIDENCE_LEVEL_VALUES


def test_the_reference_cell_is_parsed_and_the_type_column_is_not_trusted():
    """2,058 rows carry several references in one cell, some open with a stray
    separator, and **the type column is wrong on 25 of them** — typed `PMID`,
    carrying a DOI and no PMID at all. Parsing the text reaches a publication on
    all 12,512 rows; branching on the type column would have filed those 25 DOIs
    as accessions. The bare-number fallback is for a shape this release does not
    contain, and it fires **only** when the type column says PMID and the whole
    cell is digits — a looser rule would turn a DOI's year into an accession."""
    assert publications_of("PMID", "PMID: 26569070") == (["PMID:26569070"], 26569070)
    assert publications_of(
        "PMID", "PMID: 26569070; PMID: 22516259"
    ) == (["PMID:26569070", "PMID:22516259"], 26569070)
    assert publications_of("DOI", "; DOI: 10.1000/xyz123") == \
        (["doi:10.1000/xyz123"], None)
    assert publications_of("PMID", "26569070") == (["PMID:26569070"], 26569070)
    # A DOI-typed cell that also names a PMID gives both, PMID first.
    ids, pmid = publications_of("DOI", "DOI: 10.1016/j.jinf.2019.10.008; PMID: 3846592")
    assert ids == ["PMID:3846592", "doi:10.1016/j.jinf.2019.10.008"] and pmid == 3846592
    assert publications_of("DOI", "not a reference") == ([], None)


def test_masi_own_subcategory_decides_what_is_a_class_rather_than_a_compound():
    """41 substances are filed `Drug Class` or `Drug category`. Joining a class
    onto whichever molecule shares its spelling is the level-4-ATC error
    `microbiomekg.drugs` refuses, and the refusal is keyed on MASI's own column
    rather than on a rule over names."""
    assert is_class_substance("Drug Class")
    assert is_class_substance("Drug category")
    # `;`-joined, and a row filed under both takes the safe direction.
    assert is_class_substance("Approved Drug; Drug Class")
    assert not is_class_substance("Approved Drug")
    assert not is_class_substance("Medicinal Herbal Compounds")
    assert not is_class_substance("")


def test_the_substance_routes_are_verbatim_first_and_there_are_only_two():
    """MASI carries a richer cross-reference block than any other source here —
    709 DrugBank ids, 1,067 PubChem CIDs — and none of them reaches anything,
    because the fetched ChEMBL molecule JSONL carries no cross-references at all.
    So the join is two name routes, and the derived one is tried last."""
    assert [r for _k, _v, r in substance_variants("Metformin")] == ["substance-name"]
    assert [r for _k, _v, r in substance_variants("Ampicillin sodium")] == [
        "substance-name", "salt-name"
    ]
    # The salt strip that changes nothing adds no second attempt.
    assert [v for _k, v, _r in substance_variants("Baicalin")] == ["Baicalin"]


def test_a_disease_label_is_normalised_only_by_stripping_its_abbreviation():
    """`Crohn's disease(CD)` and `Inflammatory bowel disease (IBD)` are MONDO
    terms wearing an abbreviation. Nothing else is corrected: the real file's
    `Rheumatoid arthrits` keeps its typo and reaches no term, which is the
    honest outcome rather than a spelling rule standing in for a curated
    equivalence."""
    assert normalise_disease_name("Inflammatory bowel disease (IBD)") == \
        "inflammatory bowel disease"
    assert normalise_disease_name("Crohn's disease(CD)") == "crohn's disease"
    assert normalise_disease_name("Colorectal cancer") == "colorectal cancer"
    assert normalise_disease_name("Rheumatoid arthrits") == "rheumatoid arthrits"


def test_only_an_exact_mondo_synonym_is_an_identity():
    """MONDO ships `EXACT`, `BROAD`, `NARROW` and `RELATED` synonyms, and reading
    a RELATED one as identity is the same false merge `MONDO:equivalentTo` guards
    against on the xref side. `animal helminthiasis` is RELATED to *helminthiasis,
    animal* and must miss; a string two live terms both claim is not an
    identifier either and is dropped rather than resolved."""
    index = MondoIndex.from_obo(MONDO_MINI)
    assert index.mondo_by_name("colorectal cancer") == \
        ("MONDO:0005575", "mondo-name")
    assert index.mondo_by_name("obesity") == ("MONDO:0011122", "mondo-exact-synonym")
    assert index.mondo_by_name("animal helminthiasis") == (None, "unmatched")
    assert index.mondo_by_name("rheumatoid arthrits") == (None, "unmatched")
    assert index.mondo_by_name("") == (None, "unmatched")
    assert set(index.by_name) & set(index.by_exact_synonym) == set(), (
        "a term's own name must always win over another term's synonym"
    )
    # An obsolete term contributes neither a name nor a synonym key.
    assert index.mondo_by_name(
        "obsolete sickle cell disease associated with an other hemoglobin anomaly"
    ) == (None, "unmatched")


# --------------------------------------------------------------------------
# The aggregator contract — the reason this source has its own node type
# --------------------------------------------------------------------------


def test_no_masi_edge_lands_on_a_relationship_a_published_screen_owns(graph):
    """**The architectural claim, as a query.** 66.4% of MASI's interaction rows
    cite Maier 2018 or Zimmermann 2019, and 85.1% of the (taxon, compound) pairs
    it resolves to already carry a screen edge. If MASI's metabolism records
    landed on `METABOLISES`, D8's own query would double-count without saying so
    — so every one of the four relationships that carries a *measurement* must be
    free of MASI."""
    for relationship in MEASURED_RELATIONSHIPS:
        assert not rows(
            graph,
            f"MATCH ()-[r:{relationship}]->() "
            f"WHERE r.primary_source = '{SOURCE}' RETURN r LIMIT 1"
        ), f"{relationship} carries a MASI edge; it must carry only measurements"


def test_masi_mints_no_drug_node_and_reaches_the_existing_ones_by_one_edge(graph):
    """MASI never writes a `Drug`: an unmatched substance is a `Substance` node
    with no `SAME_COMPOUND_AS` edge, not a second node for a compound the graph
    already keys. Both screens *do* mint drugs, so this is a real difference and
    not an accident of the fixture — a herbal extract is not a drug, and 278 of
    MASI's 1,350 substances have no therapeutic category at all."""
    assert not rows(
        graph, f"MATCH (d:Drug) WHERE d.source = '{SOURCE}' RETURN d LIMIT 1"
    )
    assert one(graph, "MATCH (s:Substance) RETURN count(*) AS n")["n"] == SUBSTANCES
    assert one(
        graph, f"MATCH ()-[r:{RELATION_SAME_COMPOUND}]->() RETURN count(*) AS n"
    )["n"] == SAME_COMPOUND
    reached = one(
        graph,
        f"MATCH (s:Substance {{id: 'MASI:PMDBD1'}})"
        f"-[:{RELATION_SAME_COMPOUND}]->(d:Drug) "
        f"RETURN d.id AS drug, s.drug_join AS route",
    )
    assert reached == {"drug": METFORMIN, "route": "substance-name"}
    # The salt route, which is what `Drug`'s parent keying exists for.
    assert one(
        graph,
        f"MATCH (s:Substance {{id: 'MASI:PMDBD2'}})"
        f"-[:{RELATION_SAME_COMPOUND}]->(d:Drug) RETURN d.id AS drug",
    )["drug"] == AMPICILLIN


def test_a_class_of_compounds_never_reaches_a_molecule(graph, csv_dir):
    """`ACE inhibitors` is MASI's own `Drug Class` subcategory. It stays a
    `Substance` with its edges and **no** `SAME_COMPOUND_AS`, because joining a
    class onto one molecule would put every drug in the class on that node — the
    level-4-ATC error stated once in `microbiomekg.drugs` and enforced here."""
    node = one(
        graph,
        "MATCH (s:Substance {id: 'MASI:PMDBD3'}) "
        "RETURN s.title AS name, s.drug_join AS route, s.drug_id AS drug",
    )
    assert node["name"] == "ACE inhibitors" and node["route"] == "class-not-compound"
    assert not node["drug"]
    assert not rows(
        graph,
        f"MATCH (:Substance {{id: 'MASI:PMDBD3'}})-[r:{RELATION_SAME_COMPOUND}]->() "
        f"RETURN r LIMIT 1",
    )
    assert [r["record_id"] for r in ledger(csv_dir, "substance")] == [
        "PMDBD3", "PMDBD5"
    ]


def test_a_non_therapeutic_category_reaching_a_drug_is_countable(graph, csv_dir):
    """16 substances MASI files as dietary, herbal or environmental reach a
    `Drug` node by an exact name match, and every one of them is the same
    molecule ChEMBL holds — *Nicotine*, *Permethrin*, *Berberine*. The join is
    allowed and **ledgered**, so a false merge would show up in a count rather
    than in nobody's notes."""
    mismatch = [r for r in ledger(csv_dir, "substance")
                if "no therapeutic category" in r["reason"]]
    assert [r["subject"] for r in mismatch] == ["Aspirin"]
    assert one(
        graph,
        f"MATCH (s:Substance {{id: 'MASI:PMDBD5'}})"
        f"-[:{RELATION_SAME_COMPOUND}]->(d:Drug) RETURN d.id AS drug",
    )["drug"] == ASPIRIN


def test_every_restated_pair_names_the_source_that_measured_it(graph):
    """`duplicates_primary_source` is the countable half of the aggregator
    contract: on the real file 7,161 of 11,456 edges (62.5%) restate a pair a
    loaded screen already measures, and "what does MASI *add*" is one clause.
    kglite writes an empty column as null, so the clause is `IS NULL` — asserted
    here so a doc that writes `= ''` is caught by a test rather than by a user.
    The property is a **list**, so the grouping key is its JSON text rather than
    the value; `'maier2018' IN r.duplicates_primary_source` is the query form."""
    counted = {
        (tuple(r["dup"]) if r["dup"] is not None else None): r["n"] for r in rows(
            graph,
            "MATCH ()-[r]->(:Substance) "
            "RETURN r.duplicates_primary_source AS dup, count(*) AS n",
        )
    }
    assert counted == {
        ("maier2018", "zimmermann2019"): 2, ("maier2018",): 3, ("zimmermann2019",): 2,
        None: EDGES - DUPLICATED_EDGES,
    }
    assert one(
        graph,
        "MATCH ()-[r]->(:Substance) WHERE 'maier2018' IN r.duplicates_primary_source "
        "RETURN count(r) AS n",
    )["n"] == 5
    # The pair both screens measured: MASI curates it a third time, and says so.
    assert one(
        graph,
        f"MATCH (t:Taxon {{id: {B_THETA}}})-[r:{RELATION_METABOLISES}]->"
        f"(:Substance {{id: 'MASI:PMDBD6'}}) "
        f"RETURN r.duplicates_primary_source AS dup",
    )["dup"] == ["maier2018", "zimmermann2019"]
    # And a compound no screen carries: null, not an empty string.
    assert one(
        graph,
        f"MATCH (t:Taxon {{id: {BLAUTIA}}})-[r:{RELATION_ABUNDANCE_CHANGED}]->() "
        f"RETURN r.duplicates_primary_source AS dup",
    )["dup"] is None


def test_the_prep_reports_the_overlap_rather_than_leaving_it_to_a_doc(prep_output):
    """The number that decides this source's whole shape is printed by the run
    that produced the edges, not quoted from a document written once."""
    assert "AGGREGATOR OVERLAP" in prep_output
    assert f"{DUPLICATED_EDGES} of {EDGES} edges" in prep_output


# --------------------------------------------------------------------------
# The four relationships, and the two refutations
# --------------------------------------------------------------------------


def test_the_four_relationships_split_the_two_categories_by_effect(graph):
    counts = {
        r["t"]: r["n"] for r in rows(
            graph,
            "MATCH ()-[r]->(:Substance) RETURN type(r) AS t, count(*) AS n",
        )
    }
    assert counts == {
        RELATION_METABOLISES: METABOLISES,
        RELATION_NO_METABOLISM: NO_METABOLISM,
        RELATION_ABUNDANCE_CHANGED: ABUNDANCE_CHANGED,
        RELATION_ABUNDANCE_UNCHANGED: ABUNDANCE_UNCHANGED,
    }
    assert sum(counts.values()) == EDGES
    categories = {
        r["t"]: r["c"] for r in rows(
            graph,
            "MATCH ()-[r]->(:Substance) "
            "RETURN type(r) AS t, collect(DISTINCT r.interaction_category) AS c",
        )
    }
    assert categories[RELATION_METABOLISES] == [CATEGORY_METABOLISM]
    assert categories[RELATION_ABUNDANCE_CHANGED] == [CATEGORY_ABUNDANCE]


def test_a_curated_refutation_is_its_own_relationship_not_a_flag(graph):
    """The rule `NO_EXCHANGE_WITH`, `DOES_NOT_INHIBIT_GROWTH_OF` and
    `DOES_NOT_METABOLISE` already follow, applied to a curated source: a
    refutation stored as a property is counted as an observation by every query
    that does not know to exclude it, and nothing in the query text would say
    so."""
    assert not rows(
        graph,
        f"MATCH (t:Taxon)-[r:{RELATION_METABOLISES}]->(s:Substance) "
        f"WHERE r.effect = 'not-metabolised' RETURN r LIMIT 1",
    )
    assert not rows(
        graph,
        f"MATCH (t:Taxon)-[r:{RELATION_ABUNDANCE_CHANGED}]->(s:Substance) "
        f"WHERE r.effect = 'unchanged' RETURN r LIMIT 1",
    )
    # And `effect` still groups the whole measured population in one property.
    effects = {
        r["e"]: r["n"] for r in rows(
            graph,
            "MATCH ()-[r]->(:Substance) RETURN r.effect AS e, count(*) AS n",
        )
    }
    assert effects == {
        "metabolised": METABOLISES, "not-metabolised": NO_METABOLISM,
        "increased": 3, "decreased": 3, "unchanged": ABUNDANCE_UNCHANGED,
    }


def test_direction_rides_on_the_changed_edge_and_nowhere_else(graph):
    assert {
        r["d"] for r in rows(
            graph,
            f"MATCH ()-[r:{RELATION_ABUNDANCE_CHANGED}]->() RETURN r.direction AS d",
        )
    } == {"increased", "decreased"}
    assert one(
        graph,
        f"MATCH ()-[r:{RELATION_ABUNDANCE_UNCHANGED}]->() RETURN r.direction AS d",
    )["d"] is None


def test_an_untypable_change_and_an_unread_category_are_ledger_rows(graph, csv_dir):
    """Two rows of the real file say `delay microbiota maturation`, and a
    category this loader has not read would be a claim of unknown direction. Both
    become no edge and a named ledger row rather than a plausible default."""
    reasons = {r["record_id"]: r["reason"] for r in ledger(csv_dir, "record")}
    assert set(reasons) == {"PMDBI7", "PMDBI13"}
    assert "no direction for" in reasons["PMDBI7"]
    assert "has not read" in reasons["PMDBI13"]
    assert not rows(
        graph,
        "MATCH ()-[r]->(:Substance) WHERE r.masi_record_id IN ['PMDBI7', 'PMDBI13'] "
        "RETURN r LIMIT 1",
    )


def test_one_record_id_on_two_rows_is_two_edges_with_two_keys(graph):
    """`Interation_Record_ID` is **not** unique: 2,891 of the real file's 12,512
    rows share an id with exactly one other, always a second microbe under one
    curated statement. Keying `source_record_id` on the id alone would collapse
    them into one edge and lose an organism."""
    pair = rows(
        graph,
        "MATCH (t:Taxon)-[r]->(:Substance) WHERE r.masi_record_id = 'PMDBI9' "
        "RETURN t.id AS tax_id, r.source_record_id AS key ORDER BY tax_id",
    )
    assert [r["tax_id"] for r in pair] == [B_THETA, B_LONGUM]
    assert len({r["key"] for r in pair}) == 2


# --------------------------------------------------------------------------
# The taxon end: three id routes, and two refusals
# --------------------------------------------------------------------------


def test_the_microbe_dictionary_supplies_the_id_the_record_leaves_out(graph):
    """`Microbe-Tax-ID` is `n.a.` on 4,965 interaction rows and `microbesInfo`
    recovers an id for 3,007 of them; for 92 more microbes it knows only the
    genus, and the claim is then made at the genus with `taxon_id_route` saying
    so. Skipping the dictionary would cost a quarter of this source."""
    genus = one(
        graph,
        f"MATCH (t:Taxon {{id: {BLAUTIA}}})-[r:{RELATION_ABUNDANCE_CHANGED}]->() "
        f"RETURN r.taxon_id_route AS route, r.reported_rank AS reported, "
        f"r.original_rank AS original, r.reported_name AS name",
    )
    assert genus == {
        "route": "genus", "reported": "genus", "original": "genus",
        "name": "Blautia spp.",
    }


def test_the_record_wins_a_taxid_disagreement_and_the_ledger_says_so(graph, csv_dir):
    """Three microbes and 69 rows of the real file carry one id in the record and
    another in the dictionary, and every one is the same shape: the class id
    against the phylum id for a name NCBI spells at both ranks. Neither is wrong,
    so preferring one silently would make the graph's rank depend on which table
    was read first."""
    assert one(
        graph,
        f"MATCH (t:Taxon)-[r:{RELATION_ABUNDANCE_CHANGED}]->() "
        f"WHERE r.masi_microbe_id = 'PMDBM5' "
        f"RETURN t.id AS tax_id, t.rank AS rank, r.reported_rank AS reported",
    ) == {"tax_id": BACTEROIDIA, "rank": "class", "reported": "phylum"}
    disagreement = [r for r in ledger(csv_dir, "microbe")
                    if r["record_id"] == "PMDBM5"]
    assert len(disagreement) == 1
    assert "976" in disagreement[0]["reason"] and "200643" in disagreement[0]["reason"]


def test_this_source_declares_no_broadest_accepted_rank(graph):
    """Unlike the two screens, whose every organism is one cultured isolate, MASI
    genuinely curates above genus — 45 families, 21 classes, 14 orders and 11
    phyla on the real file, and its most-cited disease organisms are *Firmicutes*
    and *Bacteroidetes*. A rank ceiling here would drop real curation, and
    `reported_rank` beside `original_rank` is what a query filters on instead."""
    ranks = {
        r["rank"] for r in rows(
            graph,
            "MATCH (t:Taxon)-[r]->(:Substance) RETURN DISTINCT t.rank AS rank",
        )
    }
    assert {"species", "genus", "class"} <= ranks


def test_an_organism_that_is_not_one_becomes_a_tombstone_and_no_edges(
    graph, csv_dir
):
    """`Unclassified gut microbiota` is the single most-cited "microbe" in the
    real file — 474 records — and it is not an organism. It has no taxid and no
    genus id, so it is an `UnresolvedTaxon` and costs its records, which on the
    real file is 388 of the 404 curated *non*-metabolism statements. The
    tombstone is keyed on MASI's accession rather than the name, because 24
    microbe ids are written under more than one spelling."""
    tombstones = [r for r in table(csv_dir, "unresolved_taxa.csv")
                  if r["source"] == SOURCE]
    assert len(tombstones) == UNRESOLVED_TAXA
    by_id = {r["unresolved_id"]: r for r in tombstones}
    assert set(by_id) == {
        f"unresolved:{SOURCE}:pmdbm6", f"unresolved:{SOURCE}:pmdbm99"
    }
    # The unclassified microbiota is cited by one interaction record and one
    # disease association, and both hits are counted.
    assert by_id[f"unresolved:{SOURCE}:pmdbm6"]["n_signatures"] == "2"
    assert not rows(
        graph,
        "MATCH ()-[r]->() WHERE r.masi_microbe_id IN ['PMDBM6', 'PMDBM99'] "
        "RETURN r LIMIT 1",
    )
    orphan = [r for r in ledger(csv_dir, "microbe") if r["record_id"] == "PMDBM99"]
    assert orphan and "no microbesInfo row" in orphan[0]["reason"]


# --------------------------------------------------------------------------
# The probiotic block — D10's leg, and the collision that used to lose it
# --------------------------------------------------------------------------


def test_a_probiotic_claim_survives_two_microbes_collapsing_onto_one_taxon(graph):
    """**A regression test for a data-loss bug in this loader.** 806 MASI
    microbes collapse onto 540 taxa, so several land on one node — *E. coli*
    Nissle 1917 promotes onto the same 562 as plain *E. coli*. `taxon_probiotic.csv`
    is keyed on tax_id and `Writer` keeps the first row per key, so whichever row
    was written first used to decide, and 5 of the real file's 46 probiotic
    claims disappeared that way. A claim beats a non-claim, and
    `probiotic_reported_name` keeps the name the claim was made under."""
    coli = one(
        graph,
        f"MATCH (t:Taxon {{id: {E_COLI}}}) RETURN t.probiotic AS probiotic, "
        f"t.probiotic_use_species AS used_in, "
        f"t.probiotic_research_stage AS stage, "
        f"t.probiotic_reported_name AS reported",
    )
    assert coli == {
        "probiotic": True, "used_in": ["Human"], "stage": ["Clinical trial"],
        "reported": ["Escherichia coli O157:H7"],
    }


def test_probiotic_is_three_state_and_null_is_not_false(graph):
    """`if_probiotic` is `Yes` on 46 microbes and `n.a.` on 760, and `n.a.` means
    "not recorded", not "not a probiotic". Collapsing null into false would turn
    "MASI does not cover this organism" into a claim about 862,000 taxa MASI
    never mentioned."""
    counts = {
        r["p"]: r["n"] for r in rows(
            graph, "MATCH (t:Taxon) RETURN t.probiotic AS p, count(*) AS n"
        )
    }
    assert counts[True] == PROBIOTIC_TAXA
    assert counts[False] == ANNOTATED_TAXA - PROBIOTIC_TAXA
    assert counts[None] > 0, "taxa MASI says nothing about must stay null"
    assert one(
        graph, f"MATCH (t:Taxon {{id: {B_THETA}}}) RETURN t.probiotic AS p"
    )["p"] is False


def test_the_probiotic_columns_are_written_even_with_no_masi_table(tmp_path):
    """`blueprints/core.json` declares four probiotic columns on `Taxon`, so
    `prep_taxonomy.py` must write them whether or not this source ran — otherwise
    the header a build produces would depend on which raw files are on the
    machine, and a MASI-less build would fail to load."""
    out = tmp_path / "csv"
    out.mkdir()
    (out / "cited_taxa.csv").write_text(
        "tax_id,source,n_signatures\n818,test,1\n", encoding="utf-8"
    )
    proc = subprocess.run(
        [sys.executable, str(SCRIPTS / "prep_taxonomy.py"),
         "--taxdump", str(TAXDUMP_MINI), "--out", str(out),
         "--scope", "cited", "--cited-from", str(out / "cited_taxa.csv")],
        capture_output=True, text=True, cwd=ROOT,
    )
    assert proc.returncode == 0, proc.stderr
    written = table(out, "taxon.csv")
    assert written and all(
        row["probiotic"] == "" and row["probiotic_reported_name"] == ""
        for row in written
    )


# --------------------------------------------------------------------------
# The disease end: a fourth ASSOCIATED_WITH source, keyed by name
# --------------------------------------------------------------------------


def test_the_disease_records_are_rows_in_the_shared_association_table(graph):
    """MASI is the fourth source of `ASSOCIATED_WITH` and writes into the same
    `taxon_condition.csv` BugSigDB, gutMDisorder and CARD do — a row, never a
    second relationship, so D2/D3/D17 span it without knowing it arrived."""
    assert one(
        graph,
        f"MATCH ()-[r:ASSOCIATED_WITH]->() WHERE r.primary_source = '{SOURCE}' "
        f"RETURN count(*) AS n",
    )["n"] == ASSOCIATIONS
    assert one(graph, "MATCH (d:Disease) RETURN count(*) AS n")["n"] == DISEASE_NODES


def test_a_disease_reaches_mondo_by_name_or_keeps_masi_own_id(graph):
    """MASI ships **no condition identifier at all** — 56 labels and nothing
    else — so the hub is reached by name, and the route is on the **edge** so it
    stays countable. 41 of the 56 join; the other 15 keep `MASI:DIS<n>` with
    `mondo_id` null, which is the same half-joined shape BugSigDB's 503
    own-CURIE terms already have.

    **The route is not on the `Disease` node**, and that is a correction rather
    than a preference: `disease.csv` is shared and key-deduped on
    `condition_id`, so on the real build 631 of the 783 MONDO ids MASI reaches
    were already written by BugSigDB or gutMDisorder — a node column would have
    read null for exactly the edges it was meant to describe. It is the same
    constraint that keeps a screen's `drug_class` off the `Drug` node."""
    joined = {
        r["id"]: (r["route"], r["mondo"], r["source_condition"])
        for r in rows(
            graph,
            "MATCH ()-[r:ASSOCIATED_WITH]->(d:Disease) "
            "RETURN d.id AS id, r.condition_join AS route, "
            "d.mondo_id AS mondo, d.source_condition AS source_condition",
        )
    }
    assert joined["MONDO:0005575"][:2] == ("mondo-name", "MONDO:0005575")
    assert joined["MONDO:0011122"][:2] == ("mondo-exact-synonym", "MONDO:0011122")
    # The abbreviation strip is what reaches this one.
    assert joined["MONDO:0005052"][0] == "mondo-name"
    assert joined["MONDO:0005052"][2] == "Irritable bowel syndrome (IBS)"
    # A RELATED synonym is not an identity, and a typo is not a lookup.
    assert joined["MASI:DIS4"][:2] == ("unmatched", None)
    assert joined["MASI:DIS5"][:2] == ("unmatched", None)
    assert not rows(
        graph, "MATCH (d:Disease) WHERE d.condition_join IS NOT NULL RETURN d LIMIT 1"
    )


def test_the_association_fills_eight_of_fourteen_and_says_which(graph):
    """The export has no design, host, sequencing-type, statistical-test or
    arm-size column, so all 784 of the real file's associations violate the
    fourteen-property contract — the same shape gutMDisorder's 1,636 do. Writing
    `Association-type` ("Microbe abundance associates with disease") into
    `study_design` would improve the audit number by misdescribing the data."""
    edge = one(
        graph,
        f"MATCH ()-[r:ASSOCIATED_WITH]->() WHERE r.primary_source = '{SOURCE}' "
        f"AND r.masi_record_id = 'PMDBDis1' "
        f"RETURN r.direction AS direction, r.evidence_level AS level, "
        f"r.study_design AS design, r.sequencing_type AS sequencing, "
        f"r.group_0_size AS g0, r.pmid AS pmid, r.knowledge_level AS knowledge, "
        f"r.source_licence AS licence, r.association_type AS association_type",
    )
    assert edge["direction"] == "decreased"
    assert edge["level"] == DISEASE_EVIDENCE_LEVEL == "unknown"
    assert edge["design"] is None and edge["sequencing"] is None
    assert edge["g0"] is None
    assert edge["pmid"] == 25079328
    assert edge["knowledge"] == "knowledge_assertion"
    assert edge["licence"] == "MASI-unstated"
    assert edge["association_type"] == "Microbe abundance associates with disease"


def test_a_pair_curated_in_both_directions_stays_two_edges(graph):
    """G4: disagreement is exposed, never resolved. One taxon and one disease
    with an increase in one paper and a decrease in another is two edges with
    two PMIDs, not a verdict."""
    both = rows(
        graph,
        f"MATCH (t:Taxon {{id: {B_THETA}}})-[r:ASSOCIATED_WITH]->"
        f"(d:Disease {{id: 'MONDO:0005575'}}) "
        f"WHERE r.primary_source = '{SOURCE}' "
        f"RETURN r.direction AS direction, r.pmid AS pmid ORDER BY direction",
    )
    assert [r["direction"] for r in both] == ["decreased", "increased"]
    assert len({r["pmid"] for r in both}) == 2


# --------------------------------------------------------------------------
# The evidence contract and the licence
# --------------------------------------------------------------------------


def test_every_interaction_edge_carries_the_nine_property_contract(graph):
    """The same nine the two screens carry, and every one written by the prep
    unconditionally — which is why both ontology rules are declared at `error`
    rather than `warn`."""
    for relationship in INTERACTION_RELATIONSHIPS:
        for field in CONTRACT:
            assert not rows(
                graph,
                f"MATCH ()-[r:{relationship}]->() WHERE r.{field} IS NULL "
                f"RETURN r LIMIT 1",
            ), f"{relationship}.{field} is null on at least one edge"


def test_the_audit_reports_zero_for_every_rule_this_source_writes(graph):
    audited = {
        r["rule"]: r for r in rows(
            graph,
            "CALL ontology_audit() YIELD rule, severity, violations, total "
            "RETURN rule, severity, violations, total",
        )
    }
    for relationship in (*INTERACTION_RELATIONSHIPS, RELATION_SAME_COMPOUND):
        for rule in ("required_properties", "property_types", "cardinality"):
            row = audited.get(f"{relationship}.{rule}")
            if row is None:
                continue
            assert row["violations"] == 0, f"{relationship}.{rule}"
            assert row["total"] > 0, (
                f"{relationship}.{rule} audits nothing — a rule at 0 / 0 is a "
                f"gate that cannot fail"
            )


def test_the_licence_token_says_unstated_rather_than_guessing(graph):
    """Neither the four downloads nor the download page states a licence. G3 puts
    the licence on the edge, so `WHERE r.source_licence <> 'MASI-unstated'` is
    the redistributable cut and this token contaminates nothing else — and it is
    a *different* token from the two screens', because three permissions are
    three permissions."""
    assert {
        r["l"] for r in rows(
            graph,
            "MATCH ()-[r]->(:Substance) RETURN DISTINCT r.source_licence AS l",
        )
    } == {"MASI-unstated"}
    assert one(
        graph,
        "MATCH ()-[r]->(:Substance) RETURN count(DISTINCT r.knowledge_level) AS k",
    )["k"] == 1


def test_the_aggregator_publication_is_not_the_edge_s_own_citation(graph):
    """What a MASI edge cites is the primary study its curator read; MASI's own
    NAR paper is a different claim about a different thing, and folding it into
    `publications` would make "which paper supports this?" return the database
    description."""
    edge = one(
        graph,
        f"MATCH (t:Taxon {{id: {B_THETA}}})-[r:{RELATION_METABOLISES}]->"
        f"(:Substance {{id: 'MASI:PMDBD6'}}) "
        f"RETURN r.publications AS publications, "
        f"r.aggregator_publication AS aggregator",
    )
    assert edge["publications"] == ["PMID:31158845"]
    assert edge["aggregator"] == "PMID:33313900"
    assert edge["publications"] != edge["aggregator"]


# --------------------------------------------------------------------------
# C18 accounting: every input row is an edge, a ledger row or a counted refusal
# --------------------------------------------------------------------------


def test_every_input_record_is_accounted_for(graph, csv_dir, prep_output):
    """Input rows = edges + refusals, with every refusal named. Nothing may be
    dropped in silence."""
    edges = one(graph, "MATCH ()-[r]->(:Substance) RETURN count(*) AS n")["n"]
    assert edges == EDGES
    refusals = {
        "unresolved microbe": 2,     # PMDBI3 and PMDBI8
        "untypable change": 1,       # PMDBI7
        "unread category": 1,        # PMDBI13
    }
    assert edges + sum(refusals.values()) == RECORDS
    assert len(table(csv_dir, f"unresolved_{SOURCE}.csv")) == LEDGER_ROWS


def test_the_ledger_deduplicates_a_finding_it_would_otherwise_repeat(csv_dir):
    """A disease MONDO does not name is one finding, not one row per association
    that cited it — 99 rows for 15 findings on the real file. How many records
    each finding cost is a counter in the report, which is where a count
    belongs."""
    diseases = ledger(csv_dir, "disease")
    assert sorted(r["record_id"] for r in diseases) == ["DIS4", "DIS5"]
