"""MiMeDB: a source that writes no edge, and the ways it could have written a
wrong one.

The headline assertion in this module is a **zero** —
:func:`test_mimedb_writes_no_taxon_metabolite_edge_because_there_is_none`. Both
published releases are two MySQL tables with no join between them, so the
per-taxon production edge D5 has been waiting for is not derivable from either,
and the loader says so with a count rather than by omission. v2.0 did not change
that: it added a ``microbe_relations`` column that holds an integer **count** of
related microbes and not one of their ids, which is MiMeDB stating the size of
the edge list it does not publish.

Everything else here is about identity: this source's whole contribution is
giving NJC19's free-text compounds something with an InChIKey to point at, and
every way of getting that wrong produces a *second node for one compound*, which
halves the evidence D6 computes over.

The fixtures are ``tests/fixtures/mimedb_mini/``, generated by
``tests/fixtures/make_mimedb_mini.py``, which names every record and its trap.
Both releases are generated because the loader reads either one.
"""

from __future__ import annotations

import csv
from pathlib import Path

import pytest

from prep_support import load_from_csv_dir, run_prep

from conftest import TAXDUMP_MINI

kglite = pytest.importorskip("kglite")

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parent / "fixtures"
MIMEDB_MINI = FIXTURES / "mimedb_mini"
NJC19_MINI = FIXTURES / "njc19_mini" / "41597_2020_516_MOESM1_ESM.xlsx"
HMDB_MINI = FIXTURES / "hmdb_mini" / "hmdb_metabolites.xml"
REACTOME_MINI = FIXTURES / "reactome_mini"
SCRIPTS = ROOT / "scripts"
PREPS_DIR = ROOT / "microbiomekg" / "preps"
PREP = PREPS_DIR / "prep_mimedb.py"


for _needed in (
    PREP,
    MIMEDB_MINI / "mimedb_metabolites_v2.csv",
    MIMEDB_MINI / "mimedb_microbes_v2.csv",
    MIMEDB_MINI / "mimedb_metabolites_v1.csv",
    MIMEDB_MINI / "mimedb_microbes_v1.csv",
    HMDB_MINI,
    NJC19_MINI,
):
    if not _needed.exists():
        pytest.skip(f"{_needed} does not exist yet", allow_module_level=True)

from microbiomekg.ontology.mimedb import (  # noqa: E402
    MICROBE_RELATION_COUNT,
    RELATIONSHIPS,
    SELECTION_RULES,
    V2_ONLY_COLUMNS,
    V2_ONLY_MICROBE_COLUMNS,
    normalise_hmdb_id,
    release_of,
)

SOURCE = "mimedb"

# --------------------------------------------------------------------------
# Golden values, derived from the fixture by hand and asserted exactly.
# --------------------------------------------------------------------------

RECORDS = 12  # metabolite records in the v2 fixture CSV
LOADED = 7  # new Metabolite nodes
NOT_SELECTED = 2  # Chitin (NJC19 never names it) and the glycerophospholipid
ALREADY_HELD = 3  # by accession, by name, by InChIKey — one each
CONTESTED_RECORDS = 2  # L-Tyrosine and D-Tyrosine, one accession
MICROBES = 8  # organism rows in the v2 fixture
MICROBES_WITH_TAXID = 7  # the fungus carries none, as six real v2 rows do not
LEDGER_ROWS = 5  # 3 already-held + 2 contested

#: The same fixture one release back. v1 has neither the twelfth metabolite
#: record nor the two extra organisms, which is what makes "v2 selects more"
#: a counted difference.
RECORDS_V1 = 11
LOADED_V1 = 6
MICROBES_V1 = 6


def run(script, *args):
    return run_prep(script, *args)


def build(work: Path, release: str) -> tuple[object, Path, str]:
    """HMDB then MiMeDB through their real preps, then the real blueprint.

    HMDB first because that is the declared order (`DEPENDS_ON = ["hmdb"]`):
    every "already held" test in this module is a test of what MiMeDB does when
    a node exists, and with no HMDB there is nothing to hold anything.
    """
    csv_dir = work / "csv"
    csv_dir.mkdir(parents=True, exist_ok=True)

    run(
        PREPS_DIR / "prep_hmdb.py",
        "--xml",
        str(HMDB_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--reactome",
        str(REACTOME_MINI),
        "--out",
        str(csv_dir),
    )
    prep = run(
        PREP,
        "--metabolites",
        str(MIMEDB_MINI / f"mimedb_metabolites_{release}.csv"),
        "--microbes",
        str(MIMEDB_MINI / f"mimedb_microbes_{release}.csv"),
        "--njc19",
        str(NJC19_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
    )
    run(
        PREPS_DIR / "prep_reactome.py",
        "--reactome",
        str(REACTOME_MINI),
        "--out",
        str(csv_dir),
    )
    run(
        PREPS_DIR / "prep_taxonomy.py",
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
        "--scope",
        "cited",
        "--cited-from",
        str(csv_dir / "cited_taxa.csv"),
    )

    sources = [SOURCE, "hmdb", "reactome"]
    return load_from_csv_dir(csv_dir, sources), csv_dir, prep.stdout


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    return build(tmp_path_factory.mktemp("mimedb"), "v2")


@pytest.fixture(scope="module")
def built_v1(tmp_path_factory):
    """The same build one release back, for the fallback path only."""
    return build(tmp_path_factory.mktemp("mimedb_v1"), "v1")


@pytest.fixture(scope="module")
def graph(built):
    return built[0]


@pytest.fixture(scope="module")
def csv_dir(built):
    return built[1]


@pytest.fixture(scope="module")
def prep_output(built):
    return built[2]


def rows(graph, query):
    return list(graph.cypher(query))


def one(graph, query):
    result = rows(graph, query)
    assert result, f"query returned no rows:\n{query}"
    return result[0]


def table(csv_dir, name):
    with (csv_dir / name).open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


# --------------------------------------------------------------------------
# The finding: no association exists in either published release
# --------------------------------------------------------------------------


def test_mimedb_writes_no_taxon_metabolite_edge_because_there_is_none(
    graph, prep_output
):
    """**The headline assertion of this module, and it is a zero.**

    Both downloads are `SELECT * FROM microbes` and `SELECT * FROM metabolites`;
    the join between them is in neither, in **v1.0 and in v2.0 alike**. The
    nearest thing to a relation in either is a `microbes.activity` column that
    says `Production (export)` or `Consumption (import)` **with no compound
    named anywhere on the row**. Deriving an edge from it would manufacture
    exactly the claim D5 asks for out of a field that does not make it. The
    fixture carries one row of each on purpose.

    A zero is only worth asserting if something could make it non-zero, and
    something could: this test fails the moment any relationship is declared
    for this source, which is the review gate on "MiMeDB finally has an edge
    list" being a deliberate change rather than an accident."""
    assert RELATIONSHIPS == {}
    for row in rows(
        graph, "MATCH ()-[r]->() RETURN DISTINCT r.primary_source AS source"
    ):
        assert row["source"] != SOURCE
    assert "PRODUCES edges from MiMeDB: 0" in prep_output
    # And the zero is stated against the release actually read, so a future v3
    # cannot inherit v2's finding by silence.
    assert "v2.0" in prep_output


def test_the_relation_count_column_is_a_count_and_never_an_edge(graph, prep_output):
    """v2.0's `microbe_relations` is the closest MiMeDB has ever come to
    publishing the association, and it still is not one: an integer per
    metabolite, no microbe id anywhere in the file. It rides on the node under a
    name that cannot be read as an edge count — a node property called
    `microbe_relations` beside a graph with zero MiMeDB edges is a trap — and
    the count is what makes "MiMeDB knows these pairs and does not publish them"
    a number.

    Acetic acid's real value is 2,537. The fixture carries it verbatim, and no
    edge in this graph corresponds to any of them."""
    assert MICROBE_RELATION_COUNT == "mimedb_microbe_relation_count"
    counts = {
        r["title"]: r["n"]
        for r in rows(
            graph,
            f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' "
            f"RETURN m.title AS title, m.{MICROBE_RELATION_COUNT} AS n",
        )
    }
    assert counts["Trimethylamine oxide"] == 146
    assert all(isinstance(n, int) for n in counts.values() if n is not None)
    # Zero is a value MiMeDB states, not an absence.
    assert (
        counts["Ethanoic acid" if "Ethanoic acid" in counts else "Pectin"] is not None
    )
    total = sum(n for n in counts.values() if n is not None)
    assert (
        f"microbe_relations: {total:,} taxon-metabolite pairs counted, 0 enumerated"
        in prep_output
    )


def test_an_absent_relation_count_is_empty_and_not_a_zero(graph):
    """`NULL-valued compound` leaves every optional column at the dump's literal
    `NULL`, `microbe_relations` included. Mapping that to `0` would state
    "MiMeDB relates this compound to no microbe", which is a measurement the
    file does not make — the same error as writing a `status` this source has
    no column for."""
    row = one(
        graph,
        "MATCH (m:Metabolite {title: 'NULL-valued compound'}) "
        f"RETURN m.{MICROBE_RELATION_COUNT} AS n",
    )
    assert row["n"] in (None, ""), f"an absent count arrived as {row['n']!r}"


def test_the_organisms_are_read_reported_and_not_loaded(graph, prep_output):
    """The microbes table resolves almost perfectly — nearly every row carries an
    NCBI taxid — and that is exactly the point: this source has the taxon side
    of D5's edge and nothing to attach it to. Reporting the number is what
    separates "MiMeDB does not close D5" from "MiMeDB has nothing"; loading it
    would put 2,648 unconnected `Taxon` nodes in the real graph."""
    assert (
        f"microbes: {MICROBES} organisms, {MICROBES_WITH_TAXID} with an NCBI taxid"
        in prep_output
    )
    assert "promoted 1" in prep_output, (
        "the strain-level row must promote to its species"
    )
    # Not in cited_taxa.csv, so the taxonomy build keeps none of them for MiMeDB.
    assert not rows(
        graph,
        f"MATCH (t:Taxon)-[r]->() WHERE r.primary_source = '{SOURCE}' RETURN t",
    )


def test_the_activity_column_is_reported_and_never_loaded(graph, prep_output):
    """115 rows of the real v2 microbes table say `Production (export)` or
    `Consumption (import)` and name **no compound**. They are counted in the
    report and land nowhere else: not an edge, and not a `Taxon` property
    either. A `mimedb_activity = 'Production (export)'` on a taxon is a
    production claim with no object, and D5 is the query that would read it as
    one — see `docs/model.md`.

    The graph therefore carries the string nowhere at all."""
    assert "activity: 1 Production (export), 1 Consumption (import)" in prep_output
    assert "names no compound" in prep_output
    assert not rows(
        graph,
        "MATCH (n) WHERE any(k IN keys(n) WHERE k CONTAINS 'activity') RETURN n LIMIT 1",
    )


# --------------------------------------------------------------------------
# Which release was read
# --------------------------------------------------------------------------


def test_the_release_is_detected_from_the_columns_not_the_filename(graph, prep_output):
    """A file's name is an operator's claim; its header is the dump's. The four
    v2-only columns are what says "this is v2.0", so a v2 file dropped in under
    a v1 name — or the reverse — cannot make the graph lie about its provenance.
    The release rides on every node this source writes, because a graph that
    outlives this build report has to be able to answer which release it holds."""
    assert release_of(["id", "name", "microbe_relations"]) == "v2.0"
    assert release_of(["id", "name", "hmdb_id"]) == "v1.0"
    # The two tables grew different columns, so a header list built only from
    # the metabolites side reports every v2 microbes dump as v1.0.
    assert not set(V2_ONLY_COLUMNS) & set(V2_ONLY_MICROBE_COLUMNS)
    assert release_of(["id", "name", "basys2_id"]) == "v2.0"
    # `description` is new to the microbes table and has always been in the
    # metabolites one, so it must never be a release marker.
    assert "description" in V2_ONLY_MICROBE_COLUMNS
    assert release_of(["id", "name", "description", "hmdb_id"]) == "v1.0"
    assert "MiMeDB v2.0" in prep_output
    assert "(MiMeDB v2.0)" in prep_output, "the microbes report names its own release"
    releases = {
        r["release"]
        for r in rows(
            graph,
            f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' "
            "RETURN DISTINCT m.mimedb_release AS release",
        )
    }
    assert releases == {"v2.0"}


def test_v1_still_loads_and_says_so(built_v1):
    """v2 is what a fresh clone should place, and v1 is what this project
    actually fetched in 2026-09 — the operator may have either. The fallback is
    a code path, so it is tested: the same rules select six of eleven records
    rather than seven of twelve, the four v2-only columns are absent rather than
    empty-by-accident, and the node says `v1.0`."""
    graph_v1, _csv_v1, out_v1 = built_v1
    assert "MiMeDB v1.0" in out_v1
    assert f"read {RECORDS_V1:,} metabolite records" in out_v1
    assert f"loaded {LOADED_V1:,} new Metabolite nodes" in out_v1
    assert (
        f"microbes: {MICROBES_V1} organisms, {MICROBES_V1} with an NCBI taxid" in out_v1
    )
    releases = {
        r["release"]
        for r in rows(
            graph_v1,
            f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' "
            "RETURN DISTINCT m.mimedb_release AS release",
        )
    }
    assert releases == {"v1.0"}
    # v1 has no such column, so nothing may claim a count for it.
    for row in rows(
        graph_v1,
        f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' "
        f"RETURN m.{MICROBE_RELATION_COUNT} AS n",
    ):
        assert row["n"] in (None, "")
    # And the edge count is still zero, which is the finding both releases make.
    assert "PRODUCES edges from MiMeDB: 0" in out_v1


# --------------------------------------------------------------------------
# The identities v2 added
# --------------------------------------------------------------------------


def test_the_v2_identity_columns_reach_the_node(graph):
    """`vmh_id` (Virtual Metabolic Human), `cmmc_inchikey` and the two EPA
    DSSTox ids are cross-references this graph has no other source for, and the
    whole reason MiMeDB is loaded at all is compound identity. Carrying them is
    the contribution; the values here are cut from the real v2 dump."""
    assert set(V2_ONLY_COLUMNS) == {
        "epa_substance_id",
        "epa_compound_id",
        "microbe_relations",
        "cmmc_inchikey",
    }
    tyr = one(
        graph,
        "MATCH (m:Metabolite {title: 'L-Tyrosine'}) "
        "RETURN m.vmh_id AS vmh, m.epa_substance_id AS sid, m.epa_compound_id AS cid",
    )
    assert tyr["vmh"] == "tyr_L"
    assert tyr["sid"] == "DTXSID1023730"
    assert tyr["cid"] == "DTXCID603730"


def test_a_multi_valued_vmh_id_is_carried_verbatim(graph):
    """83 rows of the real file hold several VMH ids joined by `; `, so the
    column is a *list* in a string. It is stored as the source wrote it rather
    than split on a guess: a consumer that splits can, and one that assumed a
    single id would silently key on `M03054; tmao`."""
    tmao = one(
        graph,
        "MATCH (m:Metabolite {title: 'Trimethylamine oxide'}) RETURN m.vmh_id AS vmh",
    )
    assert tmao["vmh"] == "M03054; tmao"


def test_cmmc_inchikey_is_carried_and_is_not_a_join_key(graph, csv_dir):
    """On 428 of the real file's 1,763 filled rows `cmmc_inchikey` differs from
    the record's own `moldb_inchikey` — it points at the *parent* compound of a
    microbial modification. Joining on it would fold a conjugate onto the
    compound it was made from, which is the same merge the contested-accession
    rule refuses.

    `Conjugated deoxycholate` carries HMDB's deoxycholic acid key in
    `cmmc_inchikey` and its own structure in `moldb_inchikey`. It must be its
    own node."""
    row = one(
        graph,
        "MATCH (m:Metabolite {title: 'Conjugated deoxycholate'}) "
        "RETURN m.id AS id, m.cmmc_inchikey AS cmmc, m.inchikey AS inchikey",
    )
    assert row["id"].startswith("MIMEDB:")
    assert row["cmmc"] == "KEY-0016-N"
    assert row["inchikey"] == "CONJDEOXYCHOL1-UHFFFAOYSA-N"
    # HMDB's deoxycholic acid kept its own node, and neither swallowed the other.
    assert rows(graph, "MATCH (m:Metabolite {title: 'Deoxycholic acid'}) RETURN m")
    assert not [
        r
        for r in table(csv_dir, "unresolved_mimedb.csv")
        if r["name"] == "Conjugated deoxycholate"
    ]


# --------------------------------------------------------------------------
# The selection rule
# --------------------------------------------------------------------------


def test_only_the_selected_slice_is_loaded(graph, prep_output):
    """41% of the real v2 file is glycerophospholipids. A loader that kept
    everything would put a lipidomics table in a microbiome graph, and the
    count is the assertion rather than "it built"."""
    loaded = one(
        graph, f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' RETURN count(m) AS n"
    )["n"]
    assert loaded == LOADED
    assert f"skipped {NOT_SELECTED} that no rule selected" in prep_output
    assert not rows(graph, "MATCH (m:Metabolite {title: 'PC(16:0/18:1)'}) RETURN m")


def test_each_selection_rule_is_recorded_on_the_node_it_kept(graph):
    """A rule described only in a docstring cannot be audited and cannot be
    changed safely."""
    kept = {
        r["rule"]
        for r in rows(
            graph,
            f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' "
            "UNWIND m.selection_rule AS rule RETURN DISTINCT rule",
        )
    }
    assert kept <= set(SELECTION_RULES)
    assert kept == {"observed", "origin-classified", "njc19-compound"}


def test_the_njc19_rule_selects_a_compound_njc19_needs_and_not_one_it_might(graph):
    """`Pectin` is in NJC19's fixture and no HMDB record holds it, so this
    record is what turns a minted stub into an identified compound. `Chitin` is
    the same *shape* of record and NJC19 never names it, so it is not loaded:
    the rule is "a compound NJC19 needs", not "a compound like the ones it
    needs"."""
    pectin = one(
        graph, "MATCH (m:Metabolite {title: 'Pectin'}) RETURN m.selection_rule AS r"
    )
    assert pectin["r"] == ["njc19-compound"]
    assert not rows(graph, "MATCH (m:Metabolite {title: 'Chitin'}) RETURN m")


# --------------------------------------------------------------------------
# Identity: the three ways a compound is "already held", and the one that lies
# --------------------------------------------------------------------------


def test_a_legacy_five_digit_accession_still_finds_its_node(graph, csv_dir):
    """HMDB widened its accessions from five digits to seven in 2018 and
    MiMeDB's column still holds both spellings in v2 — 258 of its 3,904 filled
    values are legacy. A literal string join misses every one of them
    **silently**, which reads as "MiMeDB has no HMDB id for this compound" — and
    then mints a second node for it."""
    assert normalise_hmdb_id("HMDB00011") == "HMDB0000011"
    assert normalise_hmdb_id("HMDB0000011") == "HMDB0000011"
    assert normalise_hmdb_id("NULL") == ""
    assert normalise_hmdb_id("CHEBI:30772") == ""
    assert not rows(graph, "MATCH (m:Metabolite {title: 'Butyrate salt'}) RETURN m")
    reason = [
        r
        for r in table(csv_dir, "unresolved_mimedb.csv")
        if r["name"] == "Butyrate salt"
    ]
    assert len(reason) == 1
    assert reason[0]["metabolite_id"] and "already holds" in reason[0]["reason"]


def test_a_compound_held_under_another_name_is_found_by_its_structure(graph, csv_dir):
    """`Ethanoic acid` and `Acetic acid` are one compound with two names, and
    only the InChIKey says so. Without the structural test this record becomes
    a second acetate node — and NJC19, which tries derived spellings in order,
    can then reach the new one while HMDB's producers stay on the old."""
    assert not rows(graph, "MATCH (m:Metabolite {title: 'Ethanoic acid'}) RETURN m")
    reason = [
        r
        for r in table(csv_dir, "unresolved_mimedb.csv")
        if r["name"] == "Ethanoic acid"
    ]
    assert len(reason) == 1 and "already holds" in reason[0]["reason"]


def test_a_contested_hmdb_accession_is_not_a_join_key(graph, csv_dir):
    """149 accessions in the real v2 file are claimed by two or more MiMeDB
    records each — 329 records in all — almost always a D-/L- enantiomer pair.
    Joining on one folds two compounds into one node and attributes each one's
    annotations to the other, so both records keep their own identity and the
    ledger says why — the same rule `reconcile` applies to an ambiguous organism
    name. The real pair spells one accession padded and the other legacy, which
    is why normalisation runs *before* the contest is decided."""
    ids = {
        r["title"]: r["id"]
        for r in rows(
            graph,
            "MATCH (m:Metabolite) WHERE m.title IN ['L-Tyrosine', 'D-Tyrosine'] "
            "RETURN m.title AS title, m.id AS id",
        )
    }
    assert set(ids) == {"L-Tyrosine", "D-Tyrosine"}
    assert ids["L-Tyrosine"] != ids["D-Tyrosine"]
    assert all(i.startswith("MIMEDB:") for i in ids.values())
    contested = [
        r
        for r in table(csv_dir, "unresolved_mimedb.csv")
        if "is claimed by" in r["reason"]
    ]
    assert len(contested) == CONTESTED_RECORDS
    assert all("HMDB0000158" in r["reason"] for r in contested)
    # And neither of them kept the accession, because it did not identify them.
    for row in rows(
        graph,
        "MATCH (m:Metabolite) WHERE m.title IN ['L-Tyrosine', 'D-Tyrosine'] "
        "RETURN m.hmdb_id AS hmdb_id",
    ):
        assert not row["hmdb_id"]


def test_an_already_held_compound_is_a_ledger_row_and_not_a_merge(
    graph, csv_dir, prep_output
):
    """`Writer` keys `metabolite.csv` on `metabolite_id` and the first row per
    key wins, so a MiMeDB row written for a compound HMDB already has would
    have its properties silently discarded — an outcome that reads like a
    successful join in the row count and is not one. Ledgering it makes
    "MiMeDB added nothing here" a number."""
    assert f"already has a node: {ALREADY_HELD}" in prep_output
    ledger = table(csv_dir, "unresolved_mimedb.csv")
    assert len(ledger) == LEDGER_ROWS
    assert all(r["source"] == SOURCE for r in ledger)
    held = [r for r in ledger if "already holds" in r["reason"]]
    assert len(held) == ALREADY_HELD
    assert all(r["metabolite_id"] for r in held), "a ledger row names the node that won"


# --------------------------------------------------------------------------
# What the node carries, and what it deliberately does not
# --------------------------------------------------------------------------


def test_a_mimedb_node_carries_no_invented_detection_status(graph):
    """`status` is HMDB's four-value vocabulary and this file has no such
    column. Writing a plausible value into a column another source's evidence
    rule reads would be inventing evidence; `mimedb_origin` carries what this
    file does grade on."""
    for row in rows(
        graph,
        f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' "
        "RETURN m.status AS status, m.microbial_origin AS origin, "
        "m.mimedb_id AS mimedb_id, m.inchikey AS inchikey",
    ):
        assert not row["status"]
        assert row["origin"] is False
        assert row["mimedb_id"].startswith("MMDBc")
        assert row["inchikey"]


def test_the_null_string_never_reaches_the_graph(graph):
    """The MySQL dump writes an absent value as the four characters `NULL`.
    Read straight that is the *string* "NULL" in a CSV column, which kglite
    loads as a value and `ontology_audit()` counts as present — a filled
    field that says nothing."""
    row = one(
        graph,
        "MATCH (m:Metabolite {title: 'NULL-valued compound'}) "
        "RETURN m.cas AS cas, m.chemical_formula AS formula, m.hmdb_id AS hmdb_id, "
        "m.vmh_id AS vmh_id, m.cmmc_inchikey AS cmmc",
    )
    assert not row["cas"] and not row["formula"] and not row["hmdb_id"]
    assert not row["vmh_id"] and not row["cmmc"]
    assert not rows(graph, "MATCH (m:Metabolite) WHERE m.cas = 'NULL' RETURN m")


def test_the_origin_axis_survives_onto_the_node(graph):
    """`metabolite_type` is the one thing the research document found MiMeDB
    grades on an evidence basis, and it is 97.5% empty in the real v2 file —
    which is a fact about the source that only survives if the column is
    loaded."""
    origins = {
        r["origin"]
        for r in rows(
            graph,
            f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' AND m.mimedb_origin <> '' "
            "RETURN DISTINCT m.mimedb_origin AS origin",
        )
    }
    assert origins == {"Co-metabolite", "Primary"}


def test_the_prep_reports_what_it_did_not_load(prep_output):
    for phrase in (
        "selection rule:",
        "that no rule selected",
        "not written because the compound already has a node:",
        "so not used as a join key:",
        "mimedb_origin:",
        "PRODUCES edges from MiMeDB: 0",
    ):
        assert phrase in prep_output


def test_every_record_is_a_node_or_a_counted_reason(prep_output, csv_dir):
    """Input records = loaded + not selected + ledger rows. A silent drop
    cannot hide in the difference."""
    ledger = table(csv_dir, "unresolved_mimedb.csv")
    # The two contested records are ledgered *and* loaded — the ledger row is
    # about the accession they lost, not about the record being dropped.
    assert LOADED + NOT_SELECTED + ALREADY_HELD == RECORDS
    assert len(ledger) == ALREADY_HELD + CONTESTED_RECORDS


@pytest.mark.fixture
def test_the_fixture_keeps_the_real_dumps_columns():
    """A fixture with a trimmed header would hide a column-name typo in the
    loader: every field this prep reads is addressed by name. Both releases are
    checked, because the loader reads either."""
    with (MIMEDB_MINI / "mimedb_metabolites_v2.csv").open(encoding="utf-8") as fh:
        columns = next(csv.reader(fh))
    assert len(columns) == 46
    assert columns[:3] == ["id", "name", "mime_id"]
    assert {
        "hmdb_id",
        "detected",
        "quantified",
        "metabolite_type",
        "moldb_inchikey",
        "moldb_formula",
        "moldb_average_mass",
        "cas",
        "vmh_id",
        "epa_substance_id",
        "epa_compound_id",
        "microbe_relations",
        "cmmc_inchikey",
    } <= set(columns)

    with (MIMEDB_MINI / "mimedb_microbes_v2.csv").open(encoding="utf-8") as fh:
        columns = next(csv.reader(fh))
    assert len(columns) == 44
    assert {"ncbi_tax_id", "activity", "species", "strain", "description"} <= set(
        columns
    )
    # And nothing in either header names the other table. `microbe_relations` is
    # a count on the *metabolite* side and is the closest either file comes.
    assert not {c for c in columns if "metabolite" in c}

    with (MIMEDB_MINI / "mimedb_metabolites_v1.csv").open(encoding="utf-8") as fh:
        assert len(next(csv.reader(fh))) == 42
    with (MIMEDB_MINI / "mimedb_microbes_v1.csv").open(encoding="utf-8") as fh:
        assert len(next(csv.reader(fh))) == 39
