"""gutMDisorder: the second source, and the pitfalls that make it one.

Every assertion here is a *failure mode first*. The fixture
(``tests/fixtures/gutmdisorder_mini/``, generated by
``tests/fixtures/make_gutmdisorder_mini.py``, which names every injected row)
carries one row per trap from ``docs/research/source-formats.md`` §1, and the
loader is measured against what each trap would silently do:

* an index of ``1.9999999999999`` truncated by ``int()`` lands on study **1**,
  a different paper;
* an index of ``2.5`` rounded lands on study 2 or 3 — one of them wrong;
* a duplicate row counted twice inflates the evidence for a claim;
* a both-direction pair collapsed to one edge resolves a disagreement by
  majority, which G4 forbids;
* a deleted taxid dropped removes an observation and leaves no trace;
* a merged taxid kept as given splits one organism into two nodes.

The second half of the module is what the *second source* is for: a paper, a
disease and a taxon cited by both sources have to be one node each, or the
graph is two graphs in one file.
"""

from __future__ import annotations

import csv
import json
import subprocess
import sys
from pathlib import Path

import pytest

from conftest import BUGSIGDB_MINI, MONDO_MINI, TAXDUMP_MINI

kglite = pytest.importorskip("kglite")

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = Path(__file__).resolve().parent / "fixtures" / "gutmdisorder_mini"
SCRIPTS = ROOT / "scripts"
PREP = SCRIPTS / "prep_gutmdisorder.py"

sys.path.insert(0, str(SCRIPTS))

for _needed in (PREP, FIXTURE / "human.xlsx", FIXTURE / "mouse.xlsx"):
    if not _needed.exists():
        pytest.skip(f"{_needed} does not exist yet", allow_module_level=True)

from prep_gutmdisorder import study_index  # noqa: E402

from microbiomekg.ontology import EVIDENCE_LEVEL_VALUES  # noqa: E402
from microbiomekg.ontology.gutmdisorder import (  # noqa: E402
    evidence_level,
    sequencing_type,
)

SOURCE = "gutmdisorder"

# --------------------------------------------------------------------------
# Golden values, derived from the fixture by hand and asserted exactly.
# --------------------------------------------------------------------------

#: gutMDisorder's own rows, before any join.
ASSOCIATION_ROWS = 29          # 25 human + 4 mouse as written in the workbooks
NON_INTEGRAL_INDEX = 1         # the 2.5 row: never rounded into a study
EXACT_DUPLICATES = 1           # the byte-identical repeat of one human row
GUTMD_STUDIES = 8              # 6 human Literature rows + 2 mouse
GUTMD_ASSOCIATED_WITH = 27
GUTMD_ABUNDANCE_CHANGED_BY = 6
GUTMD_LEDGER_ROWS = 3          # deleted taxon, no-endpoint study, non-integral index

#: Nodes that must be **one** node although two sources name them.
SHARED_PMID = 27007700         # cited by bugsigdb_mini and by gutmdisorder human 201
SHARED_DISEASE = "MONDO:0011122"   # obesity disorder: DOID:9970 and BugSigDB's MONDO id
MERGED_TAXON = 216572          # the survivor of 541000
DELETED_TAXID = "1036"


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    """Both sources through their real prep scripts, then the real blueprint."""
    work = tmp_path_factory.mktemp("gutmdisorder")
    csv_dir = work / "csv"
    csv_dir.mkdir()

    def run(script, *args):
        proc = subprocess.run(
            [sys.executable, str(script), *args], capture_output=True, text=True, cwd=ROOT
        )
        assert proc.returncode == 0, f"{script.name} failed:\n{proc.stdout}\n{proc.stderr}"
        return proc

    # BugSigDB first, so every shared table is one another source merges into
    # — which is the order scripts/build.py uses and the only thing that makes
    # "one paper, two sources" testable.
    run(
        SCRIPTS / "prep_bugsigdb.py",
        "--raw", str(BUGSIGDB_MINI),
        "--taxdump", str(TAXDUMP_MINI),
        "--mondo", str(MONDO_MINI),
        "--out", str(csv_dir),
    )
    prep = run(
        PREP,
        "--workbooks", str(FIXTURE),
        "--taxdump", str(TAXDUMP_MINI),
        "--mondo", str(MONDO_MINI),
        "--out", str(csv_dir),
    )
    run(
        SCRIPTS / "prep_taxonomy.py",
        "--taxdump", str(TAXDUMP_MINI),
        "--out", str(csv_dir),
        "--scope", "cited",
        "--cited-from", str(csv_dir / "cited_taxa.csv"),
    )

    from build_blueprint import compose

    from microbiomekg.ontology import ontology_for, write_json

    blueprint = compose(ROOT / "blueprints", ["bugsigdb", SOURCE])
    settings = blueprint.setdefault("settings", {})
    settings["root"] = str(csv_dir)
    for key in ("output", "output_path", "output_file"):
        settings.pop(key, None)
    write_json(csv_dir / "ontology.json", ontology_for(["bugsigdb", SOURCE]))
    blueprint["ontology"] = str(csv_dir / "ontology.json")
    local = csv_dir / "blueprint.test.json"
    local.write_text(json.dumps(blueprint))

    graph = kglite.from_blueprint(local, verbose=False, save=False)
    return graph, csv_dir, prep.stdout


@pytest.fixture(scope="module")
def graph(built):
    return built[0]


@pytest.fixture(scope="module")
def csv_dir(built):
    return built[1]


@pytest.fixture(scope="module")
def prep_output(built):
    return built[2]


def rows(graph, query):
    return list(graph.cypher(query))


def one(graph, query):
    result = rows(graph, query)
    assert result, f"query returned no rows:\n{query}"
    return result[0]


def table(csv_dir, name):
    with (csv_dir / name).open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


# --------------------------------------------------------------------------
# The index columns — the pitfall that attaches a result to the wrong paper
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "value, expected",
    [
        (2, 2),
        (2.0, 2),
        (1.9999999999999, 2),      # the real mouse noise
        (3.0000000000001, 3),      # and the other direction
        (33.9999999999999, 34),    # source-formats.md's worked example
    ],
)
def test_binary_noise_rounds_to_the_index_it_means(value, expected):
    assert study_index(value) == expected


def test_truncation_is_the_bug_this_replaces():
    """``int()`` does not merely lose a row — it files it under a different
    study. 33.9999999999999 becomes 33, and that association is then attributed
    to somebody else's paper with no warning anywhere."""
    assert int(33.9999999999999) == 33
    assert study_index(33.9999999999999) == 34


@pytest.mark.parametrize("value", [2.5, 2.1, "", None, float("nan"), "two"])
def test_a_value_that_is_not_an_integer_is_rejected_not_rounded(value):
    """2.5 is equidistant from two studies and 2.1 is simply not a study
    number. There is no honest way to pick, so the row is reported."""
    assert study_index(value) is None


def test_the_non_integral_row_reaches_the_ledger_and_no_edge(csv_dir, graph):
    ledger = [r for r in table(csv_dir, "unresolved_associations.csv")
              if "not an integer" in r["reason"]]
    assert len(ledger) == NON_INTEGRAL_INDEX
    assert ledger[0]["study_index"] == "2.5"
    assert not rows(
        graph,
        "MATCH ()-[r:ASSOCIATED_WITH]->() WHERE r.study_id CONTAINS 'human-2' "
        "AND r.primary_source = 'gutmdisorder' AND r.study_id ENDS WITH '-2' "
        "RETURN r LIMIT 1",
    )


def test_the_mouse_rows_land_on_the_studies_they_belong_to(graph):
    """Both mouse studies share a PMID, so a mis-join would be invisible in the
    citation — it shows up here, as an edge under the wrong study id."""
    got = {
        (r["study"], r["taxon"])
        for r in rows(
            graph,
            "MATCH (t:Taxon)-[r:ASSOCIATED_WITH]->() "
            "WHERE r.study_id STARTS WITH 'STUDY:gutmdisorder-mouse' "
            "RETURN r.study_id AS study, t.id AS taxon",
        )
    }
    assert got == {
        ("STUDY:gutmdisorder-mouse-2", 31979),
        ("STUDY:gutmdisorder-mouse-2", 39491),
        ("STUDY:gutmdisorder-mouse-3", 1578),
        ("STUDY:gutmdisorder-mouse-3", 1678),
    }


# --------------------------------------------------------------------------
# Duplicates, contradictions, and what may never be collapsed
# --------------------------------------------------------------------------


def test_an_exact_duplicate_is_one_edge_that_says_it_was_repeated(graph):
    """Two identical curated rows are one fact stated twice, not two
    independent observations — counting them twice would inflate the evidence
    for the claim. The count survives as `duplicate_rows` so nothing is lost."""
    result = one(
        graph,
        "MATCH (t:Taxon {id: 816})-[r:ASSOCIATED_WITH]->(d:Disease {id: 'MONDO:0011122'}) "
        "WHERE r.primary_source = 'gutmdisorder' "
        "RETURN count(r) AS edges, sum(r.duplicate_rows) AS rows_behind_them",
    )
    assert result["edges"] == 1
    assert result["rows_behind_them"] == 2


def test_a_both_direction_pair_stays_two_edges(graph):
    """G4: a pair carrying both directions is returned as two rows with their
    evidence, never reduced to a sign and never resolved by majority."""
    result = rows(
        graph,
        "MATCH (t:Taxon {id: 838})-[r:ASSOCIATED_WITH]->(d:Disease {id: 'MONDO:0011122'}) "
        "WHERE r.primary_source = 'gutmdisorder' "
        "RETURN r.direction AS direction, r.source_relation AS relation",
    )
    assert sorted(r["direction"] for r in result) == ["decreased", "increased"]
    # The source's own sentence is what distinguishes them, and it is kept.
    assert len({r["relation"] for r in result}) == 2


def test_the_duplicate_count_is_one_where_nothing_was_duplicated(graph):
    """A `duplicate_rows` that is silently null on the normal case would make
    the property unusable in a filter."""
    result = one(
        graph,
        "MATCH ()-[r:ASSOCIATED_WITH]->() WHERE r.primary_source = 'gutmdisorder' "
        "RETURN count(r) AS edges, "
        "sum(CASE WHEN r.duplicate_rows IS NULL THEN 1 ELSE 0 END) AS missing",
    )
    assert result["edges"] == GUTMD_ASSOCIATED_WITH
    assert result["missing"] == 0


# --------------------------------------------------------------------------
# Taxon reconciliation — the same policy BugSigDB uses
# --------------------------------------------------------------------------


def test_a_merged_taxid_lands_on_the_survivor_keeping_the_id_as_given(graph):
    result = rows(
        graph,
        "MATCH (t:Taxon)-[r:ASSOCIATED_WITH]->() WHERE r.reported_tax_id = 541000 "
        "RETURN t.id AS tax_id, r.resolution_status AS status, "
        "r.reported_name AS reported",
    )
    assert result, "the merged id resolved to nothing"
    for row in result:
        assert row["tax_id"] == MERGED_TAXON
        assert row["status"] == "merged"
    assert not rows(graph, "MATCH (t:Taxon {id: 541000}) RETURN t")


def test_a_deleted_taxid_becomes_a_tombstone_and_a_ledger_row(graph, csv_dir):
    """G2: nothing is dropped. gutMDisorder has no Signature node to wire the
    tombstone to — BugSigDB's is wired by REPORTED_BY — so the association it
    would have carried is recorded in the ledger instead of vanishing."""
    tombstone = one(
        graph,
        f"MATCH (u:UnresolvedTaxon) WHERE u.source = '{SOURCE}' "
        "RETURN u.id AS id, u.status AS status, u.reported_tax_id AS tax_id, "
        "u.note AS note",
    )
    assert tombstone["status"] == "deleted"
    assert tombstone["tax_id"] == int(DELETED_TAXID)
    assert "delnodes" in tombstone["note"]
    ledger = [r for r in table(csv_dir, "unresolved_associations.csv")
              if r["reported_tax_id"] == DELETED_TAXID]
    assert len(ledger) == 1 and "deleted" in ledger[0]["reason"]
    assert not rows(
        graph,
        f"MATCH ()-[r:ASSOCIATED_WITH]->() WHERE r.reported_tax_id = {DELETED_TAXID} "
        "RETURN r",
    )


def test_a_row_with_no_taxid_resolves_by_name(graph):
    """3.7% of gutMDisorder's association rows carry no NCBI id. Pairing on the
    id column alone would drop them without a word."""
    result = rows(
        graph,
        "MATCH (t:Taxon)-[r:ASSOCIATED_WITH]->() "
        "WHERE r.reported_name = 'Escherichia coli' AND r.primary_source = 'gutmdisorder' "
        "RETURN DISTINCT t.id AS tax_id, r.reported_tax_id AS reported",
    )
    assert result and all(r["tax_id"] == 562 for r in result)
    assert all(r["reported"] is None for r in result)


# --------------------------------------------------------------------------
# The disease endpoint, through the MONDO hub
# --------------------------------------------------------------------------


def test_a_malformed_doid_reaches_the_ledger_and_no_disease_node(graph, csv_dir):
    """`DOID:00400085` is 8 digits with a leading double zero where DOID ids
    are 1–7 — a typo at the source, not a coverage gap, and the difference has
    to survive into the ledger's reason."""
    ledger = [r for r in table(csv_dir, "unresolved_conditions.csv")
              if r["source"] == SOURCE]
    assert [r["source_id"] for r in ledger] == ["DOID:00400085"]
    assert "malformed" in ledger[0]["reason"]
    assert not rows(graph, "MATCH (d:Disease {id: 'DOID:00400085'}) RETURN d")


def test_an_unmapped_doid_keeps_its_own_curie_with_a_null_mondo_id(graph):
    result = {
        r["id"]: r
        for r in rows(
            graph,
            "MATCH (d:Disease) WHERE d.source_vocabulary = 'DOID' AND d.mondo_id IS NULL "
            "RETURN d.id AS id, d.title AS label, d.source_id AS source_id",
        )
    }
    assert set(result) == {"DOID:8878", "DOID:8577"}
    # The comma-multivalued cell paired positionally with its two labels,
    # through the same policy BugSigDB's condition column uses.
    assert result["DOID:8878"]["label"] == "Crohn's disease"
    assert result["DOID:8577"]["label"] == "ulcerative colitis"


def test_a_mapped_doid_is_keyed_on_the_mondo_hub(graph):
    """DOID:9778 becomes MONDO:0005052 — the join MONDO was added for, and the
    half of the hub BugSigDB could not use (none of its 394 EFO ids has a MONDO
    equivalence; DOID has 11,258).

    Note what ``source_id`` means on a node two sources reach: **the id the node
    was keyed from**, which is whichever source created it — here BugSigDB's own
    MONDO id, because it ran first. It is not a list of every id that resolved
    here, and it does not try to be: the per-source ids live on the edges, which
    carry ``primary_source``, and the equivalence itself is MONDO's to state.
    A node with no MONDO id cannot collide this way, because an unmapped term
    keeps its own CURIE as its key."""
    result = one(
        graph,
        "MATCH (d:Disease {id: 'MONDO:0005052'}) "
        "RETURN d.title AS label, d.mondo_id AS mondo_id, count(d) AS n",
    )
    assert result["label"] == "irritable bowel syndrome"
    assert result["mondo_id"] == "MONDO:0005052"
    reached = one(
        graph,
        "MATCH ()-[r:ASSOCIATED_WITH]->(d:Disease {id: 'MONDO:0005052'}) "
        "WHERE r.primary_source = 'gutmdisorder' RETURN count(r) AS edges",
    )
    assert reached["edges"] == 3


# --------------------------------------------------------------------------
# The evidence a gutMDisorder edge carries
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "technology, expected",
    [
        ("16S rRNA sequences", "16S"),
        ("16S rDNA sequences", "16S"),
        ("16S rRNA sequences,qPCR", "16S"),
        ("quantitative metagenomics by shotgun sequencing", "WMS"),
        ("16S rRNA sequences,quantitative metagenomics by shotgun sequencing", "WMS"),
        ("qPCR", "PCR"),
        ("RT-qPCR", "PCR"),
        ("denaturing gradient gel electrophoresis", "PCR"),
        ("", ""),
        (None, ""),
    ],
)
def test_the_free_text_assay_maps_onto_the_graphs_vocabulary(technology, expected):
    """`r.sequencing_type = '16S'` has to mean the same thing on a gutMDisorder
    edge as on a BugSigDB one, or D9 is not one query. The strongest assay wins:
    a study that ran both shotgun and 16S supports the shotgun claim."""
    assert sequencing_type(technology) == expected


@pytest.mark.parametrize(
    "workbook, research_type, technology, expected",
    [
        ("mouse", "Gut microbiota associated with disorder", "16S rRNA sequences",
         "in-vivo-model"),
        # G6: a mouse intervention is still animal evidence.
        ("mouse", "Interventions change the composition of gut microbiota",
         "16S rRNA sequences", "in-vivo-model"),
        ("human", "Interventions change the composition of gut microbiota",
         "16S rRNA sequences", "interventional-rct"),
        ("human", "Gut microbiota for adjuvant therapy", "qPCR", "interventional-rct"),
        ("human", "Gut microbiota associated with disorder", "16S rRNA sequences",
         "observational-16S"),
        ("human", "Gut microbiota associated with disorder",
         "quantitative metagenomics by shotgun sequencing", "observational-shotgun"),
        ("human", "Gut microbiota associated with disorder", "qPCR",
         "observational-targeted"),
        ("human", "Gut microbiota associated with disorder", "",
         "observational-unspecified"),
    ],
)
def test_evidence_level_follows_part_bs_table(workbook, research_type, technology, expected):
    assert evidence_level(workbook, research_type, technology) == expected


def test_every_level_written_is_one_of_the_twelve(graph):
    """A near-miss spelling is a silent filter miss: `observational_16s` would
    export cleanly and match nothing."""
    used = {
        r["level"]
        for r in rows(
            graph,
            "MATCH ()-[r:ASSOCIATED_WITH|ABUNDANCE_CHANGED_BY]->() "
            "WHERE r.primary_source = 'gutmdisorder' "
            "RETURN DISTINCT r.evidence_level AS level",
        )
    }
    assert used <= set(EVIDENCE_LEVEL_VALUES)
    assert "in-vivo-model" in used


def test_the_whole_mouse_workbook_is_animal_evidence(graph):
    result = rows(
        graph,
        "MATCH ()-[r:ASSOCIATED_WITH|ABUNDANCE_CHANGED_BY]->() "
        "WHERE r.study_id STARTS WITH 'STUDY:gutmdisorder-mouse' "
        "RETURN DISTINCT r.evidence_level AS level, r.host_species AS host",
    )
    assert result == [{"level": "in-vivo-model", "host": "Mus musculus"}]


def test_group_sizes_are_absent_and_the_study_level_ones_say_so(graph):
    """An Association row has no link to a Sample row, so there is no
    per-association group size. Filling `group_0_size` from the study's first
    arm would invent a fact and make the audit look better for it; the study's
    arms are carried separately, scoped, and the gap is counted."""
    result = one(
        graph,
        "MATCH ()-[r:ASSOCIATED_WITH]->() WHERE r.primary_source = 'gutmdisorder' "
        "RETURN count(r) AS edges, "
        "sum(CASE WHEN r.group_0_size IS NULL THEN 1 ELSE 0 END) AS no_group0, "
        "sum(CASE WHEN r.group_1_size IS NULL THEN 1 ELSE 0 END) AS no_group1, "
        "sum(CASE WHEN r.study_sample_size IS NULL THEN 1 ELSE 0 END) AS no_total, "
        "collect(DISTINCT r.sample_size_scope) AS scope",
    )
    assert result["no_group0"] == result["edges"]
    assert result["no_group1"] == result["edges"]
    assert result["no_total"] == 0
    assert result["scope"] == ["study-level (not per-association)"]


def test_a_three_arm_study_carries_all_three_arm_sizes(graph):
    """The mouse study has three arms. Any two-group model of it is wrong, and
    that is exactly why the sizes are a list rather than a pair."""
    result = one(
        graph,
        "MATCH ()-[r:ASSOCIATED_WITH]->() "
        "WHERE r.study_id = 'STUDY:gutmdisorder-mouse-2' "
        "RETURN DISTINCT r.study_arm_sizes AS arms, r.study_sample_size AS total",
    )
    assert result["arms"] == ["10", "16", "16"]
    assert result["total"] == 42


def test_every_edge_carries_its_provenance_and_an_unknown_licence(graph):
    """G3. `unknown` is a value, not a gap: the site states no licence, and
    recording it keeps the redistribution question one WHERE clause away
    instead of implying a permission nobody granted."""
    result = rows(
        graph,
        "MATCH ()-[r:ASSOCIATED_WITH|ABUNDANCE_CHANGED_BY]->() "
        "WHERE r.primary_source = 'gutmdisorder' "
        "RETURN DISTINCT r.source_licence AS licence, r.knowledge_level AS kl, "
        "r.agent_type AS agent",
    )
    assert result == [{
        "licence": "unknown",
        "kl": "statistical_association",
        "agent": "manual_agent",
    }]


def test_the_source_records_no_study_design_and_says_so(graph):
    """`Research Type` is a curation category, not a design. Writing it into
    `study_design` would improve the audit number by misdescribing the data."""
    result = one(
        graph,
        "MATCH ()-[r:ASSOCIATED_WITH]->() WHERE r.primary_source = 'gutmdisorder' "
        "RETURN count(r) AS edges, "
        "sum(CASE WHEN r.study_design IS NULL THEN 1 ELSE 0 END) AS no_design, "
        "sum(CASE WHEN r.research_type IS NULL THEN 1 ELSE 0 END) AS no_research_type",
    )
    assert result["no_design"] == result["edges"]
    assert result["no_research_type"] == 0


# --------------------------------------------------------------------------
# Interventions — D4's missing leg
# --------------------------------------------------------------------------


def test_an_intervention_is_its_own_node_with_its_drugbank_id(graph):
    result = {
        r["id"]: r
        for r in rows(
            graph,
            "MATCH (i:Intervention) RETURN i.id AS id, i.title AS label, "
            "i.drugbank_id AS drugbank_id, i.intervention_type AS type",
        )
    }
    assert set(result) == {
        "INTERVENTION:rehmannia-glutinosa-root",
        "INTERVENTION:epigallocatechin-gallate",
    }
    assert result["INTERVENTION:epigallocatechin-gallate"]["drugbank_id"] == "DB12116"
    assert result["INTERVENTION:epigallocatechin-gallate"]["type"] == "Drug"


def test_the_intervention_edge_is_not_an_association(graph):
    """"This drug changed this taxon" and "this taxon is associated with this
    disease" are different claims with different directions. Collapsing them
    into one relationship is MDAD's documented weakness."""
    result = one(
        graph,
        "MATCH (t:Taxon)-[r:ABUNDANCE_CHANGED_BY]->(i:Intervention) "
        "RETURN count(r) AS edges, count(DISTINCT i.id) AS interventions",
    )
    assert result["edges"] == GUTMD_ABUNDANCE_CHANGED_BY
    assert result["interventions"] == 2


def test_an_intervention_study_with_a_doid_reaches_both_endpoints(graph):
    """Study 234 intervenes *and* names a disease, so its taxa carry both
    edges. Neither may swallow the other."""
    result = one(
        graph,
        "MATCH ()-[r]->() WHERE r.study_id = 'STUDY:gutmdisorder-human-234' "
        "RETURN count(r) AS edges, collect(DISTINCT type(r)) AS types",
    )
    assert sorted(result["types"]) == ["ABUNDANCE_CHANGED_BY", "ASSOCIATED_WITH"]
    assert result["edges"] == 8


# --------------------------------------------------------------------------
# Two sources, one graph
# --------------------------------------------------------------------------


def test_a_paper_cited_by_both_sources_is_one_node(graph):
    """`Paper` is keyed on the PMID and nothing else, which is what makes
    "what else does this paper support?" a one-hop query across sources."""
    result = one(
        graph,
        f"MATCH (p:Paper {{id: {SHARED_PMID}}})<-[:PUBLISHED_AS]-(s:Study) "
        "RETURN count(s) AS studies, collect(DISTINCT s.source) AS sources",
    )
    assert result["studies"] >= 2
    assert sorted(x for x in result["sources"] if x) == [SOURCE]
    assert one(graph, f"MATCH (p:Paper {{id: {SHARED_PMID}}}) RETURN count(p) AS n")["n"] == 1


def test_a_disease_cited_by_both_sources_is_one_node_with_both_sources_edges(graph):
    """BugSigDB reaches obesity by its MONDO id and gutMDisorder by DOID:9970.
    The hub is what makes them the same node — and D3's cross-condition count
    is wrong if they are not."""
    result = one(
        graph,
        f"MATCH ()-[r:ASSOCIATED_WITH]->(d:Disease {{id: '{SHARED_DISEASE}'}}) "
        "RETURN collect(DISTINCT r.primary_source) AS sources, count(r) AS edges",
    )
    assert sorted(result["sources"]) == ["bugsigdb", "gutmdisorder"]


def test_a_taxon_cited_by_both_sources_is_one_node(graph):
    result = rows(
        graph,
        "MATCH (t:Taxon)-[r:ASSOCIATED_WITH]->() "
        "WITH t, collect(DISTINCT r.primary_source) AS sources "
        "WHERE size(sources) > 1 RETURN t.id AS tax_id, t.title AS name",
    )
    assert result, "no taxon is cited by both sources — the join is not happening"


def test_the_cited_taxa_table_carries_both_sources_counts(csv_dir):
    """`cited_taxa.csv` drives which taxa the taxonomy build keeps, so a source
    that overwrote another's rows instead of merging would silently shrink the
    graph to whichever source ran last.

    One row per (taxon, source), not one row carrying a sum: the ``source``
    column is what lets a prep re-run replace its own contribution, and a taxon
    both sources cite is then two attributable counts rather than a total
    nobody can take apart."""
    rows_ = table(csv_dir, "cited_taxa.csv")
    assert rows_, "cited_taxa.csv is empty"
    counts: dict[str, dict[str, int]] = {}
    for row in rows_:
        counts.setdefault(row["tax_id"], {})[row["source"]] = int(row["n_signatures"])
    assert {"bugsigdb", SOURCE} <= {r["source"] for r in rows_}
    # 853 (Faecalibacterium prausnitzii) is cited by both sources, so its total
    # is more than either alone and both halves are still readable.
    assert set(counts["853"]) == {"bugsigdb", SOURCE}
    assert sum(counts["853"].values()) >= 2


# --------------------------------------------------------------------------
# C18 accounting — every input row is an edge, a ledger row or a counted drop
# --------------------------------------------------------------------------


def test_every_association_row_is_accounted_for(graph, csv_dir, prep_output):
    """Input rows = edges + ledger records + explicitly reported collapses.
    The point of the rule is that a silent drop cannot hide in the difference."""
    edges = one(
        graph,
        "MATCH ()-[r:ASSOCIATED_WITH]->() WHERE r.primary_source = 'gutmdisorder' "
        "RETURN count(DISTINCT r.source_record_id + '|' + r.direction) AS n",
    )["n"]
    intervention_only = 1  # study 234's taxa reach both endpoints; only its rows
    ledger = table(csv_dir, "unresolved_associations.csv")
    assert len(ledger) == GUTMD_LEDGER_ROWS
    # One edge per surviving row; a row reaching two diseases is still one row.
    surviving = ASSOCIATION_ROWS - EXACT_DUPLICATES - len(ledger)
    assert edges + intervention_only == surviving + 1  # mouse-3's rows are intervention+disease
    assert f"{EXACT_DUPLICATES} exact duplicates collapsed" in prep_output


def test_the_prep_reports_what_it_did_not_load(prep_output):
    """A build log that only reports successes cannot be audited."""
    for phrase in ("not loaded:", "malformed DOIDs", "exact duplicates collapsed"):
        assert phrase in prep_output


def test_the_study_count_is_one_per_literature_row(graph):
    result = one(
        graph,
        f"MATCH (s:Study) WHERE s.source = '{SOURCE}' RETURN count(s) AS n",
    )
    assert result["n"] == GUTMD_STUDIES


def test_the_audit_has_no_vacuous_rule_for_this_build(graph):
    """A rule with a zero denominator is a gate that cannot fail — which is how
    a second source's relationship silently audits nothing."""
    for r in rows(
        graph, "CALL ontology_audit() YIELD rule, total RETURN rule, total"
    ):
        assert r["total"] > 0, f"{r['rule']} audits nothing"
