"""MiMeDB: a source that writes no edge, and the four ways it could have written
a wrong one.

The headline assertion in this module is a **zero** —
:func:`test_mimedb_writes_no_taxon_metabolite_edge_because_there_is_none`. The
downloads on disk are two MySQL tables with no join between them, so the
per-taxon production edge D5 has been waiting for is not derivable from them,
and the loader says so with a count rather than by omission. Everything else
here is about identity: this source's whole contribution is giving NJC19's
free-text compounds something with an InChIKey to point at, and every way of
getting that wrong produces a *second node for one compound*, which halves the
evidence D6 computes over.

The fixture is ``tests/fixtures/mimedb_mini/``, generated by
``tests/fixtures/make_mimedb_mini.py``, which names every record and its trap.
"""

from __future__ import annotations

import csv
import json
import subprocess
import sys
from pathlib import Path

import pytest

from conftest import TAXDUMP_MINI

kglite = pytest.importorskip("kglite")

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parent / "fixtures"
MIMEDB_MINI = FIXTURES / "mimedb_mini"
NJC19_MINI = FIXTURES / "njc19_mini" / "41597_2020_516_MOESM1_ESM.xlsx"
HMDB_MINI = FIXTURES / "hmdb_mini" / "hmdb_metabolites.xml"
REACTOME_MINI = FIXTURES / "reactome_mini"
SCRIPTS = ROOT / "scripts"
PREP = SCRIPTS / "prep_mimedb.py"

sys.path.insert(0, str(SCRIPTS))

for _needed in (PREP, MIMEDB_MINI / "mimedb_metabolites_v1.csv",
                MIMEDB_MINI / "mimedb_microbes_v1.csv", HMDB_MINI, NJC19_MINI):
    if not _needed.exists():
        pytest.skip(f"{_needed} does not exist yet", allow_module_level=True)

from microbiomekg.ontology.mimedb import (  # noqa: E402
    RELATIONSHIPS,
    SELECTION_RULES,
    normalise_hmdb_id,
)

SOURCE = "mimedb"

# --------------------------------------------------------------------------
# Golden values, derived from the fixture by hand and asserted exactly.
# --------------------------------------------------------------------------

RECORDS = 11            # metabolite records in the fixture CSV
LOADED = 6              # new Metabolite nodes
NOT_SELECTED = 2        # Chitin (NJC19 never names it) and the glycerophospholipid
ALREADY_HELD = 3        # by accession, by name, by InChIKey — one each
CONTESTED_RECORDS = 2   # L-Tyrosine and D-Tyrosine, one accession
MICROBES = 6
LEDGER_ROWS = 5         # 3 already-held + 2 contested


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    """HMDB then MiMeDB through their real preps, then the real blueprint.

    HMDB first because that is the declared order (`DEPENDS_ON = ["hmdb"]`):
    every "already held" test in this module is a test of what MiMeDB does when
    a node exists, and with no HMDB there is nothing to hold anything.
    """
    work = tmp_path_factory.mktemp("mimedb")
    csv_dir = work / "csv"
    csv_dir.mkdir()

    def run(script, *args):
        proc = subprocess.run(
            [sys.executable, str(script), *args], capture_output=True, text=True, cwd=ROOT
        )
        assert proc.returncode == 0, f"{script.name} failed:\n{proc.stdout}\n{proc.stderr}"
        return proc

    run(
        SCRIPTS / "prep_hmdb.py",
        "--xml", str(HMDB_MINI),
        "--taxdump", str(TAXDUMP_MINI),
        "--reactome", str(REACTOME_MINI),
        "--out", str(csv_dir),
    )
    prep = run(
        PREP,
        "--metabolites", str(MIMEDB_MINI / "mimedb_metabolites_v1.csv"),
        "--microbes", str(MIMEDB_MINI / "mimedb_microbes_v1.csv"),
        "--njc19", str(NJC19_MINI),
        "--taxdump", str(TAXDUMP_MINI),
        "--out", str(csv_dir),
    )
    run(SCRIPTS / "prep_reactome.py", "--reactome", str(REACTOME_MINI), "--out", str(csv_dir))
    run(
        SCRIPTS / "prep_taxonomy.py",
        "--taxdump", str(TAXDUMP_MINI),
        "--out", str(csv_dir),
        "--scope", "cited",
        "--cited-from", str(csv_dir / "cited_taxa.csv"),
    )

    from build_blueprint import compose

    from microbiomekg.ontology import ontology_for, write_json

    sources = [SOURCE, "hmdb", "reactome"]
    blueprint = compose(ROOT / "blueprints", sources)
    settings = blueprint.setdefault("settings", {})
    settings["root"] = str(csv_dir)
    for key in ("output", "output_path", "output_file"):
        settings.pop(key, None)
    write_json(csv_dir / "ontology.json", ontology_for(sources))
    blueprint["ontology"] = str(csv_dir / "ontology.json")
    local = csv_dir / "blueprint.test.json"
    local.write_text(json.dumps(blueprint))

    return kglite.from_blueprint(local, verbose=False, save=False), csv_dir, prep.stdout


@pytest.fixture(scope="module")
def graph(built):
    return built[0]


@pytest.fixture(scope="module")
def csv_dir(built):
    return built[1]


@pytest.fixture(scope="module")
def prep_output(built):
    return built[2]


def rows(graph, query):
    return list(graph.cypher(query))


def one(graph, query):
    result = rows(graph, query)
    assert result, f"query returned no rows:\n{query}"
    return result[0]


def table(csv_dir, name):
    with (csv_dir / name).open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


# --------------------------------------------------------------------------
# The finding: no association exists in the download
# --------------------------------------------------------------------------


def test_mimedb_writes_no_taxon_metabolite_edge_because_there_is_none(graph, prep_output):
    """**The headline assertion of this module, and it is a zero.**

    The two downloads are `SELECT * FROM microbes` and `SELECT * FROM
    metabolites`; the join between them is in neither, and the nearest thing to
    a relation in either is a `microbes.activity` column that says `Production
    (export)` **with no compound named anywhere on the row**. Deriving an edge
    from it would manufacture exactly the claim D5 asks for out of a field that
    does not make it. The fixture carries that row on purpose.

    A zero is only worth asserting if something could make it non-zero, and
    something could: this test fails the moment any relationship is declared
    for this source, which is the review gate on "MiMeDB finally has an edge
    list" being a deliberate change rather than an accident."""
    assert RELATIONSHIPS == {}
    for row in rows(
        graph, "MATCH ()-[r]->() RETURN DISTINCT r.primary_source AS source"
    ):
        assert row["source"] != SOURCE
    assert "PRODUCES edges from MiMeDB: 0" in prep_output


def test_the_organisms_are_read_reported_and_not_loaded(graph, prep_output):
    """The microbes table resolves almost perfectly — every row carries an NCBI
    taxid — and that is exactly the point: this source has the taxon side of
    D5's edge and nothing to attach it to. Reporting the number is what
    separates "MiMeDB does not close D5" from "MiMeDB has nothing"; loading it
    would put 2,174 unconnected `Taxon` nodes in the real graph."""
    assert f"microbes: {MICROBES} organisms, {MICROBES} with an NCBI taxid" in prep_output
    assert "promoted 1" in prep_output, "the strain-level row must promote to its species"
    # Not in cited_taxa.csv, so the taxonomy build keeps none of them for MiMeDB.
    assert not rows(
        graph,
        f"MATCH (t:Taxon)-[r]->() WHERE r.primary_source = '{SOURCE}' RETURN t",
    )


# --------------------------------------------------------------------------
# The selection rule
# --------------------------------------------------------------------------


def test_only_the_selected_slice_is_loaded(graph, prep_output):
    """44% of the real file is glycerophospholipids. A loader that kept
    everything would put a lipidomics table in a microbiome graph, and the
    count is the assertion rather than "it built"."""
    loaded = one(
        graph, f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' RETURN count(m) AS n"
    )["n"]
    assert loaded == LOADED
    assert f"skipped {NOT_SELECTED} that no rule selected" in prep_output
    assert not rows(graph, "MATCH (m:Metabolite {title: 'PC(16:0/18:1)'}) RETURN m")


def test_each_selection_rule_is_recorded_on_the_node_it_kept(graph):
    """A rule described only in a docstring cannot be audited and cannot be
    changed safely."""
    kept = {
        rule
        for r in rows(
            graph,
            f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' "
            "RETURN DISTINCT m.selection_rule AS rule",
        )
        for rule in r["rule"].split("|")
    }
    assert kept <= set(SELECTION_RULES)
    assert kept == {"observed", "origin-classified", "njc19-compound"}


def test_the_njc19_rule_selects_a_compound_njc19_needs_and_not_one_it_might(graph):
    """`Pectin` is in NJC19's fixture and no HMDB record holds it, so this
    record is what turns a minted stub into an identified compound. `Chitin` is
    the same *shape* of record and NJC19 never names it, so it is not loaded:
    the rule is "a compound NJC19 needs", not "a compound like the ones it
    needs"."""
    pectin = one(graph, "MATCH (m:Metabolite {title: 'Pectin'}) RETURN m.selection_rule AS r")
    assert pectin["r"] == "njc19-compound"
    assert not rows(graph, "MATCH (m:Metabolite {title: 'Chitin'}) RETURN m")


# --------------------------------------------------------------------------
# Identity: the three ways a compound is "already held", and the one that lies
# --------------------------------------------------------------------------


def test_a_legacy_five_digit_accession_still_finds_its_node(graph, csv_dir):
    """HMDB widened its accessions from five digits to seven in 2018 and
    MiMeDB's column holds both spellings. A literal string join misses every
    legacy id **silently**, which reads as "MiMeDB has no HMDB id for this
    compound" — and then mints a second node for it."""
    assert normalise_hmdb_id("HMDB00011") == "HMDB0000011"
    assert normalise_hmdb_id("HMDB0000011") == "HMDB0000011"
    assert normalise_hmdb_id("NULL") == ""
    assert normalise_hmdb_id("CHEBI:30772") == ""
    assert not rows(graph, "MATCH (m:Metabolite {title: 'Butyrate salt'}) RETURN m")
    reason = [r for r in table(csv_dir, "unresolved_mimedb.csv")
              if r["name"] == "Butyrate salt"]
    assert len(reason) == 1
    assert reason[0]["metabolite_id"] and "already holds" in reason[0]["reason"]


def test_a_compound_held_under_another_name_is_found_by_its_structure(graph, csv_dir):
    """`Ethanoic acid` and `Acetic acid` are one compound with two names, and
    only the InChIKey says so. Without the structural test this record becomes
    a second acetate node — and NJC19, which tries derived spellings in order,
    can then reach the new one while HMDB's producers stay on the old."""
    assert not rows(graph, "MATCH (m:Metabolite {title: 'Ethanoic acid'}) RETURN m")
    reason = [r for r in table(csv_dir, "unresolved_mimedb.csv")
              if r["name"] == "Ethanoic acid"]
    assert len(reason) == 1 and "already holds" in reason[0]["reason"]


def test_a_contested_hmdb_accession_is_not_a_join_key(graph, csv_dir):
    """149 accessions in the real file are claimed by two MiMeDB records each,
    almost all of them a D-/L- enantiomer pair. Joining on one folds two
    compounds into one node and attributes each one's annotations to the other,
    so both records keep their own identity and the ledger says why — the same
    rule `reconcile` applies to an ambiguous organism name."""
    ids = {
        r["title"]: r["id"]
        for r in rows(
            graph,
            "MATCH (m:Metabolite) WHERE m.title IN ['L-Tyrosine', 'D-Tyrosine'] "
            "RETURN m.title AS title, m.id AS id",
        )
    }
    assert set(ids) == {"L-Tyrosine", "D-Tyrosine"}
    assert ids["L-Tyrosine"] != ids["D-Tyrosine"]
    assert all(i.startswith("MIMEDB:") for i in ids.values())
    contested = [r for r in table(csv_dir, "unresolved_mimedb.csv")
                 if "is claimed by" in r["reason"]]
    assert len(contested) == CONTESTED_RECORDS
    assert all("HMDB0000158" in r["reason"] for r in contested)
    # And neither of them kept the accession, because it did not identify them.
    for row in rows(
        graph,
        "MATCH (m:Metabolite) WHERE m.title IN ['L-Tyrosine', 'D-Tyrosine'] "
        "RETURN m.hmdb_id AS hmdb_id",
    ):
        assert not row["hmdb_id"]


def test_an_already_held_compound_is_a_ledger_row_and_not_a_merge(graph, csv_dir, prep_output):
    """`Writer` keys `metabolite.csv` on `metabolite_id` and the first row per
    key wins, so a MiMeDB row written for a compound HMDB already has would
    have its properties silently discarded — an outcome that reads like a
    successful join in the row count and is not one. Ledgering it makes
    "MiMeDB added nothing here" a number."""
    assert f"already has a node: {ALREADY_HELD}" in prep_output
    ledger = table(csv_dir, "unresolved_mimedb.csv")
    assert len(ledger) == LEDGER_ROWS
    assert all(r["source"] == SOURCE for r in ledger)
    held = [r for r in ledger if "already holds" in r["reason"]]
    assert len(held) == ALREADY_HELD
    assert all(r["metabolite_id"] for r in held), "a ledger row names the node that won"


# --------------------------------------------------------------------------
# What the node carries, and what it deliberately does not
# --------------------------------------------------------------------------


def test_a_mimedb_node_carries_no_invented_detection_status(graph):
    """`status` is HMDB's four-value vocabulary and this file has no such
    column. Writing a plausible value into a column another source's evidence
    rule reads would be inventing evidence; `mimedb_origin` carries what this
    file does grade on."""
    for row in rows(
        graph,
        f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' "
        "RETURN m.status AS status, m.microbial_origin AS origin, "
        "m.mimedb_id AS mimedb_id, m.inchikey AS inchikey",
    ):
        assert not row["status"]
        assert row["origin"] is False
        assert row["mimedb_id"].startswith("MMDBc")
        assert row["inchikey"]


def test_the_null_string_never_reaches_the_graph(graph):
    """The MySQL dump writes an absent value as the four characters `NULL`.
    Read straight that is the *string* "NULL" in a CSV column, which kglite
    loads as a value and `ontology_audit()` counts as present — a filled
    field that says nothing."""
    row = one(
        graph,
        "MATCH (m:Metabolite {title: 'NULL-valued compound'}) "
        "RETURN m.cas AS cas, m.chemical_formula AS formula, m.hmdb_id AS hmdb_id",
    )
    assert not row["cas"] and not row["formula"] and not row["hmdb_id"]
    assert not rows(graph, "MATCH (m:Metabolite) WHERE m.cas = 'NULL' RETURN m")


def test_the_origin_axis_survives_onto_the_node(graph):
    """`metabolite_type` is the one thing the research document found MiMeDB
    grades on an evidence basis, and it is 97.4% empty in the real file — which
    is a fact about the source that only survives if the column is loaded."""
    origins = {
        r["origin"]
        for r in rows(
            graph,
            f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' AND m.mimedb_origin <> '' "
            "RETURN DISTINCT m.mimedb_origin AS origin",
        )
    }
    assert origins == {"Co-metabolite", "Primary"}


def test_the_prep_reports_what_it_did_not_load(prep_output):
    for phrase in ("selection rule:", "that no rule selected",
                   "not written because the compound already has a node:",
                   "so not used as a join key:", "mimedb_origin:",
                   "PRODUCES edges from MiMeDB: 0"):
        assert phrase in prep_output


def test_every_record_is_a_node_or_a_counted_reason(prep_output, csv_dir):
    """Input records = loaded + not selected + ledger rows. A silent drop
    cannot hide in the difference."""
    ledger = table(csv_dir, "unresolved_mimedb.csv")
    # The two contested records are ledgered *and* loaded — the ledger row is
    # about the accession they lost, not about the record being dropped.
    assert LOADED + NOT_SELECTED + ALREADY_HELD == RECORDS
    assert len(ledger) == ALREADY_HELD + CONTESTED_RECORDS


@pytest.mark.fixture
def test_the_fixture_keeps_the_real_dumps_columns():
    """A fixture with a trimmed header would hide a column-name typo in the
    loader: every field this prep reads is addressed by name."""
    with (MIMEDB_MINI / "mimedb_metabolites_v1.csv").open(encoding="utf-8") as fh:
        columns = next(csv.reader(fh))
    assert len(columns) == 42
    assert columns[:3] == ["id", "name", "mime_id"]
    assert {"hmdb_id", "detected", "quantified", "metabolite_type", "moldb_inchikey",
            "moldb_formula", "moldb_average_mass", "cas"} <= set(columns)

    with (MIMEDB_MINI / "mimedb_microbes_v1.csv").open(encoding="utf-8") as fh:
        columns = next(csv.reader(fh))
    assert len(columns) == 39
    assert {"ncbi_tax_id", "activity", "species", "strain"} <= set(columns)
    # And nothing in either header names the other table.
    assert not {c for c in columns if "metabolite" in c}
