"""HMDB: 578 production claims over 224 records, and how a naive load loses them.

The fixture (``tests/fixtures/hmdb_mini/``, generated by
``tests/fixtures/make_hmdb_mini.py``, which names every injected record) carries
one record per trap from ``docs/research/source-formats.md`` §2, and the loader
is measured against what each trap would silently do:

* a substring match on ``microb`` selects ``Antimicrobial agent`` — a drug that
  *kills* microbes — as a microbial metabolite;
* loading all 217,920 records puts a chemistry database in a microbiome graph,
  88.8% of it never observed in a sample;
* resolving HMDB's organism strings verbatim writes "a **kingdom** produces
  butyrate", because NCBI files ``Firmicutes`` as a synonym of ``Bacillati``;
* keeping only the deepest organism term loses the whole claim whenever the one
  species under a genus is misspelled, which HMDB's are;
* loading the disease layer creates one ``Disease`` node with 20,020 metabolite
  edges;
* reading ``<chebi_id/>`` straight writes the string ``"None"`` into the graph.

One of those expectations did not survive contact with the data, and the test
that records it is
:func:`test_the_ligature_typo_is_repaired_by_casefold_not_left_unresolved`.
"""

from __future__ import annotations

import csv
import json
import subprocess
import sys
from pathlib import Path

import pytest

from conftest import TAXDUMP_MINI

kglite = pytest.importorskip("kglite")

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parent / "fixtures"
HMDB_MINI = FIXTURES / "hmdb_mini" / "hmdb_metabolites.xml"
REACTOME_MINI = FIXTURES / "reactome_mini"
SCRIPTS = ROOT / "scripts"
PREPS_DIR = ROOT / "microbiomekg" / "preps"
PREP = PREPS_DIR / "prep_hmdb.py"


for _needed in (PREP, HMDB_MINI, REACTOME_MINI / "ChEBI2Reactome.txt"):
    if not _needed.exists():
        pytest.skip(f"{_needed} does not exist yet", allow_module_level=True)

from microbiomekg.ontology import EVIDENCE_LEVEL_VALUES  # noqa: E402
from microbiomekg.ontology.hmdb import (  # noqa: E402
    MICROBE_PATH,
    PRODUCTION_CONTRACT,
    PRODUCTION_RANK_CEILING,
    evidence_level,
)

SOURCE = "hmdb"

# --------------------------------------------------------------------------
# Golden values, derived from the fixture by hand and asserted exactly.
# --------------------------------------------------------------------------

RECORDS = 62  # metabolites in the fixture XML
SELECTED = 20  # Metabolite nodes: 21 records, two sharing one ChEBI
NOT_SELECTED = 41  # records no rule kept — the shape of the real file
PRODUCES_EDGES = 13
LEDGER_ROWS = 7  # 4 unresolved + 1 too broad + 1 duplicate + 1 ChEBI key
UNRESOLVED_TAXA = 4
DISEASE_ROWS = 3  # counted, never loaded
MICROBIAL_ORIGIN = 13  # 12 naming an organism + 1 naming none
PRODUCING_TAXA = {
    853,
    841,
    239935,
    816,
    562,
    1678,
    29523,
    239934,
    1512,
    1578,
    818,
    572511,
    1386,
}

#: The disease name that carries 72% of HMDB's disease layer.
MEGA_DISEASE = "3-methylglutaconic aciduria type II, X-linked"


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    """HMDB and Reactome through their real preps, then the real blueprint."""
    work = tmp_path_factory.mktemp("hmdb")
    csv_dir = work / "csv"
    csv_dir.mkdir()

    def run(script, *args):
        proc = subprocess.run(
            [sys.executable, str(script), *args],
            capture_output=True,
            text=True,
            cwd=ROOT,
        )
        assert proc.returncode == 0, (
            f"{script.name} failed:\n{proc.stdout}\n{proc.stderr}"
        )
        return proc

    prep = run(
        PREP,
        "--xml",
        str(HMDB_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--reactome",
        str(REACTOME_MINI),
        "--out",
        str(csv_dir),
    )
    # Reactome too, because the metabolite selection rule reads its ChEBI set
    # and D13's path needs a Pathway on the far end of IN_PATHWAY.
    run(
        PREPS_DIR / "prep_reactome.py",
        "--reactome",
        str(REACTOME_MINI),
        "--out",
        str(csv_dir),
    )
    run(
        PREPS_DIR / "prep_taxonomy.py",
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
        "--scope",
        "cited",
        "--cited-from",
        str(csv_dir / "cited_taxa.csv"),
    )

    from microbiomekg.fragments import compose

    from microbiomekg.ontology import ontology_for, write_json

    sources = [SOURCE, "reactome"]
    blueprint = compose(ROOT / "microbiomekg" / "blueprints", sources)
    settings = blueprint.setdefault("settings", {})
    settings["root"] = str(csv_dir)
    for key in ("output", "output_path", "output_file"):
        settings.pop(key, None)
    write_json(csv_dir / "ontology.json", ontology_for(sources))
    blueprint["ontology"] = str(csv_dir / "ontology.json")
    local = csv_dir / "blueprint.test.json"
    local.write_text(json.dumps(blueprint))

    return kglite.from_blueprint(local, verbose=False, save=False), csv_dir, prep.stdout


@pytest.fixture(scope="module")
def graph(built):
    return built[0]


@pytest.fixture(scope="module")
def csv_dir(built):
    return built[1]


@pytest.fixture(scope="module")
def prep_output(built):
    return built[2]


def rows(graph, query):
    return list(graph.cypher(query))


def one(graph, query):
    result = rows(graph, query)
    assert result, f"query returned no rows:\n{query}"
    return result[0]


def table(csv_dir, name):
    with (csv_dir / name).open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


# --------------------------------------------------------------------------
# The selection rule — what is loaded, and what a substring match would load
# --------------------------------------------------------------------------


def test_the_substring_trap_does_not_select_an_antimicrobial_drug(graph):
    """`grep microb|bacter|fung` over HMDB's ontology returns 519 metabolites,
    and 233 of them are `Role/Industrial application/Household products/
    Antimicrobial agent` — drugs that kill microbes, the exact opposite of the
    relation being loaded. Origin is matched as a **path prefix** for that
    reason, and the fixture's triclosan record proves the difference."""
    assert not rows(graph, "MATCH (m:Metabolite {title: 'Triclosan'}) RETURN m")
    assert not rows(
        graph,
        "MATCH ()-[r:PRODUCES]->(m:Metabolite) WHERE m.title = 'Triclosan' RETURN r",
    )


def test_only_the_selected_slice_is_loaded(graph, prep_output):
    """The whole file is not the point: 88.8% of HMDB is predicted or expected,
    and a loader that kept everything would put a chemistry database in a
    microbiome graph. The count is the assertion, not "it built"."""
    assert one(graph, "MATCH (m:Metabolite) RETURN count(m) AS n")["n"] == SELECTED
    assert f"skipped {NOT_SELECTED} that no rule selected" in prep_output


def test_each_selection_rule_is_recorded_on_the_node_it_kept(graph):
    """`selection_rule` makes the rule countable in the graph. A rule described
    only in a docstring cannot be audited, and cannot be changed safely."""
    # `selection_rule` is a list property, so the rules come apart in Cypher
    # rather than in a `.split("|")` here.
    rules = {
        r["rule"]
        for r in rows(
            graph,
            "MATCH (m:Metabolite) UNWIND m.selection_rule AS rule "
            "RETURN rule, count(m) AS n",
        )
    }
    assert rules == {"microbial-origin", "feces", "reactome-chebi"}
    # A metabolite kept by the Reactome bridge alone: predicted, never in
    # feces, no microbial origin — and still needed, because it is the far end
    # of an IN_PATHWAY edge.
    lone = one(
        graph,
        "MATCH (m:Metabolite {id: 'CHEBI:28834'}) RETURN m.selection_rule AS rule, "
        "m.status AS status, m.microbial_origin AS microbial, m.biospecimens AS bio",
    )
    assert lone == {
        "rule": ["reactome-chebi"],
        "status": "predicted",
        "microbial": False,
        "bio": ["Blood"],
    }


def test_a_feces_metabolite_is_kept_without_microbial_origin(graph):
    """The gut slice is the second-largest biospecimen class in HMDB and is
    most of what this source contributes; it is not the same set as the 224."""
    result = one(
        graph,
        "MATCH (m:Metabolite {id: 'CHEBI:9169'}) RETURN m.selection_rule AS rule, "
        "m.microbial_origin AS microbial, m.biospecimens AS bio",
    )
    assert result == {"rule": ["feces"], "microbial": False, "bio": ["Feces"]}


# --------------------------------------------------------------------------
# The organism strings — where the wrong answers live
# --------------------------------------------------------------------------


def test_a_rank_broader_than_a_family_reaches_the_ledger_not_an_edge(graph, csv_dir):
    """`Firmicutes` is why this is a correctness rule and not a tidiness one.
    NCBI files that exact string as a **synonym of 1783272 `Bacillati`, a
    kingdom** (the 2024 nomenclature change), while the phylum a reader means
    carries `firmicutes` only as a blast name, which NAME_CLASSES excludes. So
    a naive load does not write a vague edge — it writes a false one. The
    fixture's mini dump has no `Firmicutes` at all, so its phylum case is
    `Bacillota` (1239); both land in the ledger, by the two different routes."""
    ledger = {
        r["reported_name"]: r for r in table(csv_dir, "unresolved_production.csv")
    }
    broad = ledger["Bacillota"]
    assert broad["resolved_tax_id"] == "1239"
    assert broad["resolved_rank"] == "phylum"
    assert PRODUCTION_RANK_CEILING in broad["reason"]
    assert not rows(graph, "MATCH (t:Taxon {id: 1239})-[r:PRODUCES]->() RETURN r")
    # And the resolution is kept, so the decision is reversible rather than a
    # drop: a later phase can promote these without re-reading 6.5 GB.
    assert broad["microbe_path"].startswith(MICROBE_PATH)


def test_an_unresolvable_organism_is_a_tombstone_and_a_ledger_row(graph, csv_dir):
    """G2: nothing is dropped. A community (`Human gut microbiota`), a Gram
    stain and a string absent from names.dmp are all real HMDB terms and none
    of them is an organism NCBI has an id for."""
    tombstones = {
        r["raw_name"]: r
        for r in table(csv_dir, "unresolved_taxa.csv")
        if r["source"] == SOURCE
    }
    assert set(tombstones) == {
        "Firmicutes",
        "Human gut microbiota",
        "Gram-negative bacteria",
        "Akkermansia muciniphilia",
    }
    assert len(tombstones) == UNRESOLVED_TAXA
    for row in tombstones.values():
        assert row["status"] == "unresolved"
        assert row["n_signatures"] == "1"
    assert (
        one(
            graph,
            f"MATCH (u:UnresolvedTaxon) WHERE u.source = '{SOURCE}' RETURN count(u) AS n",
        )["n"]
        == UNRESOLVED_TAXA
    )


def test_the_ligature_typo_is_repaired_by_casefold_not_left_unresolved(graph, csv_dir):
    """**The one expectation the data refused.** `source-formats.md` §2 lists
    the U+FB01 ligature `Biﬁdobacterium` among the strings "expected to land in
    `UnresolvedTaxon`", and D5 repeats it. It does not: Python's
    ``str.casefold`` applies *full* case folding, which decomposes U+FB01 to
    ``fi``, so the reconciler's casefolded name index matches it to
    `Bifidobacterium` (1678) exactly as if it were spelled correctly.

    That is the right answer and a better one than the ledger — but it creates
    a failure the plan did not anticipate, because the same record carries the
    correctly spelled sibling too, and two terms resolving to one taxon are one
    annotation spelled twice, not two observations. The loader keeps one edge
    and files the loser with its reason."""
    assert "Biﬁdobacterium".casefold() == "bifidobacterium"
    edges = rows(
        graph,
        "MATCH (t:Taxon {id: 1678})-[r:PRODUCES]->(m:Metabolite {id: 'CHEBI:17272'}) "
        "RETURN r.reported_name AS reported",
    )
    assert len(edges) == 1, "the ligature and its sibling became two edges"
    assert edges[0]["reported"] == "Bifidobacterium", (
        "the tie-break must prefer the term that *is* the NCBI name it matched, "
        "not whichever the XML listed first"
    )
    dropped = [
        r
        for r in table(csv_dir, "unresolved_production.csv")
        if r["reported_name"] == "Biﬁdobacterium"
    ]
    assert len(dropped) == 1
    assert dropped[0]["resolved_tax_id"] == "1678"
    assert "already claimed" in dropped[0]["reason"]
    assert not any(
        r["raw_name"] == "Biﬁdobacterium" for r in table(csv_dir, "unresolved_taxa.csv")
    )


def test_a_species_term_suppresses_its_own_genus(graph):
    """A metabolite listing `Microbe/Faecalibacterium` and
    `Microbe/Faecalibacterium/Faecalibacterium prausnitzii` makes one claim at
    two levels of detail. Emitting both doubles the evidence for it and puts a
    genus row beside its own species row in D5's answer."""
    got = {
        (r["tax_id"], r["reported"])
        for r in rows(
            graph,
            "MATCH (t:Taxon)-[r:PRODUCES]->(m:Metabolite {id: 'CHEBI:17968'}) "
            "RETURN t.id AS tax_id, r.reported_name AS reported",
        )
    }
    assert got == {(853, "Faecalibacterium prausnitzii"), (841, "Roseburia")}


def test_a_misspelled_species_does_not_take_its_genus_down_with_it(graph, csv_dir):
    """The failure a plain "keep the leaf" rule produces. HMDB's species level
    carries `Citrobacter frundii`, `Akkermansia muciniphilia`,
    `Clostridium botulinium`; where such a typo is a genus's only child, the
    leaf rule drops a genus the source did name, silently. The genus is
    suppressed only when the species actually resolved."""
    result = one(
        graph,
        "MATCH (t:Taxon)-[r:PRODUCES]->(m:Metabolite {id: 'CHEBI:18089'}) "
        "RETURN t.id AS tax_id, r.reported_name AS reported, "
        "r.reported_rank AS reported_rank",
    )
    assert result["tax_id"] == 239934, "the genus edge was lost with its typo'd species"
    assert result["reported"] == "Akkermansia"
    assert result["reported_rank"] == "genus-level term"
    assert any(
        r["reported_name"] == "Akkermansia muciniphilia" and "unresolved" in r["reason"]
        for r in table(csv_dir, "unresolved_production.csv")
    )


def test_a_cross_kingdom_homonym_is_settled_by_the_microbial_context(graph):
    """`Bacillus` is a bacterial genus (1386) **and** a genus of stick insects
    (55087), and it is HMDB's single most common organism term — 13 metabolites
    in the real file, plus `Proteus` (a bacterium and an amphibian), `Serratia`,
    `Rhodococcus`, `Edwardsiella` and `Paracoccus`. `reconcile` answers
    `ambiguous` and returns the candidates rather than guessing, which is right:
    C2's warning is that `first-wins` invents facts. The context the *caller*
    has is that the term came from `Disposition/Source/Biological/Microbe`, so a
    stick insect is not merely less likely — it is wrong.

    Exactly one candidate under a microbial root, never the first: C3's point is
    that a kingdom heuristic cannot separate two bacteria, so
    `Lactobacillus plantarum` (1590 and 1385856) stays ambiguous."""
    result = one(
        graph,
        "MATCH (t:Taxon)-[r:PRODUCES]->(m:Metabolite {id: 'HMDB:HMDB0000032'}) "
        "RETURN t.id AS tax_id, r.resolution_status AS status, "
        "r.reported_name AS reported",
    )
    assert result == {
        "tax_id": 1386,
        "status": "kingdom-disambiguated",
        "reported": "Bacillus",
    }
    assert not rows(graph, "MATCH (t:Taxon {id: 55087})-[r:PRODUCES]->() RETURN r")


def test_a_placeholder_organism_resolves_and_is_flagged_not_dropped(graph):
    """G9: `Bacteroides sp.` is a real NCBI node (29523) meaning "some species
    of Bacteroides". It resolves verbatim and the *Taxon* carries the flag; a
    ranked query excludes it by that boolean, never by a name substring."""
    result = one(
        graph,
        "MATCH (t:Taxon)-[r:PRODUCES]->(m:Metabolite {id: 'CHEBI:16411'}) "
        "RETURN t.id AS tax_id, t.placeholder AS placeholder, "
        "r.reported_name AS reported",
    )
    assert result == {
        "tax_id": 29523,
        "placeholder": True,
        "reported": "Bacteroides sp.",
    }


def test_the_source_rank_claim_and_ncbis_rank_are_kept_apart(graph):
    """G5. `reported_rank` is HMDB's own level — and the point is that it is
    *not* a rank: its "genus" level holds genera, phyla, families, a class and
    two Gram stains. `original_rank` is what NCBI says. Folding them into one
    column makes the mixing invisible and the ceiling unauditable."""
    mixed = rows(
        graph,
        "MATCH ()-[r:PRODUCES]->() WHERE r.reported_rank = 'genus-level term' "
        "AND r.original_rank <> 'genus' "
        "RETURN r.reported_name AS reported, r.original_rank AS ncbi_rank",
    )
    assert {(r["reported"], r["ncbi_rank"]) for r in mixed} == {
        ("Bacteroides sp.", "species"),
        ("Clostridium symbiosum", "species"),
    }


# --------------------------------------------------------------------------
# The evidence a PRODUCES edge carries
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "status, expected",
    [
        ("quantified", "in-vitro"),
        ("detected", "in-vitro"),
        ("expected", "computational-predicted"),
        ("predicted", "computational-predicted"),
        ("", "computational-predicted"),
        (None, "computational-predicted"),
        ("QUANTIFIED", "in-vitro"),
    ],
)
def test_evidence_level_follows_the_metabolites_status(status, expected):
    """Part B: "HMDB microbial-origin edges whose metabolite is
    detected/quantified" are in-vitro. An unrecognised spelling takes the
    conservative branch, never a plausible-looking `unknown`."""
    assert evidence_level(status) == expected


def test_an_expected_metabolite_produces_a_predicted_edge(graph):
    result = one(
        graph,
        "MATCH ()-[r:PRODUCES]->(m:Metabolite {id: 'CHEBI:15724'}) "
        "RETURN r.evidence_level AS level, r.hmdb_status AS status",
    )
    assert result == {"level": "computational-predicted", "status": "expected"}


def test_every_level_written_is_one_of_the_twelve(graph):
    used = {
        r["level"]
        for r in rows(
            graph,
            "MATCH ()-[r:PRODUCES]->() RETURN DISTINCT r.evidence_level AS level",
        )
    }
    assert used <= set(EVIDENCE_LEVEL_VALUES)
    assert used == {"in-vitro", "computational-predicted"}


def test_the_claim_is_a_curators_whatever_the_metabolites_status(graph):
    """`knowledge_level` and `evidence_level` answer different questions and
    Part B keeps them in different columns. HMDB's microbial-origin annotation
    is a person's entry in a hand-built tree on all 224 records; what the status
    changes is whether anyone has *measured* the compound. Collapsing them would
    make `prediction` mean "nobody has run the assay yet"."""
    result = rows(
        graph,
        "MATCH ()-[r:PRODUCES]->() RETURN DISTINCT r.knowledge_level AS kl, "
        "r.agent_type AS agent, r.source_licence AS licence, "
        "r.primary_source AS source, r.source_relation AS relation",
    )
    assert result == [
        {
            "kl": "knowledge_assertion",
            "agent": "manual_agent",
            "licence": "HMDB-noncommercial",
            "source": SOURCE,
            "relation": MICROBE_PATH,
        }
    ]


def test_the_publication_cap_is_visible_rather_than_silent(graph):
    """A truncated list that does not say it was truncated changes the answer
    to "how many papers support this" without anything looking wrong."""
    result = one(
        graph,
        "MATCH ()-[r:PRODUCES]->(m:Metabolite {id: 'CHEBI:16991'}) "
        "RETURN r.publications AS refs, r.n_publications AS n",
    )
    assert result["n"] == 30
    assert len(result["refs"]) == 25
    assert all(ref.startswith("PMID:") for ref in result["refs"])


def test_a_repeated_pmid_is_one_publication(graph):
    """The butyrate record cites one PMID twice; a citation list that counts it
    twice overstates the support."""
    result = one(
        graph,
        "MATCH ()-[r:PRODUCES]->(m:Metabolite {id: 'CHEBI:17968'}) "
        "RETURN r.publications AS refs, r.n_publications AS n LIMIT 1",
    )
    assert result["n"] == 2
    assert result["refs"] == ["PMID:10362454", "PMID:7762816"]


# --------------------------------------------------------------------------
# Metabolite identity and the scalar columns
# --------------------------------------------------------------------------


def test_a_metabolite_with_no_chebi_is_keyed_on_its_hmdb_accession(graph):
    result = one(
        graph,
        "MATCH (m:Metabolite {id: 'HMDB:HMDB0000028'}) "
        "RETURN m.hmdb_id AS hmdb, m.chebi_id AS chebi, m.title AS name",
    )
    assert result["hmdb"] == "HMDB0000028"
    assert result["chebi"] is None
    assert result["name"] == "Unmapped microbial metabolite"


def test_two_records_sharing_a_chebi_id_are_one_node_and_the_merge_is_reported(
    graph, csv_dir
):
    """HMDB carries 13,701 chebi_id values over 13,562 distinct ids, so a
    handful of records are two HMDB entries for one ChEBI compound. Keying on
    ChEBI merges them, which is right — ChEBI is the identity — but the second
    record's scalar properties are lost, and a silent loss is the bug."""
    node = one(
        graph,
        "MATCH (m:Metabolite {id: 'CHEBI:78320'}) RETURN count(m) AS n, "
        "m.hmdb_id AS hmdb, m.title AS name",
    )
    assert node["n"] == 1 and node["hmdb"] == "HMDB0000022"
    merged = [
        r
        for r in table(csv_dir, "unresolved_production.csv")
        if r["accession"] == "HMDB0000023"
    ]
    assert len(merged) == 1 and "already keyed by HMDB0000022" in merged[0]["reason"]


def test_an_empty_element_is_absent_rather_than_the_string_None(graph):
    """`<chebi_id/>` has `.text is None`. Written through, it becomes the string
    `"None"` in the CSV — which kglite loads as a value and the audit counts as
    present."""
    result = one(
        graph,
        "MATCH (m:Metabolite {id: 'HMDB:HMDB0000029'}) "
        "RETURN m.chebi_id AS chebi, m.kegg_id AS kegg, m.pubchem_cid AS pubchem",
    )
    assert result == {"chebi": None, "kegg": None, "pubchem": None}
    assert not rows(graph, "MATCH (m:Metabolite) WHERE m.kegg_id = 'None' RETURN m")


def test_the_retired_accession_redirect_table_is_loaded(graph):
    """80,986 retired HMDB ids across the file. Without them a citation of
    `HMDB00001` finds nothing at all."""
    result = one(
        graph,
        "MATCH (m:Metabolite {id: 'CHEBI:17968'}) "
        "RETURN m.secondary_accessions AS secondary",
    )
    assert result["secondary"] == ["HMDB00011", "HMDB0004935"]


def test_microbial_origin_is_a_boolean_not_a_string(graph):
    """A string `"false"` is truthy in every language a consumer will use."""
    result = one(
        graph,
        "MATCH (m:Metabolite) RETURN count(m) AS total, "
        "sum(CASE WHEN m.microbial_origin THEN 1 ELSE 0 END) AS microbial",
    )
    assert result["total"] == SELECTED
    assert result["microbial"] == MICROBIAL_ORIGIN


def test_a_microbial_metabolite_can_name_no_organism_at_all(graph, prep_output):
    """**"224 microbial metabolites" is not "224 production edges".** 67 of
    HMDB's 224 records carry `Disposition/Source/Biological/Microbe` with
    nothing beneath it — a real origin claim with no organism to point an edge
    at. Reading the selection rule and the edge source as the same question
    both overstates the edges and, worse, drops those records from the graph
    entirely: they are microbial metabolites and the flag says so."""
    result = one(
        graph,
        "MATCH (m:Metabolite {id: 'HMDB:HMDB0000031'}) "
        "RETURN m.microbial_origin AS microbial, m.selection_rule AS rule",
    )
    assert result == {"microbial": True, "rule": ["microbial-origin"]}
    assert not rows(
        graph, "MATCH ()-[r:PRODUCES]->(m:Metabolite {id: 'HMDB:HMDB0000031'}) RETURN r"
    )
    assert "1 microbial-origin metabolites name no organism at all" in prep_output


# --------------------------------------------------------------------------
# The disease layer, which is deliberately absent
# --------------------------------------------------------------------------


def test_the_disease_layer_is_counted_and_not_loaded(graph, prep_output):
    """20,020 of HMDB's 27,670 disease rows carry one name — 72% of the layer,
    where the next name down has 831. Loading it naively produces a single
    Disease node with 20,020 metabolite edges that dominates every path query.
    The rows are reported, so the decision is visible in the build log."""
    assert not rows(graph, f"MATCH (d:Disease {{title: '{MEGA_DISEASE}'}}) RETURN d")
    assert not rows(graph, "MATCH (:Metabolite)-->(:Disease) RETURN 1 LIMIT 1")
    assert f"disease layer NOT loaded: {DISEASE_ROWS} rows" in prep_output


# --------------------------------------------------------------------------
# C18 accounting and the audit
# --------------------------------------------------------------------------


def test_every_organism_term_is_an_edge_or_a_counted_reason(
    graph, csv_dir, prep_output
):
    """Input terms = edges + ledger rows + explicitly reported suppressions.
    A silent drop cannot hide in the difference."""
    edges = one(graph, "MATCH ()-[r:PRODUCES]->() RETURN count(r) AS n")["n"]
    assert edges == PRODUCES_EDGES
    ledger = table(csv_dir, "unresolved_production.csv")
    assert len(ledger) == LEDGER_ROWS
    organism_rows = [r for r in ledger if r["reported_name"]]
    covered = 4  # genus terms whose own species became the edge
    assert edges + len(organism_rows) + covered == 23, (
        "23 organism terms in the fixture"
    )
    assert "23 organism terms -> 13 PRODUCES edges" in prep_output


def test_the_prep_reports_what_it_did_not_load(prep_output):
    for phrase in (
        "selection rule:",
        "not loaded:",
        "suppressed as duplicate detail:",
        "disease layer NOT loaded:",
        "have never been observed in a sample",
    ):
        assert phrase in prep_output


def test_the_production_contract_is_a_rule_that_can_fail(graph):
    """Unlike the association contract, every field here is written by this
    loader rather than read from upstream — so the rule *should* sit at zero,
    and a rule at zero for that reason is only worth having if it could move."""
    audit = {
        r["rule"]: r
        for r in rows(
            graph,
            "CALL ontology_audit() YIELD rule, violations, total RETURN rule, "
            "violations, total",
        )
    }
    rule = audit["PRODUCES.required_properties"]
    assert rule["total"] == PRODUCES_EDGES
    assert rule["violations"] == 0
    # And the contract is the applicable subset, not the association one: a
    # production claim has no direction, no assay and no cohort.
    assert "direction" not in PRODUCTION_CONTRACT
    assert "group_0_size" not in PRODUCTION_CONTRACT
    assert "evidence_level" in PRODUCTION_CONTRACT


def test_every_hmdb_produces_edge_still_carries_its_status(graph):
    """`hmdb_status` left `PRODUCTION_CONTRACT` when NJC19 became the second
    author of the `PRODUCES` table — a required property only one of two
    sources can write turns the other's every edge into a violation of a rule
    meant to read zero. The guarantee did not go anywhere, it moved here, which
    is where a source-specific field's guarantee belongs: the contract is what
    both authors owe, and this is what *this* author owes."""
    assert "hmdb_status" not in PRODUCTION_CONTRACT
    statuses = [
        r["status"]
        for r in rows(
            graph,
            "MATCH ()-[r:PRODUCES]->() WHERE r.primary_source = 'hmdb' "
            "RETURN r.hmdb_status AS status",
        )
    ]
    assert len(statuses) == PRODUCES_EDGES
    assert all(statuses), "an HMDB production edge with no detection status"
    assert set(statuses) <= {"expected", "predicted", "detected", "quantified"}


def test_no_rule_this_source_declares_audits_nothing(graph):
    """A rule with a zero denominator is a gate that cannot fail.

    Scoped to the relationships **these two sources add**, because the spine is
    always composed: this fixture loads no association source, so
    ``ASSOCIATED_WITH``'s rules sit at ``0 / 0`` here and would in any
    single-source build. That is a property of the fixture, not of the loader —
    ``scripts/build.py`` composes a partial ontology exactly so it is not a
    property of a real one."""
    totals = {
        r["rule"]: r["total"]
        for r in rows(
            graph, "CALL ontology_audit() YIELD rule, total RETURN rule, total"
        )
    }
    mine = {
        rule: n
        for rule, n in totals.items()
        if rule.split(".")[0] in ("PRODUCES", "IN_PATHWAY", "PART_OF_PATHWAY")
    }
    assert mine, "the audit reports no rule for this source's relationships at all"
    for rule, n in mine.items():
        assert n > 0, f"{rule} audits nothing"


def test_the_producing_taxa_are_all_cited_and_loaded(graph, csv_dir):
    """`cited_taxa.csv` drives which taxa the taxonomy build keeps; a source
    that did not contribute to it would have its edges point at nothing."""
    got = {
        r["tax_id"]
        for r in rows(
            graph, "MATCH (t:Taxon)-[:PRODUCES]->() RETURN DISTINCT t.id AS tax_id"
        )
    }
    assert got == PRODUCING_TAXA
    cited = {int(r["tax_id"]) for r in table(csv_dir, "cited_taxa.csv")}
    assert PRODUCING_TAXA <= cited
