"""Zimmermann 2019: the bacterium changes the drug, and the 17,479 pairs where
it does not.

The fixture (``tests/fixtures/zimmermann2019_mini/``, generated by
``tests/fixtures/make_zimmermann2019_mini.py``, which names every row and its
trap) is loaded through the real prep and the real blueprint alongside ChEMBL's
**and Maier's**, because the most consequential thing to assert here is a join
across all three:

* a compound the screen names must reach the ``Drug`` node ChEMBL already has,
  or the one *the other screen* minted, before it mints one of its own — a
  second node for one compound would make D8's own question ("does drug D
  inhibit gut bacteria, **or get metabolised by them**") unanswerable for it;
* the four abiotic ``Control pH`` columns must become no edges, because they
  read exactly like strains and produce apparent hits;
* a measured non-hit must not be reachable by a query for metabolism, and a
  pair with no number must be neither.

And the direction, which is the whole reason this source exists as its own
relationship: ``Taxon -> Drug``, never the reverse, so
``MATCH (d:Drug)-[]->(t:Taxon)`` stays the growth screen alone.
"""

from __future__ import annotations

import csv
import json
import subprocess
import sys
from pathlib import Path

import pytest

from prep_support import run_prep

from conftest import TAXDUMP_MINI

kglite = pytest.importorskip("kglite")

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parent / "fixtures"
ZIMMERMANN_MINI = FIXTURES / "zimmermann2019_mini"
MAIER_MINI = FIXTURES / "maier2018_mini"
CHEMBL_MINI = FIXTURES / "chembl_mini"
SCRIPTS = ROOT / "scripts"
PREPS_DIR = ROOT / "microbiomekg" / "preps"
PREP = PREPS_DIR / "prep_zimmermann2019.py"
WORKBOOK = "41586_2019_1291_MOESM1_ESM.xlsx"


for _needed in (
    PREP,
    ZIMMERMANN_MINI / WORKBOOK,
    MAIER_MINI / "NIHMS76168-supplement-Supplementary_table_3.xlsx",
    CHEMBL_MINI / "mechanism.jsonl",
):
    if not _needed.exists():
        pytest.skip(f"{_needed} does not exist yet", allow_module_level=True)

from microbiomekg.ontology import EVIDENCE_LEVEL_VALUES  # noqa: E402
from microbiomekg.ontology.zimmermann2019 import (  # noqa: E402
    AMBIGUOUS_STRAINS,
    COLUMN_OVERRIDES,
    EVIDENCE_LEVEL,
    FDR_THRESHOLD,
    METABOLISM_CONTRACT,
    PUBLICATION,
    RELATION_METABOLISES,
    RELATION_NO_METABOLISM,
    SPECIES_OVERRIDES,
    drug_variants,
    is_control_column,
    join_key,
    patric_tax_id,
    relation_for,
)

SOURCE = "zimmermann2019"

# --------------------------------------------------------------------------
# Golden values, derived from the fixture by hand and asserted exactly.
# --------------------------------------------------------------------------

DRUGS = 6
COLUMNS = 10  # nine strain columns and one abiotic control
CELLS = DRUGS * COLUMNS
#: What the prep must reproduce before it writes anything: six drugs, nine
#: strain columns, five of the six metabolised by at least one of them. The
#: real run's triple is the paper's 271, 76, 176.
PUBLISHED_MATRIX = "6,9,5"

EDGES = 47
METABOLISES = 7
NO_METABOLISM = 40
NOT_MEASURED = 1  # the one cell written blank
CONTROL_CELLS = 6  # the whole control column
UNUSABLE_CELLS = 6  # the column whose organism reaches no taxon
LEDGER_ROWS = 5
UNRESOLVED_TAXA = 1
TAXA = 6  # ten columns collapse: two B. fragilis, two E. coli
MINTED_DRUGS = 1
GENE_PAIRS = 3  # one on a hit edge, two on a measured non-hit

B_THETA = 818
B_FRAGILIS = 817
E_COLI = 562
B_LONGUM = 216816
L_REUTERI = 1598
F_PRAUSNITZII = 853

VANCOMYCIN = "CHEMBL:CHEMBL262777"
ACETAMINOPHEN = "CHEMBL:CHEMBL112"
AMPICILLIN = "CHEMBL:CHEMBL174"
METFORMIN = "CHEMBL:CHEMBL1431"
FICTITINE = "PRESTWICK:Prestw-9999"
INVENTOL = "ZIMMERMANN2019:INVENTOL-MESYLATE"

E_COLI_GENE_COLUMN = "Escherichia coli O157:H7"
E_COLI_OTHER_COLUMN = "Escherichia coli  K-12"


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    """ChEMBL, Maier and Zimmermann through their real preps, then the real
    blueprint. The order is the build's own: this prep declares
    ``DEPENDS_ON = ["chembl", "maier2018"]`` because its join routes read the
    ``drug.csv`` both of them write into."""
    work = tmp_path_factory.mktemp("zimmermann2019")
    csv_dir = work / "csv"
    csv_dir.mkdir()

    def run(script, *args):
        return run_prep(script, *args)

    run(
        PREPS_DIR / "prep_chembl.py",
        "--chembl",
        str(CHEMBL_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
    )
    run(
        PREPS_DIR / "prep_maier2018.py",
        "--tables",
        str(MAIER_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
    )
    prep = run(
        PREP,
        "--tables",
        str(ZIMMERMANN_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
        "--published-matrix",
        PUBLISHED_MATRIX,
    )
    run(
        PREPS_DIR / "prep_taxonomy.py",
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
        "--scope",
        "cited",
        "--cited-from",
        str(csv_dir / "cited_taxa.csv"),
    )

    from microbiomekg.fragments import compose

    from microbiomekg.ontology import ontology_for, write_json

    sources = [SOURCE, "chembl", "maier2018"]
    blueprint = compose(ROOT / "microbiomekg" / "blueprints", sources)
    settings = blueprint.setdefault("settings", {})
    settings["root"] = str(csv_dir)
    for key in ("output", "output_path", "output_file"):
        settings.pop(key, None)
    write_json(csv_dir / "ontology.json", ontology_for(sources))
    blueprint["ontology"] = str(csv_dir / "ontology.json")
    local = csv_dir / "blueprint.test.json"
    local.write_text(json.dumps(blueprint))

    return kglite.from_blueprint(local, verbose=False, save=False), csv_dir, prep.stdout


@pytest.fixture(scope="module")
def graph(built):
    return built[0]


@pytest.fixture(scope="module")
def csv_dir(built):
    return built[1]


@pytest.fixture(scope="module")
def prep_output(built):
    return built[2]


def rows(graph, query):
    return list(graph.cypher(query))


def one(graph, query):
    result = rows(graph, query)
    assert result, f"query returned no rows:\n{query}"
    return result[0]


def table(csv_dir, name):
    with (csv_dir / name).open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def ledger(csv_dir, kind):
    return [r for r in table(csv_dir, f"unresolved_{SOURCE}.csv") if r["kind"] == kind]


# --------------------------------------------------------------------------
# The parsing vocabulary, as unit tests: these run without a graph
# --------------------------------------------------------------------------


def test_the_call_rule_needs_both_halves_and_both_boundaries_are_inclusive():
    """`relation_for` is where the whole source's sign lives, and the sheet
    publishes only half of it: the per-drug depletion threshold is a column,
    the significance cutoff and the comparison are not. Fourteen cells of the
    real screen sit at exactly `p = 0.05` and one at exactly the threshold, so
    writing either boundary the other way moves the answer off the paper's own
    176."""
    assert relation_for(30.0, 20.0, 0.01) == RELATION_METABOLISES
    # Depleted enough, but not significantly.
    assert relation_for(30.0, 20.0, 0.2) == RELATION_NO_METABOLISM
    # Significant, but below the drug's own threshold — the flat 20% floor is
    # not the rule, and using it makes 190 drugs metabolised instead of 176.
    assert relation_for(24.0, 25.0, 0.001) == RELATION_NO_METABOLISM
    # Both boundaries, inclusive.
    assert relation_for(20.0, 20.0, FDR_THRESHOLD) == RELATION_METABOLISES
    # And a missing number is neither, never a non-hit.
    assert relation_for(None, 20.0, 0.01) is None
    assert relation_for(30.0, None, 0.01) is None
    assert relation_for(30.0, 20.0, None) is None


def test_a_control_column_is_recognised_by_its_label_and_nothing_else():
    """The four `Control pH` columns sit *between* strain columns and carry the
    same five sub-columns, so nothing structural separates them. Under the hit
    rule they produce 38 apparent hits between them — abiotic degradation read as
    microbial metabolism — and excluding them is what makes the paper's own 76
    strains reproduce from a sheet with 80 measured columns."""
    assert is_control_column("Control pH 7 ")
    assert is_control_column("Control pH 4")
    assert not is_control_column("Bacteroides caccae ATCC43185")
    assert not is_control_column("")


def test_two_spellings_of_one_label_meet_on_alphanumerics():
    """The two sheets punctuate a strain designation differently in almost every
    row, and the gene sheet spells a drug in title case where the screen shouts
    it. The join key is what they agree on; the verbatim strings survive on the
    edge."""
    assert join_key("Alistipes indistinctus DSM 22520") == join_key(
        "Alistipes indistinctus DSM22520"
    )
    assert join_key("Bacteroides fragilis 3397 (T10)") == join_key(
        "Bacteroides fragilis 3397 T10"
    )
    assert join_key("Norethindrone acetate") == join_key("NORETHINDRONEACETATE")
    assert join_key(None) == ""


def test_a_patric_id_yields_the_ncbi_taxid_or_nothing():
    """The first component of a PATRIC genome id *is* an NCBI taxid, which is
    the only identifier the gene sheet and the screen share. A spelling this
    function does not recognise gives no organism rather than a plausible wrong
    one."""
    assert patric_tax_id("fig|226186.12.peg.149") == 226186
    assert patric_tax_id("fig|411903.6.peg.275") == 411903
    assert patric_tax_id("226186.12") is None
    assert patric_tax_id(None) is None


def test_the_drug_routes_are_ordered_verbatim_first_and_have_no_atc_route():
    """Supplementary table 2 carries no ATC column, so Maier's middle route does
    not exist here — and it carries something Maier's library does not, a parent
    drug name of its own. That is still verbatim: the file supplies it. The
    derived salt strip is tried last, as it is in both screens."""
    # A parent column that repeats the screened spelling adds no route, so the
    # salt strip is the only way past the counter-ion.
    assert [
        r for _k, _v, r in drug_variants("AMPICILLIN SODIUM", "Ampicillin sodium")
    ] == ["molename", "salt-name"]
    assert [r for _k, _v, r in drug_variants("VANCOMYCIN", "Vancomycin")] == [
        "molename"
    ]
    # And a salt strip that lands on the spelling the parent column already gave
    # is not a third attempt: the same key twice would double-count the route.
    assert [r for _k, _v, r in drug_variants("ABACAVIR SULFATE", "Abacavir")] == [
        "molename",
        "parent-name",
    ]


def test_an_override_is_written_only_where_the_row_confirms_it():
    """Five of the 76 strain names are corrected and two deliberately are not.
    Each correction is confirmed by something other than the spelling — a
    culture-collection number, an exhaustive edit-distance-1 search, or the
    binomial being a verbatim prefix — and the two that are not corrected have
    **two** NCBI candidates each with nothing in the row to choose between."""
    assert set(SPECIES_OVERRIDES) == {
        "pretovella copri",
        "bryantia formataxigens",
        "eubacterium biforme",
        "odoribacter splanchnius",
        "lactobacillus  reuteri cf48-3a",
    }
    assert all(key == key.casefold() for key in SPECIES_OVERRIDES)
    assert set(AMBIGUOUS_STRAINS) == {"bacteroides wh2", "bifidobacterium ruminatum"}
    # The two maps are disjoint: a name is either corrected or refused, never
    # both, and a name in neither resolves on its own.
    assert not set(SPECIES_OVERRIDES) & set(AMBIGUOUS_STRAINS)
    assert all(len(c) > 1 for c in AMBIGUOUS_STRAINS.values()), (
        "a name with one candidate would be an override, not a refusal"
    )
    # The column map is keyed on the screen's verbatim header, double space and
    # all, because a prefix rule would match seven B. fragilis rows at once.
    assert "Escherichia coli  K-12" in COLUMN_OVERRIDES


# --------------------------------------------------------------------------
# The two relationships, their direction, and why they are two
# --------------------------------------------------------------------------


def test_the_edge_runs_from_the_bacterium_to_the_drug(graph):
    """Maier's screen says the drug changes the bug and its edges run
    `Drug -> Taxon`; this one says the bug changes the drug. Reversing either to
    make the pair symmetric would put the agent on the wrong end of half the
    edges — and `tests/test_acceptance.py` asserts that every `Drug -> Taxon`
    edge in the graph is the growth screen's, which only stays true because this
    source points the other way."""
    result = one(
        graph,
        f"MATCH (t:Taxon)-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->"
        "(d:Drug) RETURN count(r) AS edges, count(DISTINCT d) AS drugs, "
        "count(DISTINCT t) AS taxa",
    )
    assert result["edges"] == EDGES
    assert result["drugs"] == DRUGS
    assert result["taxa"] == TAXA
    assert not rows(
        graph,
        f"MATCH (d:Drug)-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->"
        "(t:Taxon) RETURN r",
    ), "a metabolism edge points from the drug to the bacterium"


def test_a_measured_non_hit_is_never_reachable_as_metabolism(graph):
    """The fixture says *E. coli K-12 does not metabolise paracetamol* — and the
    screen measured it, so that is a finding rather than an absence. Folding it
    into a property of a `METABOLISES` edge would make every
    `MATCH (t)-[:METABOLISES]->(d)` count it as metabolism, silently, for anyone
    who did not know to add a WHERE clause. It is Part D's own rule for this
    layer: two edge types, never one."""
    assert not rows(
        graph,
        f"MATCH (t:Taxon {{id: {E_COLI}}})-[r:{RELATION_METABOLISES}]->"
        f"(d:Drug {{id: '{ACETAMINOPHEN}'}}) "
        f"WHERE r.screen_column = '{E_COLI_OTHER_COLUMN}' RETURN r",
    )
    refutation = one(
        graph,
        f"MATCH (t:Taxon {{id: {E_COLI}}})-[r:{RELATION_NO_METABOLISM}]->"
        f"(d:Drug {{id: '{ACETAMINOPHEN}'}}) "
        f"WHERE r.screen_column = '{E_COLI_OTHER_COLUMN}' "
        "RETURN r.effect AS effect, r.source_relation AS relation, "
        "r.fdr_p_value AS p, r.percent_consumed AS consumed, "
        "r.drug_threshold_percent AS threshold, r.incubation_hours AS hours, "
        "r.replicates AS n",
    )
    assert refutation["effect"] == "not-metabolised"
    assert str(FDR_THRESHOLD) in refutation["relation"]
    # Depleted past the flat 20% floor and past significance in neither: this is
    # the cell that separates the published per-drug threshold from a floor.
    assert refutation["p"] > FDR_THRESHOLD
    assert refutation["consumed"] > 20.0
    assert refutation["threshold"] == 25.0
    # The negative is *bounded*, which is what makes it usable: not "nobody
    # looked", but "nothing at 12 h over four cultures".
    assert refutation["hours"] == 12.0 and refutation["n"] == 4


def test_both_populations_are_counted_and_neither_is_dropped(graph):
    """G4 applied to a screen: 7 hits and 40 measured non-hits in the fixture,
    2,575 and 17,479 in the real file. A loader that kept only the hits would
    look identical in every hit query and would have thrown away the half of the
    matrix that makes 'this strain was given this drug and did nothing to it'
    answerable at all."""
    counts = {
        rel: one(graph, f"MATCH ()-[r:{rel}]->() RETURN count(r) AS n")["n"]
        for rel in (RELATION_METABOLISES, RELATION_NO_METABOLISM)
    }
    assert counts[RELATION_METABOLISES] == METABOLISES
    assert counts[RELATION_NO_METABOLISM] == NO_METABOLISM
    effects = {
        r["effect"]
        for r in rows(
            graph,
            f"MATCH ()-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->() "
            "RETURN DISTINCT r.effect AS effect",
        )
    }
    assert effects == {"metabolised", "not-metabolised"}
    # And the two screens' `effect` vocabularies do not overlap: a shared
    # `no-effect` token would make one WHERE clause mix "did not stop it
    # growing" with "did not touch the drug".
    growth = {
        r["effect"]
        for r in rows(
            graph,
            "MATCH ()-[r:INHIBITS_GROWTH_OF|DOES_NOT_INHIBIT_GROWTH_OF]->() "
            "RETURN DISTINCT r.effect AS effect",
        )
    }
    assert growth and not (growth & effects)


def test_an_abiotic_control_column_becomes_no_edge_and_one_ledger_row(
    graph, csv_dir, prep_output
):
    """The Maier lesson, in the other file: a column that reads exactly like a
    strain is not one. `Control pH 4` through `Control pH 7` sit among the
    strain columns with the same five sub-columns each, and on the real screen
    they produce 38 apparent hits between them. The fixture's single control is a
    hit for the first drug, so a loader that took the block structure at face
    value would write it."""
    assert not rows(
        graph,
        "MATCH ()-[r]->() WHERE r.screen_column STARTS WITH 'Control' RETURN r",
    )
    controls = ledger(csv_dir, "column")
    assert [r["record_id"] for r in controls] == ["Control pH 7"]
    assert "abiotic" in controls[0]["reason"]
    assert f"{CONTROL_CELLS:,} on an abiotic control column" in prep_output


def test_an_unmeasured_pair_is_neither_relationship_and_is_ledgered(graph, csv_dir):
    """All 20,596 measured cells of the real screen carry a number, which is
    worth knowing and is not worth trusting. A pair the screen did not measure
    is not a non-hit — calling it one invents a measurement, and it is exactly
    the direction that would look harmless."""
    for relationship in (RELATION_METABOLISES, RELATION_NO_METABOLISM):
        assert not rows(
            graph,
            f"MATCH (t:Taxon)-[r:{relationship}]->(d:Drug) "
            "WHERE r.reported_drug_name = 'AMPICILLIN SODIUM' "
            f"AND r.screen_column = '{E_COLI_OTHER_COLUMN}' RETURN r",
        )
    unmeasured = ledger(csv_dir, "cell")
    assert len(unmeasured) == NOT_MEASURED
    assert unmeasured[0]["record_id"] == f"AMPICILLIN SODIUM|{E_COLI_OTHER_COLUMN}"


# --------------------------------------------------------------------------
# The drug end: three routes, the other screen's nodes, and minting
# --------------------------------------------------------------------------


def test_each_join_route_reaches_its_drug_and_says_which_route_it_was(graph):
    """The routes are ordered verbatim-first and `drug_join` is what makes the
    weakest of them countable instead of assumed. `PARACETAMOL` is the reason
    the parent-name route exists at all: ChEMBL's `pref_name` is
    `ACETAMINOPHEN`, so no spelling of the screened name reaches it and only the
    file's own parent column does."""
    got = {
        (r["drug"], r["route"])
        for r in rows(
            graph,
            f"MATCH ()-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->(d:Drug) "
            "RETURN DISTINCT d.id AS drug, r.drug_join AS route",
        )
    }
    assert got == {
        (VANCOMYCIN, "molename"),
        (ACETAMINOPHEN, "parent-name"),
        (AMPICILLIN, "salt-name"),
        (METFORMIN, "parent-name"),
        (FICTITINE, "molename"),
        (INVENTOL, "minted"),
    }


def test_a_compound_the_other_screen_minted_reaches_that_node_not_a_second_one(
    graph, csv_dir, prep_output
):
    """**The reason `DEPENDS_ON` names `maier2018` and not only `chembl`.** 17 of
    the 271 real compounds reach a `Drug` node only because the growth screen
    minted one for them. Running first would mint a second node for each, and
    the split would be invisible: both nodes would have edges, both would look
    right, and D8's own question — does this drug inhibit gut bacteria *or* get
    metabolised by them — would return half an answer for every one of them."""
    node = one(
        graph,
        f"MATCH (d:Drug {{id: '{FICTITINE}'}}) "
        "RETURN d.source AS source, d.title AS name",
    )
    assert node["source"] == "maier2018", "the other screen still owns the node"
    both = one(
        graph,
        f"MATCH (d:Drug {{id: '{FICTITINE}'}}) "
        f"OPTIONAL MATCH (d)-[g:INHIBITS_GROWTH_OF|DOES_NOT_INHIBIT_GROWTH_OF]->() "
        f"OPTIONAL MATCH ()-[m:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->(d) "
        "RETURN count(DISTINCT g) AS growth, count(DISTINCT m) AS metabolism",
    )
    assert both["growth"] and both["metabolism"], (
        "one compound must carry both screens' edges, on one node"
    )
    assert len(table(csv_dir, "drug.csv")) == len(
        {r["drug_id"] for r in table(csv_dir, "drug.csv")}
    ), "drug.csv gained a duplicate identity"
    assert "joined to a node written by: chembl" in prep_output
    assert "maier2018" in prep_output.split("joined to a node written by:")[1]


def test_a_drug_no_route_reaches_is_minted_not_dropped(graph, csv_dir):
    """23 of the real screen's 271 compounds. Dropping them would drop 1,748
    measurements and would make the join rate unreadable — the misses would look
    like compounds the screen never tested."""
    node = one(
        graph,
        f"MATCH (d:Drug {{id: '{INVENTOL}'}}) "
        "RETURN d.title AS name, d.approved AS approved, d.source AS source, "
        "d.cas AS cas, d.trade_name AS trade, d.source_licence AS licence, "
        "d.chembl_id AS chembl",
    )
    assert node["name"] == "INVENTOL MESYLATE"
    assert node["cas"] == "88888-88-8" and node["trade"] == "INVENTA"
    assert node["source"] == SOURCE
    assert node["licence"] == "Zimmermann2019-unstated"
    assert not node["chembl"], "a minted node must not claim a ChEMBL identity"
    # Not `true`. Every compound screened here is a marketed oral drug, but
    # `approved` in this graph means ChEMBL max_phase 4, and inheriting the
    # claim from a screening library would put an unverified regulatory status
    # on 23 real nodes.
    assert node["approved"] is False
    minted = [r for r in table(csv_dir, "drug.csv") if r["source"] == SOURCE]
    assert len(minted) == MINTED_DRUGS


def test_the_drug_table_is_one_table_three_sources(csv_dir):
    """`drug.csv` is ChEMBL's file and both screens append to it — a shared
    table is how a further source contributes to one node type, not a second
    node type (microbiomekg.tables). `source` is what tells them apart, and the
    three columns this source adds are empty on the other two's rows rather than
    absent."""
    written = {r["source"] for r in table(csv_dir, "drug.csv")}
    assert written == {"chembl", "maier2018", SOURCE}
    others = [r for r in table(csv_dir, "drug.csv") if r["source"] != SOURCE]
    assert others
    assert all(r["cas"] == "" and r["trade_name"] == "" for r in others)


def test_a_screen_fact_about_a_known_drug_rides_on_the_edge(graph):
    """`drug.csv` is keyed on `drug_id` and the first row per key wins, so this
    screen's annotation for a compound ChEMBL already holds **cannot** be
    written onto its node — the constraint docs/model.md §ChEMBL records, and
    the one Maier's `drug_class` already answers to. It is also half of why
    MASI's substances are their own node type rather than rows in `drug.csv`.
    `therapeutic_indication` therefore rides on
    the edge, where it is there for all 271 screened compounds rather than only
    the 23 minted here."""
    node = one(
        graph,
        f"MATCH (d:Drug {{id: '{VANCOMYCIN}'}}) "
        "RETURN d.therapeutic_indication AS ind, d.source AS source",
    )
    assert node["source"] == "chembl"
    assert not node["ind"], "ChEMBL's row won the key, as the model says it must"
    edge = one(
        graph,
        f"MATCH ()-[r:{RELATION_METABOLISES}]->(d:Drug {{id: '{VANCOMYCIN}'}}) "
        "RETURN DISTINCT r.therapeutic_indication AS ind, "
        "r.parent_drug_name AS parent",
    )
    assert edge["ind"] == "antibiotic"
    assert edge["parent"] == "Vancomycin"


# --------------------------------------------------------------------------
# The taxon end: two joins, promotion, the override and the refusal
# --------------------------------------------------------------------------


def test_two_isolates_of_one_species_are_two_edges_on_one_taxon(graph):
    """The screen ran seven *B. fragilis* isolates and three
    *B. thetaiotaomicron* side by side. They are one taxon and independent
    measurements — C13's rule — and merging them would silently divide the
    evidence on that node."""
    result = one(
        graph,
        f"MATCH (t:Taxon {{id: {B_FRAGILIS}}})-[r:{RELATION_METABOLISES}|"
        f"{RELATION_NO_METABOLISM}]->(d:Drug {{id: '{VANCOMYCIN}'}}) "
        "RETURN count(r) AS edges, collect(DISTINCT r.screen_column) AS columns, "
        "count(DISTINCT r.strain) AS strains",
    )
    assert result["edges"] == 2
    assert sorted(result["columns"]) == [
        "Bacteroides fragilis DS-208",
        "Bacteroides fragilis NCTC9343",
    ]
    assert result["strains"] == 2, "the two isolates must stay distinguishable"


def test_the_column_override_is_what_reaches_the_strain_dictionary(graph, csv_dir):
    """The two sheets spell two of the 76 strains differently — table 3 writes
    the *E. coli* lineage where table 1 writes the Keio designation, and
    `formatexigens` where table 1 writes `formataxigens`. A prefix rule would
    catch the first and would also match `Bacteroides fragilis NCTC9343` against
    any of the seven *B. fragilis* rows, attaching one isolate's measurements to
    another's strain designation, so it is a closed two-entry map instead."""
    edge = one(
        graph,
        f"MATCH ()-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->() "
        f"WHERE r.screen_column = '{E_COLI_OTHER_COLUMN}' "
        "RETURN DISTINCT r.strain_join AS route, r.strain AS strain, "
        "r.reported_name AS said, r.phylum AS phylum",
    )
    assert edge["route"] == "override"
    assert edge["strain"] == "BW25113", "the override reached the right row"
    assert edge["said"].strip() == "Escherichia coli"
    assert edge["phylum"] == "Proteobacteria"
    # No column went unjoined: an unmatched header is a ledger row, and there
    # are none of that shape here.
    assert not [
        r
        for r in ledger(csv_dir, "column")
        if "no supplementary-table-1 row" in r["reason"]
    ]


def test_a_fecal_isolate_joins_on_its_name_because_it_has_no_designation(graph):
    """Four of the 76 rows have the literal `fecal isolate` where the others
    have a DSM or ATCC number, and their screen columns carry no designation at
    all. The name-only key is what reaches them — and it is added **only** for a
    name that appears once in the sheet, because seven rows say `Bacteroides
    fragilis` and a bare-name key would match a header against all of them."""
    edge = one(
        graph,
        f"MATCH (t:Taxon {{id: {F_PRAUSNITZII}}})-[r:{RELATION_METABOLISES}]->() "
        "RETURN DISTINCT r.strain_join AS route, r.strain AS strain",
    )
    assert edge["route"] == "name"
    assert edge["strain"] == "fecal isolate"


def test_the_species_override_is_what_keeps_l_reuteri_from_being_a_lost_taxon(
    graph, csv_dir
):
    """Supplementary table 1 writes a strain designation *inside* the species
    name. Letting the string fail reconciliation writes an `UnresolvedTaxon`
    tombstone asserting NCBI has lost *L. reuteri* — a false statement about the
    taxonomy, arrived at by doing nothing — and costs 271 measurements."""
    unresolved = {r["raw_name"] for r in table(csv_dir, "unresolved_taxa.csv")}
    assert not (unresolved & set(SPECIES_OVERRIDES.values()))
    edge = one(
        graph,
        f"MATCH (t:Taxon {{id: {L_REUTERI}}})-[r:{RELATION_METABOLISES}]->() "
        "RETURN r.reported_name AS said, r.taxon_join AS route, "
        "r.strain AS strain, r.resolution_status AS status",
    )
    # The string the source actually wrote survives on the edge, designation and
    # all, so the override is inspectable rather than a silent rewrite.
    assert edge["said"] == "Lactobacillus  reuteri CF48-3A"
    assert edge["route"] == "override"
    assert edge["strain"] == "BEI HM-102"
    assert edge["status"] == "synonym"


def test_a_subspecies_is_promoted_and_keeps_the_rank_it_came_from(graph):
    """G5's split: the edge is keyed on the species, and `original_rank` still
    says the screen named something narrower. These are cultured isolates, so
    `reported_rank` says that on every edge regardless of what NCBI's rank for
    the string turned out to be."""
    edge = one(
        graph,
        f"MATCH (t:Taxon {{id: {B_LONGUM}}})-[r:{RELATION_METABOLISES}]->() "
        "RETURN DISTINCT r.original_rank AS original, r.reported_rank AS reported, "
        "r.resolution_status AS status",
    )
    assert edge["original"] == "subspecies"
    assert edge["status"] == "promoted"
    assert edge["reported"] == "strain-level isolate"


def test_an_ambiguous_strain_is_a_tombstone_naming_what_was_rejected(graph, csv_dir):
    """G2: nothing is dropped, and a refusal is not a shrug. NCBI holds
    `Bacteroides sp. WH2` **and** `Bacteroides cellulosilyticus WH2`, the row's
    reference is the bare token `WH2`, and nothing chooses between them. Picking
    one would attribute a whole 271-cell row to an organism nobody screened and
    no count would show it; refusing without saying what was refused would leave
    the next reader with a dead end."""
    tomb = one(
        graph,
        "MATCH (u:UnresolvedTaxon) WHERE u.raw_name = 'Bacteroides WH2' "
        "RETURN u.status AS status, u.reported_rank AS rank, "
        "u.candidates AS candidates",
    )
    assert tomb["status"] == "unresolved"
    assert tomb["rank"] == "strain-level isolate"
    assert sorted(tomb["candidates"]) == ["1268240", "311784"]
    assert (
        len([r for r in table(csv_dir, "unresolved_taxa.csv") if r["source"] == SOURCE])
        == UNRESOLVED_TAXA
    )
    strain_rows = ledger(csv_dir, "strain")
    assert len(strain_rows) == 1
    assert "Bacteroides sp. WH2 (311784)" in strain_rows[0]["detail"]
    assert "Bacteroides cellulosilyticus WH2 (1268240)" in strain_rows[0]["detail"]
    assert not rows(
        graph,
        "MATCH ()-[r]->() WHERE r.screen_column = 'Bacteroides WH2 WH2' RETURN r",
    )


def test_every_screened_taxon_is_cited_and_loaded(graph, csv_dir):
    """`cited_taxa.csv` drives which taxa the taxonomy build keeps; a source that
    did not contribute to it would have its edges pointing at vivified stubs with
    no name and no lineage."""
    got = {
        r["tax_id"]
        for r in rows(
            graph,
            f"MATCH (t:Taxon)-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->() "
            f"WHERE r.primary_source = '{SOURCE}' RETURN DISTINCT t.id AS tax_id",
        )
    }
    cited = {
        int(r["tax_id"])
        for r in table(csv_dir, "cited_taxa.csv")
        if r["source"] == SOURCE
    }
    assert got and got <= cited
    assert all(
        row["organism"]
        for row in rows(
            graph,
            f"MATCH (t:Taxon)-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->() "
            "RETURN t.title AS organism",
        )
    ), "an edge landed on a stub with no name"


# --------------------------------------------------------------------------
# The gene layer, which is on the edge because there is no Gene node
# --------------------------------------------------------------------------


def test_a_gene_product_rides_on_the_edge_of_the_one_isolate_it_came_from(graph):
    """W7 asks for "the gene where identified" and the graph answers it in one
    hop, with no node type Part D queries. The join is the PATRIC genome's NCBI
    taxid **plus** the screened column's own collection number, and the second
    half is not optional: the real file has three *B. thetaiotaomicron* columns
    and the fixture has two *E. coli* ones, so a species-only match would
    attribute one isolate's gene to every isolate of its species."""
    edge = one(
        graph,
        f"MATCH ()-[r:{RELATION_METABOLISES}]->(d:Drug {{id: '{VANCOMYCIN}'}}) "
        f"WHERE r.screen_column = '{E_COLI_GENE_COLUMN}' "
        "RETURN r.gene_locus_tags AS tags, r.gene_products AS products, "
        "r.gene_protein_ids AS proteins, r.n_gene_products AS n",
    )
    assert edge["tags"] == ["Z_0152"]
    assert edge["products"] == ["acetyl esterase (acetylxylosidase)"]
    assert edge["proteins"] == ["NP_809065.1"]
    assert edge["n"] == 1
    sibling = one(
        graph,
        f"MATCH ()-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->"
        f"(d:Drug {{id: '{VANCOMYCIN}'}}) "
        f"WHERE r.screen_column = '{E_COLI_OTHER_COLUMN}' "
        "RETURN r.gene_locus_tags AS tags, r.n_gene_products AS n",
    )
    assert not sibling["tags"] and sibling["n"] is None, (
        "the other isolate of the same species must carry no gene evidence"
    )


def test_the_two_experiments_are_allowed_to_disagree_and_the_disagreement_shows(
    graph, prep_output
):
    """The gene products were identified by expressing a library in *E. coli*,
    not in the 76 strains these edges come from — so a gene can metabolise a drug
    its own donor strain did not touch in culture. Five of the real file's 37
    gene-supported pairs are that shape. Dropping them, or moving them onto the
    hit edge, would be inventing agreement between two experiments; they sit on
    the `DOES_NOT_METABOLISE` edge where they belong and the prep counts them."""
    divergent = one(
        graph,
        f"MATCH ()-[r:{RELATION_NO_METABOLISM}]->(d:Drug {{id: '{METFORMIN}'}}) "
        f"WHERE r.screen_column = '{E_COLI_GENE_COLUMN}' "
        "RETURN r.gene_locus_tags AS tags, r.effect AS effect",
    )
    assert divergent["tags"] == ["Z_2068"]
    assert divergent["effect"] == "not-metabolised"
    carried = one(
        graph,
        f"MATCH ()-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->() "
        "WHERE r.gene_locus_tags IS NOT NULL RETURN count(r) AS n",
    )
    assert carried["n"] == GENE_PAIRS
    assert (
        f"pairs carrying a gain-of-function gene product: {GENE_PAIRS} "
        f"({RELATION_METABOLISES} 1, {RELATION_NO_METABOLISM} 2)"
    ) in prep_output


def test_a_gene_the_screen_cannot_place_is_a_ledger_row_not_a_guess(csv_dir):
    """Two ways to fail and both are ledgered rather than resolved to the
    nearest organism: a PATRIC genome no screened column is, and a string that
    is not a PATRIC id at all. On the real file neither happens — which is only
    worth knowing because the check runs."""
    gene_rows = {r["record_id"]: r for r in ledger(csv_dir, "gene")}
    assert set(gene_rows) == {"COLAER_00311", "FAKE_0001"}
    assert "reaches no taxon" in gene_rows["COLAER_00311"]["reason"]
    assert "not a PATRIC feature id" in gene_rows["FAKE_0001"]["reason"]


def test_there_is_no_gene_node_type(graph):
    """The recommendation docs/model.md records, asserted so it cannot drift in
    by accident: 30 gene products over 3 organisms and 20 drugs, from a
    different experiment, that no Part D query asks for. If a `Gene` node ever
    earns its place, this test is where the decision gets restated."""
    from microbiomekg.fragments import compose

    from microbiomekg.ontology import ontology_for

    loaded = {
        label
        for row in rows(graph, "MATCH (n) RETURN DISTINCT labels(n) AS label")
        for label in row["label"]
    }
    declared = set(
        compose(ROOT / "microbiomekg" / "blueprints", [SOURCE, "chembl", "maier2018"])[
            "nodes"
        ]
    )
    classes = set(ontology_for([SOURCE, "chembl", "maier2018"])["classes"])
    assert loaded, "no node types at all — the assertion below would be vacuous"
    for forbidden in ("Gene", "GeneProduct", "Protein"):
        assert forbidden not in loaded | declared | classes


# --------------------------------------------------------------------------
# The derived call rule, the evidence contract, and C18 accounting
# --------------------------------------------------------------------------


def test_the_call_rule_is_re_derived_against_a_published_headline_on_every_run(
    prep_output,
):
    """The rule decides the *type* of every edge in this source and the sheet
    states only half of it, so trusting the module would make a silent drift a
    silent inversion of the whole layer. The prep re-derives it against a
    published count and refuses to write when it stops holding."""
    assert "the call rule reproduces the published headline: 5 of 6 drugs" in (
        prep_output
    )


def test_the_headline_check_refuses_to_write_when_it_stops_holding():
    """The gate that makes the line above worth printing, on both halves. A
    screen whose shape has changed cannot be checked against the published
    numbers at all, and a rule that no longer reproduces them is a rule we
    cannot use — writing 20,054 edges of unknown sign is the one failure this
    loader could never notice afterwards.

    The shape half matters as much as the count half: a gate that quietly
    stopped applying because a re-extraction dropped a column would be worse
    than no gate."""
    from microbiomekg.preps import prep_zimmermann2019 as prep

    screen = [
        {
            "drug": "A",
            "threshold": 20.0,
            "cells": [("Strain one", [50.0, 1.0, 0.5, 0.1, 0.001])],
        },
        {
            "drug": "B",
            "threshold": 20.0,
            "cells": [("Strain one", [1.0, 1.0, 0.01, 0.1, 0.9])],
        },
    ]
    columns = ["Strain one"]
    # One of the two drugs is metabolised, and the rule reproduces it.
    assert prep.check_headline(screen, columns, (2, 1, 1)) == 1
    with pytest.raises(SystemExit) as wrong_count:
        prep.check_headline(screen, columns, (2, 1, 2))
    assert "metabolised by at least one strain" in str(wrong_count.value)
    with pytest.raises(SystemExit) as wrong_shape:
        prep.check_headline(screen, columns, (271, 76, 176))
    assert "not 271 x 76" in str(wrong_shape.value)
    # And the real build's triple is the paper's, not something a caller chose.
    assert prep.PUBLISHED_MATRIX == (271, 76, 176)


def test_the_evidence_is_stated_and_is_the_same_on_every_edge(graph):
    """A metabolism screen in monoculture is `in-vitro` by Part B's own
    definition of the tier, and the workbook carries no per-row design, host or
    assay column that could move it. One value is not a missing value, and it is
    drawn from the pinned vocabulary rather than spelled at the write site."""
    assert EVIDENCE_LEVEL in EVIDENCE_LEVEL_VALUES
    for relationship in (RELATION_METABOLISES, RELATION_NO_METABOLISM):
        for row in rows(
            graph,
            f"MATCH ()-[r:{relationship}]->() "
            "RETURN DISTINCT r.evidence_level AS level, r.knowledge_level AS kl, "
            "r.agent_type AS agent, r.source_licence AS licence, "
            "r.publications AS pubs, r.pmid AS pmid",
        ):
            assert row["level"] == EVIDENCE_LEVEL == "in-vitro"
            assert row["kl"] == "knowledge_assertion"
            assert row["agent"] == "manual_agent"
            assert row["licence"] == "Zimmermann2019-unstated"
            assert row["pubs"] == [PUBLICATION] == ["PMID:31158845"]
            assert row["pmid"] == 31158845


def test_the_licence_is_its_own_token_so_the_two_screens_can_be_cut_apart(graph):
    """Journal supplementary material with no separate data licence, the same
    terms as Maier's — and a *different* token, because two subscription
    articles are two permissions and a reader excluding one has no reason to
    lose the other. G3's per-edge licence is what makes either cut one WHERE
    clause."""
    ours = one(
        graph,
        f"MATCH ()-[r:{RELATION_METABOLISES}|{RELATION_NO_METABOLISM}]->() "
        "WHERE r.source_licence <> 'Zimmermann2019-unstated' RETURN count(r) AS n",
    )
    assert ours["n"] == 0
    theirs = {
        r["licence"]
        for r in rows(
            graph,
            "MATCH ()-[r:INHIBITS_GROWTH_OF|DOES_NOT_INHIBIT_GROWTH_OF]->() "
            "RETURN DISTINCT r.source_licence AS licence",
        )
    }
    assert theirs == {"Maier2018-unstated"}


def test_the_metabolism_contract_is_a_rule_that_can_fail(graph):
    """Every field is written by this prep rather than read from upstream, so
    the rule *should* sit at zero — and a rule at zero is only worth having if it
    could move. The contract is the applicable subset: a monoculture metabolism
    screen has no direction, no cohort and no sequencing assay, and requiring
    those would report a permanent 100% meaning "this is not an abundance
    study"."""
    audit = {
        r["rule"]: r
        for r in rows(
            graph,
            "CALL ontology_audit() YIELD rule, violations, total "
            "RETURN rule, violations, total",
        )
    }
    for relationship in (RELATION_METABOLISES, RELATION_NO_METABOLISM):
        rule = audit[f"{relationship}.required_properties"]
        assert rule["total"] > 0, (
            f"{relationship} audits nothing — a gate that cannot fail"
        )
        assert rule["violations"] == 0, f"{relationship} violates its own contract"
    assert "direction" not in METABOLISM_CONTRACT
    assert "group_0_size" not in METABOLISM_CONTRACT
    assert "sequencing_type" not in METABOLISM_CONTRACT
    assert {"effect", "evidence_level", "publications"} <= set(METABOLISM_CONTRACT)


def test_every_screen_cell_is_an_edge_or_a_counted_reason(graph, csv_dir, prep_output):
    """Input cells = edges + unmeasured cells + the cells on an abiotic control
    column + the cells on a strain that reached no taxon. A silent drop cannot
    hide in the difference, and the two column-level terms are the ones a
    per-cell ledger would have buried: they are reported as counts instead."""
    edges = sum(
        one(
            graph,
            f"MATCH ()-[r:{rel}]->() WHERE r.primary_source = '{SOURCE}' "
            "RETURN count(r) AS n",
        )["n"]
        for rel in (RELATION_METABOLISES, RELATION_NO_METABOLISM)
    )
    assert edges == EDGES
    assert len(table(csv_dir, f"unresolved_{SOURCE}.csv")) == LEDGER_ROWS
    assert (
        f"not loaded: {NOT_MEASURED:,} cells the screen left a number out of, "
        f"{CONTROL_CELLS:,} on an abiotic control column, "
        f"{UNUSABLE_CELLS:,} on a strain that reached no taxon, "
        f"0 on a drug with no identifier"
    ) in prep_output
    assert EDGES + NOT_MEASURED + CONTROL_CELLS + UNUSABLE_CELLS == CELLS


def test_the_prep_reports_what_it_did_not_load(prep_output):
    for phrase in (
        "by relationship:",
        "measured non-hits kept as",
        "pairs carrying a gain-of-function gene product",
        "drug join:",
        "joined to a node written by:",
        "strain join:",
        "organism resolution:",
        "not loaded:",
        "minted",
        "abiotic controls, not organisms",
    ):
        assert phrase in prep_output


def test_an_absent_workbook_leaves_the_build_without_failing_it(tmp_path):
    """Exit 3 is "this source's raw file is not on this machine", which
    `scripts/build.py` treats as a source that did not run rather than as a
    failure. Exit 2 would take the whole build down with it."""
    proc = subprocess.run(
        [
            sys.executable,
            str(PREP),
            "--tables",
            str(tmp_path),
            "--taxdump",
            str(TAXDUMP_MINI),
            "--out",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    assert proc.returncode == 3
    assert WORKBOOK in proc.stderr


@pytest.mark.fixture
def test_the_fixture_keeps_the_real_workbook_shape():
    """The loader finds table 1's organisms between a header cell and the mutant
    section that follows them, table 2's drugs between its header and a blank
    row that a block of *column descriptions* follows, and table 3's five
    sub-columns by their labels rather than by counting. A tidied fixture would
    exercise none of that and would pass while the real file broke."""
    import openpyxl

    book = openpyxl.load_workbook(ZIMMERMANN_MINI / WORKBOOK, data_only=True)
    try:
        assert "Supplementary Table 1" in book.sheetnames
        strains = list(book["Supplementary Table 1"].iter_rows(values_only=True))
        drugs = list(book["Supplementary Table 2"].iter_rows(values_only=True))
        screen = list(book["Supplementary Table 3"].iter_rows(values_only=True))
        genes = list(book["Supplementary Table 13"].iter_rows(values_only=True))
    finally:
        book.close()

    # Table 1: a title, blanks, the header, a sub-heading with no phylum, the
    # organisms, then the mutants and plasmids that are not organisms.
    assert strains[0][0].startswith("Supplementary Table 1")
    assert strains[3][0] == "Name"
    assert any(
        row[0] == "Human gut bacteria tested for drug-metabolizing activity"
        and row[1] is None
        for row in strains
    )
    assert any(
        str(row[0] or "").startswith("Bacteroides thetaiotaomicron (Background")
        for row in strains
    )
    assert any(row[0] == "Plasmids" for row in strains)

    # Table 2: the data, a blank row, then the sheet describing its own columns.
    header_at = next(i for i, row in enumerate(drugs) if row[0] == "MOLENAME")
    blank_at = next(
        i
        for i, row in enumerate(drugs[header_at + 1 :], header_at + 1)
        if row[0] is None
    )
    assert any(row[0] == "MOLENAME" for row in drugs[blank_at:]), (
        "the column-description block is what makes the blank-row terminator "
        "load-bearing"
    )

    # Table 3: two header rows, the control among the strains, five sub-columns.
    block_at = next(i for i, row in enumerate(screen) if row[0] == "DrugName")
    labels = [c for c in screen[block_at] if c][1:]
    assert len(labels) == COLUMNS
    assert 0 < labels.index("Control pH 7 ") < len(labels) - 1, (
        "a control at either end could be found by position"
    )
    assert screen[block_at + 1][1] == "Drug adaptive FC threshold %"
    first = screen[block_at].index(labels[0])
    assert [str(screen[block_at + 1][first + k]).split()[0] for k in range(5)] == [
        "%",
        "%",
        "FC",
        "FC",
        "p(FDR)",
    ]
    assert len([r for r in screen[block_at + 2 :] if r[0]]) == DRUGS
    # The unmeasured cell is a *blank*, not a zero, which is what makes
    # `as_float` the right tool and a `float(cell) or 0` the wrong one.
    assert any(cell is None for row in screen[block_at + 2 :] for cell in row[2:])

    # Table 13: parent-drug columns interleaved with metabolite-mass columns.
    gene_at = next(i for i, row in enumerate(genes) if row[0] == "Gene")
    sub = genes[gene_at + 1]
    assert list(sub[:4]) == ["RefSeq Locus Tag", "PATRIC ID", "Product", "Protein ID"]
    assert sub.count("Parent drug") == 3
    assert any(isinstance(c, float) for c in sub[4:]), (
        "a metabolite-mass column is what the reader has to filter out"
    )
