"""Maier 2018: the first direct drug→taxon edge, and the negatives that make it
worth having.

The fixture (``tests/fixtures/maier2018_mini/``, generated by
``tests/fixtures/make_maier2018_mini.py``, which names every row and its trap)
is loaded through the real prep and the real blueprint alongside ChEMBL's,
because most of what is worth asserting here is a *join* to what ChEMBL wrote:

* ``Vancomycin`` must reach ``VANCOMYCIN`` by name, ``Paracetamol`` must reach
  ``ACETAMINOPHEN`` by its ATC code — the name route cannot get there — and
  ``Ampicillin sodium`` must reach ``AMPICILLIN`` only after its salt suffix is
  stripped. Each route is recorded on the edge, so the weakest one is countable;
* a drug none of the three reaches must become a node keyed on its Prestwick
  catalogue number rather than disappearing, and must not claim to be approved;
* the two *B. fragilis* isolates must land on **one** taxon as **two** edges per
  drug, and the string that names neither must be a tombstone.

And the two that are the whole point of the source: a measured non-hit must not
be reachable by a query for an inhibition, and a pair the screen wrote ``NA``
for must be neither.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from microbiomekg.rawdata import MalformedInput

from prep_support import load_graph_for, rows_of, run_prep

from conftest import TAXDUMP_MINI

kglite = pytest.importorskip("kglite")

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parent / "fixtures"
MAIER_MINI = FIXTURES / "maier2018_mini"
CHEMBL_MINI = FIXTURES / "chembl_mini"
SCRIPTS = ROOT / "scripts"
PREPS_DIR = ROOT / "microbiomekg" / "preps"
PREP = PREPS_DIR / "prep_maier2018.py"


for _needed in (
    PREP,
    MAIER_MINI / "NIHMS76168-supplement-Supplementary_table_3.xlsx",
    CHEMBL_MINI / "mechanism.jsonl",
):
    if not _needed.exists():
        pytest.skip(f"{_needed} does not exist yet", allow_module_level=True)

from microbiomekg.drugs import atc_level5, strip_salt  # noqa: E402
from microbiomekg.ontology import EVIDENCE_LEVEL_VALUES  # noqa: E402
from microbiomekg.ontology.maier2018 import (  # noqa: E402
    EVIDENCE_LEVEL,
    GROWTH_CONTRACT,
    HIT_THRESHOLD,
    PUBLICATION,
    RELATION_INHIBITS,
    RELATION_NO_EFFECT,
    SPECIES_OVERRIDES,
    drug_variants,
    nt_code_of,
    pubchem_cid,
    relation_for,
)

SOURCE = "maier2018"

# --------------------------------------------------------------------------
# Golden values, derived from the fixture by hand and asserted exactly.
# --------------------------------------------------------------------------

DRUGS = 5
ISOLATES = 6  # columns of the fixture screen
CELLS = DRUGS * ISOLATES
EDGES = 24
INHIBITS = 12
NO_EFFECT = 12
NOT_MEASURED = 1  # the one cell written `NA`
UNUSABLE_CELLS = 5  # the five on the isolate that reaches no taxon
LEDGER_ROWS = 2  # one unmeasured cell + one unresolvable isolate
UNRESOLVED_TAXA = 1
TAXA = 4  # 40 fixture columns collapse: both B. fragilis isolates
MINTED_DRUGS = 1

B_THETA = 818
B_FRAGILIS = 817
E_COLI = 562
B_LONGUM = 216816

VANCOMYCIN = "CHEMBL:CHEMBL262777"
ACETAMINOPHEN = "CHEMBL:CHEMBL112"
AMPICILLIN = "CHEMBL:CHEMBL174"
FICTITINE = "PRESTWICK:Prestw-9999"


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    """ChEMBL and Maier through their real preps, then the real blueprint."""
    work = tmp_path_factory.mktemp("maier2018")
    csv_dir = work / "csv"
    csv_dir.mkdir()

    def run(script, *args):
        return run_prep(script, *args)

    # Prep order is the build's: `prep_maier2018` declares DEPENDS_ON = [chembl]
    # because all three of its drug join routes read `drug`.
    run(
        PREPS_DIR / "prep_chembl.py",
        "--chembl",
        str(CHEMBL_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
    )
    prep = run(
        PREP,
        "--tables",
        str(MAIER_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
    )
    run(
        PREPS_DIR / "prep_taxonomy.py",
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
        "--scope",
        "cited",
        "--cited-from",
        str(csv_dir / "cited_taxa.csv"),
    )

    sources = [SOURCE, "chembl"]
    return load_graph_for(csv_dir, sources), csv_dir, prep.stdout


@pytest.fixture(scope="module")
def graph(built):
    return built[0]


@pytest.fixture(scope="module")
def csv_dir(built):
    return built[1]


@pytest.fixture(scope="module")
def prep_output(built):
    return built[2]


def rows(graph, query):
    return list(graph.cypher(query))


def one(graph, query):
    result = rows(graph, query)
    assert result, f"query returned no rows:\n{query}"
    return result[0]


def table(csv_dir, name):
    return rows_of(csv_dir, name)


# --------------------------------------------------------------------------
# The parsing vocabulary, as unit tests: these run without a graph
# --------------------------------------------------------------------------


def test_the_hit_threshold_decides_the_relationship_and_na_decides_neither():
    """`relation_for` is where the whole source's sign lives. The 55 real cells
    written `NA` are the case a `float(v) < THRESHOLD` written inline gets
    wrong twice over — it raises on the string, and a `try` wide enough to
    swallow that would file the pair as a non-hit, which is a measurement
    nobody made."""
    assert relation_for(HIT_THRESHOLD / 10) == RELATION_INHIBITS
    assert relation_for(HIT_THRESHOLD) == RELATION_NO_EFFECT
    assert relation_for(0.9) == RELATION_NO_EFFECT
    assert relation_for(None) is None


def test_a_species_column_is_found_by_its_nt_code_not_by_position():
    """Table 3 puts four metadata columns before its forty species columns.
    Counting them works until a release adds one; the `(NT####)` suffix is
    what the sheet actually guarantees."""
    assert nt_code_of("Akkermansia muciniphila (NT5021)") == "NT5021"
    assert nt_code_of("Bacteroides fragilis (ET) (NT5033)") == "NT5033"
    assert nt_code_of("prestwick_ID") == ""
    assert nt_code_of("n_hit") == ""


def test_only_a_level_five_atc_code_is_a_join_key():
    """A level-4 code names a *class*: joining `L01BB` would put every
    nitrogen-mustard analogue on one node. The real cells are space-joined and
    mix levels, and the veterinary `Q` codes are eight characters and have no
    ChEMBL counterpart."""
    assert atc_level5("A07AB03") == ["A07AB03"]
    assert atc_level5("L01BB") == []
    assert atc_level5("C01EA01 G04BE01") == ["C01EA01", "G04BE01"]
    assert atc_level5("QJ01GB90 QJ51GB90 QA07AA92") == []
    assert atc_level5("-") == []
    assert atc_level5(None) == []


def test_a_salt_suffix_is_stripped_only_as_the_last_route():
    """ChEMBL keys `Drug` on the parent molecule, so stripping a salt moves
    *towards* this graph's own identity. It is still a derivation, so it is
    tried after the source's own spelling and after the ATC code — the same
    verbatim-before-derived rule `njc19.name_variants` uses."""
    assert strip_salt("Cetirizine dihydrochloride") == "Cetirizine"
    assert strip_salt("Quinidine hydrochloride monohydrate") == "Quinidine"
    assert strip_salt("Ampicillin") == "Ampicillin"
    # "Sodium" as the *first* word is part of the drug's name, not a counter-ion.
    assert strip_salt("Sodium valproate") == "Sodium valproate"

    routes = [route for _kind, _key, route in drug_variants("Ampicillin sodium", "-")]
    assert routes == ["name", "salt-name"]
    routes = [route for _kind, _key, route in drug_variants("Paracetamol", "N02BE01")]
    assert routes == ["name", "atc"]


def test_a_stitch_id_yields_a_pubchem_cid_or_nothing():
    """`CID1` + eight zero-padded digits. A spelling this function does not
    recognise gives an empty property rather than a plausible wrong number."""
    assert pubchem_cid("CID100008646") == "8646"
    assert pubchem_cid("CID154687131") == "54687131"
    assert pubchem_cid("8646") == ""
    assert pubchem_cid(None) == ""


def test_the_species_overrides_are_a_closed_map_of_verbatim_strings():
    """Two hand-written phrases in one file, not a grammar. A suffix-stripping
    rule general enough to catch them would mangle the next organism name, and
    the two here are the only strings in supplementary table 2 that carry an
    isolate qualifier inside the species column."""
    assert set(SPECIES_OVERRIDES) == {
        "bacteroides fragilis nontoxigenic",
        "bacteroides fragilis enterotoxigenic (et)",
    }
    assert set(SPECIES_OVERRIDES.values()) == {"Bacteroides fragilis"}
    assert all(key == key.casefold() for key in SPECIES_OVERRIDES)


# --------------------------------------------------------------------------
# The two relationships — and why they are two
# --------------------------------------------------------------------------


def test_a_direct_drug_to_taxon_edge_exists_at_all_which_is_the_point(graph):
    """Before this source there was **no** `Drug`–`Taxon` edge in the graph, and
    `tests/test_acceptance.py` asserted the zero so the gap could not close by
    accident. ChEMBL's only route from a drug to a taxon runs through the
    protein it acts on, which is a different claim; this is the direct one."""
    result = one(
        graph,
        "MATCH (d:Drug)-[r]->(t:Taxon) RETURN count(r) AS edges, "
        "count(DISTINCT d) AS drugs, count(DISTINCT t) AS taxa",
    )
    assert result["edges"] == EDGES
    assert result["drugs"] == DRUGS
    assert result["taxa"] == TAXA


def test_a_measured_non_hit_is_never_reachable_as_an_inhibition(graph):
    """The fixture says *Paracetamol does not inhibit E. coli K-12* — and the
    screen measured it, so that is a finding rather than an absence. Folding it
    into a property of an `INHIBITS_GROWTH_OF` edge would make every
    `MATCH (d)-[:INHIBITS_GROWTH_OF]->(t)` count it as an inhibition, silently,
    for anyone who did not know to add a WHERE clause. It is Part D's own rule
    for this layer: two edge types, never one."""
    assert not rows(
        graph,
        f"MATCH (d:Drug {{id: '{ACETAMINOPHEN}'}})-[r:{RELATION_INHIBITS}]->"
        f"(t:Taxon {{id: {E_COLI}}}) RETURN r",
    )
    refutation = one(
        graph,
        f"MATCH (d:Drug {{id: '{ACETAMINOPHEN}'}})-[r:{RELATION_NO_EFFECT}]->"
        f"(t:Taxon {{id: {E_COLI}}}) "
        "RETURN r.effect AS effect, r.source_relation AS relation, "
        "r.adjusted_p_value AS p, r.screen_concentration_um AS conc",
    )
    assert refutation["effect"] == "no-effect"
    assert str(HIT_THRESHOLD) in refutation["relation"]
    assert refutation["p"] >= HIT_THRESHOLD
    # The negative is *bounded*, which is what makes it usable: not "nobody
    # looked", but "20 µM did nothing".
    assert refutation["conc"] == 20.0


def test_both_populations_are_counted_and_neither_is_dropped(graph):
    """G4 applied to a screen: 12 hits and 12 measured non-hits in the fixture,
    5,592 and 42,233 in the real file. A loader that kept only the hits would
    look identical in every hit query and would have thrown away the half of
    the matrix no other source in this graph has."""
    counts = {
        rel: one(graph, f"MATCH ()-[r:{rel}]->() RETURN count(r) AS n")["n"]
        for rel in (RELATION_INHIBITS, RELATION_NO_EFFECT)
    }
    assert counts[RELATION_INHIBITS] == INHIBITS
    assert counts[RELATION_NO_EFFECT] == NO_EFFECT
    effects = {
        r["effect"]
        for r in rows(
            graph,
            f"MATCH ()-[r:{RELATION_INHIBITS}|{RELATION_NO_EFFECT}]->() "
            "RETURN DISTINCT r.effect AS effect",
        )
    }
    assert effects == {"inhibited", "no-effect"}


def test_an_unmeasured_pair_is_neither_relationship_and_is_ledgered(graph, csv_dir):
    """55 of the real screen's 47,880 cells are the literal `NA`. A pair the
    screen did not measure is not a non-hit — calling it one invents a
    measurement, and it is exactly the direction that would look harmless."""
    for relationship in (RELATION_INHIBITS, RELATION_NO_EFFECT):
        assert not rows(
            graph,
            f"MATCH (d:Drug)-[r:{relationship}]->(t:Taxon {{id: {B_FRAGILIS}}}) "
            "WHERE r.reported_drug_name = 'Aspirin' AND r.nt_code = 'NT5003' "
            "RETURN r",
        )
    unmeasured = [
        r for r in table(csv_dir, "unresolved_maier2018.csv") if r["kind"] == "cell"
    ]
    assert len(unmeasured) == NOT_MEASURED
    assert unmeasured[0]["record_id"] == "Prestw-9998|NT5003"
    assert "NA" in unmeasured[0]["reason"]


# --------------------------------------------------------------------------
# The drug end: three routes, and what happens when none of them works
# --------------------------------------------------------------------------


def test_each_join_route_reaches_its_drug_and_says_which_route_it_was(graph):
    """The routes are ordered verbatim-first, and `drug_join` is what makes the
    weakest of them countable instead of assumed. `Paracetamol` is the reason
    the ATC route exists at all: ChEMBL's `pref_name` is `ACETAMINOPHEN`, so no
    spelling of the catalogue name reaches it and only the code does."""
    got = {
        (r["drug"], r["route"])
        for r in rows(
            graph,
            f"MATCH (d:Drug)-[r:{RELATION_INHIBITS}|{RELATION_NO_EFFECT}]->() "
            "RETURN DISTINCT d.id AS drug, r.drug_join AS route",
        )
    }
    assert got == {
        (VANCOMYCIN, "name"),
        (ACETAMINOPHEN, "atc"),
        (AMPICILLIN, "salt-name"),
        (FICTITINE, "minted"),
        ("CHEMBL:CHEMBL25", "name"),
    }


def test_a_drug_no_route_reaches_is_minted_not_dropped(graph, csv_dir):
    """330 of the real screen's 1,197 drugs. Dropping them would drop 12,540
    measurements and would make the join rate unreadable — the misses would
    look like drugs the screen never tested."""
    node = one(
        graph,
        f"MATCH (d:Drug {{id: '{FICTITINE}'}}) "
        "RETURN d.title AS name, d.approved AS approved, d.source AS source, "
        "d.prestwick_id AS prestwick, d.pubchem_cid AS cid, "
        "d.source_licence AS licence, d.chembl_id AS chembl",
    )
    assert node["name"] == "Fictitine hydrochloride"
    assert node["prestwick"] == "Prestw-9999"
    assert node["cid"] == "99999"
    assert node["source"] == SOURCE
    assert node["licence"] == "Maier2018-unstated"
    assert not node["chembl"], "a minted node must not claim a ChEMBL identity"
    # Not `true`. The Prestwick library is marketed as approved drugs, but
    # `approved` in this graph means ChEMBL max_phase 4, and inheriting the
    # claim from a catalogue would put an unverified regulatory status on 330
    # real nodes.
    assert node["approved"] is False
    minted = [r for r in table(csv_dir, "drug.csv") if r["source"] == SOURCE]
    assert len(minted) == MINTED_DRUGS


def test_the_drug_table_is_one_table_two_sources(graph, csv_dir):
    """the `drug` table is ChEMBL's and this source merges into it — a shared
    table is how a second source contributes to one node type, not a second
    node type (microbiomekg.tables). `source` is what tells them apart."""
    written = {r["source"] for r in table(csv_dir, "drug.csv")}
    assert written == {"chembl", SOURCE}
    # And the four columns this source adds are empty on ChEMBL's rows rather
    # than absent, which is what lets two sources share a table without either
    # knowing the other's schema.
    chembl_rows = [r for r in table(csv_dir, "drug.csv") if r["source"] == "chembl"]
    assert chembl_rows
    assert all(r["prestwick_id"] == "" for r in chembl_rows)


def test_a_screen_fact_about_a_chembl_drug_rides_on_the_edge(graph):
    """`drug` is keyed on `drug_id` and the first row per key wins, so a
    Prestwick fact about a drug ChEMBL already holds **cannot** be written onto
    its node — docs/model.md §ChEMBL records the constraint. `drug_class`
    therefore rides on the edge, where it is there for all 1,197 screened drugs
    rather than only the 330 this source minted."""
    node = one(
        graph,
        f"MATCH (d:Drug {{id: '{VANCOMYCIN}'}}) "
        "RETURN d.screen_drug_class AS cls, d.source AS source",
    )
    assert node["source"] == "chembl"
    assert not node["cls"], "ChEMBL's row won the key, as the model says it must"
    edge = one(
        graph,
        f"MATCH (d:Drug {{id: '{VANCOMYCIN}'}})-[r:{RELATION_INHIBITS}]->() "
        "RETURN DISTINCT r.drug_class AS cls, r.prestwick_id AS prestwick",
    )
    assert edge["cls"] == "antibiotics"
    assert edge["prestwick"] == "Prestw-1109"


# --------------------------------------------------------------------------
# The taxon end: promotion, the override, and the tombstone
# --------------------------------------------------------------------------


def test_two_isolates_of_one_species_are_two_edges_on_one_taxon(graph):
    """The screen ran a non-toxigenic and an enterotoxigenic *B. fragilis* side
    by side. They are one taxon and two measurements: C13's rule, and merging
    them would silently halve the evidence on that node."""
    result = one(
        graph,
        f"MATCH (d:Drug {{id: '{VANCOMYCIN}'}})-[r:{RELATION_INHIBITS}]->"
        f"(t:Taxon {{id: {B_FRAGILIS}}}) "
        "RETURN count(r) AS edges, collect(DISTINCT r.nt_code) AS codes, "
        "count(DISTINCT r.strain) AS strains",
    )
    assert result["edges"] == 2
    assert sorted(result["codes"]) == ["NT5003", "NT5033"]
    assert result["strains"] == 2, "the two isolates must stay distinguishable"


def test_the_species_override_is_what_keeps_b_fragilis_from_being_a_lost_taxon(
    graph, csv_dir
):
    """Supplementary table 2 writes the toxigenicity phenotype inside the
    species column. Letting the two strings fail reconciliation writes two
    `UnresolvedTaxon` tombstones each asserting NCBI has lost *Bacteroides
    fragilis* — a false statement about the taxonomy, arrived at by doing
    nothing — and costs 2,394 edges on the real file."""
    unresolved = {r["raw_name"] for r in table(csv_dir, "unresolved_taxa.csv")}
    assert not (unresolved & set(SPECIES_OVERRIDES.values()))
    assert "Bacteroides fragilis nontoxigenic" not in unresolved
    edge = one(
        graph,
        f"MATCH ()-[r:{RELATION_INHIBITS}]->(t:Taxon {{id: {B_FRAGILIS}}}) "
        "WHERE r.nt_code = 'NT5003' "
        "RETURN r.reported_name AS said, r.taxon_join AS route, "
        "r.strain AS strain, r.gram_stain AS gram",
    )
    # The string the source actually wrote survives on the edge, qualifier and
    # all, so the override is inspectable rather than a silent rewrite.
    assert edge["said"] == "Bacteroides fragilis nontoxigenic"
    assert edge["route"] == "override"
    assert edge["strain"] == "EN-2, VPI 2553"
    assert edge["gram"] == "negative"


def test_a_strain_and_a_subspecies_are_promoted_and_keep_the_rank_they_came_from(
    graph,
):
    """G5's split: the edge is keyed on the species, and `original_rank` still
    says the screen named something narrower. These are cultured lab isolates,
    so `reported_rank` says that on every edge regardless of what NCBI's rank
    for the string turned out to be."""
    coli = one(
        graph,
        f"MATCH ()-[r:{RELATION_INHIBITS}]->(t:Taxon {{id: {E_COLI}}}) "
        "RETURN DISTINCT r.original_rank AS original, r.reported_rank AS reported, "
        "r.resolution_status AS status, r.reported_name AS said",
    )
    assert coli["said"] == "Escherichia coli K-12"
    assert coli["original"] == "strain"
    assert coli["status"] == "promoted"
    assert coli["reported"] == "strain-level isolate"
    longum = one(
        graph,
        f"MATCH ()-[r:{RELATION_INHIBITS}]->(t:Taxon {{id: {B_LONGUM}}}) "
        "RETURN DISTINCT r.original_rank AS original, r.resolution_status AS status",
    )
    assert longum["original"] == "subspecies"
    assert longum["status"] == "promoted"


def test_an_unresolvable_isolate_is_a_tombstone_and_a_ledger_row_not_a_drop(
    graph, csv_dir
):
    """G2: nothing is dropped. The isolate is ledgered once rather than once per
    cell — on the real file a bad isolate costs 1,197 cells and 1,197 identical
    ledger rows would be noise — and the count of cells it cost is in the
    prep's own report, which the accounting test below reads."""
    tomb = one(
        graph,
        "MATCH (u:UnresolvedTaxon) WHERE u.raw_name = 'Nonexistiblia inventata' "
        "RETURN u.status AS status, u.reported_rank AS rank, u.note AS note",
    )
    assert tomb["status"] == "unresolved"
    assert tomb["rank"] == "strain-level isolate"
    assert tomb["note"]
    assert (
        len([r for r in table(csv_dir, "unresolved_taxa.csv") if r["source"] == SOURCE])
        == UNRESOLVED_TAXA
    )
    ledger = [
        r for r in table(csv_dir, "unresolved_maier2018.csv") if r["kind"] == "isolate"
    ]
    assert len(ledger) == 1
    assert ledger[0]["record_id"] == "NT5099"
    assert "unresolved" in ledger[0]["reason"]
    assert not rows(
        graph,
        "MATCH (d:Drug)-[r]->(t:Taxon) WHERE r.nt_code = 'NT5099' RETURN r",
    )


def test_every_screened_taxon_is_cited_and_loaded(graph, csv_dir):
    """`cited_taxa` drives which taxa the taxonomy build keeps; a source
    that did not contribute to it would have its edges pointing at vivified
    stubs with no name and no lineage."""
    got = {
        r["tax_id"]
        for r in rows(
            graph,
            "MATCH (d:Drug)-[r]->(t:Taxon) "
            f"WHERE r.primary_source = '{SOURCE}' RETURN DISTINCT t.id AS tax_id",
        )
    }
    cited = {
        int(r["tax_id"])
        for r in table(csv_dir, "cited_taxa.csv")
        if r["source"] == SOURCE
    }
    assert got and got <= cited
    assert all(
        row["organism"]
        for row in rows(
            graph, "MATCH (d:Drug)-[r]->(t:Taxon) RETURN t.title AS organism"
        )
    ), "an edge landed on a stub with no name"


# --------------------------------------------------------------------------
# The threshold, the follow-up, and the evidence contract
# --------------------------------------------------------------------------


def test_the_hit_threshold_is_re_derived_on_every_run(prep_output):
    """`HIT_THRESHOLD` decides the *type* of every edge in this source and the
    sheet never states it, so trusting the module would make a silent drift a
    silent inversion of the whole layer. The prep re-derives it against the
    sheet's own `n_hit` column and refuses to write when it stops holding."""
    assert f"hit threshold p < {HIT_THRESHOLD} reproduces the sheet's own n_hit" in (
        prep_output
    )


def test_the_threshold_check_refuses_to_write_when_it_stops_holding(tmp_path):
    """The gate that makes the line above worth printing. A sheet whose `n_hit`
    the threshold does not reproduce is a sheet whose hit calls we cannot
    derive — and writing 47,825 edges of unknown sign is the one failure this
    loader could never notice afterwards."""
    from microbiomekg.preps import prep_maier2018 as prep

    screen = [
        {
            "prestwick_ID": "Prestw-1",
            "n_hit": 3,
            "cells": [("NT5001", 0.5), ("NT5002", 0.5)],
        }
    ]
    with pytest.raises(MalformedInput) as excinfo:
        prep.check_threshold(screen)
    assert "does not reproduce" in str(excinfo.value)
    assert "Prestw-1" in str(excinfo.value)


def test_the_authors_own_confusion_matrix_lands_on_the_right_relationship(graph):
    """Supplementary table 4 re-measured 379 pairs and scored each against the
    screen's call. A `TP` or an `FP` can only sit on an `INHIBITS_GROWTH_OF`
    edge and a `TN` or an `FN` only on a `DOES_NOT_INHIBIT_GROWTH_OF` one, so
    this is a check on the derived threshold using a column that had no part in
    deriving it. On the real build it holds for all 379."""
    for relationship, allowed in (
        (RELATION_INHIBITS, {"TP", "FP"}),
        (RELATION_NO_EFFECT, {"TN", "FN"}),
    ):
        outcomes = {
            r["outcome"]
            for r in rows(
                graph,
                f"MATCH ()-[r:{relationship}]->() WHERE r.validation_outcome <> '' "
                "RETURN DISTINCT r.validation_outcome AS outcome",
            )
        }
        assert outcomes and outcomes <= allowed, relationship


def test_the_dose_response_follow_up_rides_on_the_pair_it_measured(graph):
    """The screen is one concentration; table 4 is a dilution series on 379
    pairs. The bounded negative is the interesting half — `> 160 µM` is a much
    stronger statement than "not at 20 µM" and it is the source's own wording,
    kept verbatim in `ic25_qualifier`."""
    positive = one(
        graph,
        f"MATCH (d:Drug {{id: '{ACETAMINOPHEN}'}})-[r:{RELATION_INHIBITS}]->"
        f"(t:Taxon {{id: {B_THETA}}}) "
        "RETURN r.validation_outcome AS outcome, r.ic25_qualifier AS qualifier, "
        "r.ic25_um AS ic25, r.mic_um AS mic",
    )
    assert positive["outcome"] == "TP"
    assert positive["qualifier"] == "="
    assert positive["ic25"] == 5.0 and positive["mic"] == 10.0
    negative = one(
        graph,
        f"MATCH (d:Drug {{id: '{ACETAMINOPHEN}'}})-[r:{RELATION_NO_EFFECT}]->"
        f"(t:Taxon {{id: {E_COLI}}}) "
        "RETURN r.validation_outcome AS outcome, r.ic25_qualifier AS qualifier, "
        "r.ic25_um AS ic25",
    )
    assert negative["outcome"] == "TN"
    assert negative["qualifier"] == ">"
    assert negative["ic25"] == 160.0
    # And a pair table 4 never looked at carries nothing rather than a zero.
    untouched = one(
        graph,
        f"MATCH (d:Drug {{id: '{VANCOMYCIN}'}})-[r:{RELATION_INHIBITS}]->() "
        "RETURN DISTINCT r.validation_outcome AS outcome, r.ic25_um AS ic25",
    )
    assert not untouched["outcome"] and untouched["ic25"] is None


def test_the_evidence_is_stated_and_is_the_same_on_every_edge(graph):
    """A growth screen is `in-vitro` by Part B's own definition of the tier, and
    the file carries no per-row design, host or assay column that could move it.
    One value is not a missing value, and it is drawn from the pinned vocabulary
    rather than spelled at the write site."""
    assert EVIDENCE_LEVEL in EVIDENCE_LEVEL_VALUES
    for relationship in (RELATION_INHIBITS, RELATION_NO_EFFECT):
        for row in rows(
            graph,
            f"MATCH ()-[r:{relationship}]->() "
            "RETURN DISTINCT r.evidence_level AS level, r.knowledge_level AS kl, "
            "r.agent_type AS agent, r.source_licence AS licence, "
            "r.publications AS pubs, r.pmid AS pmid",
        ):
            assert row["level"] == EVIDENCE_LEVEL == "in-vitro"
            assert row["kl"] == "knowledge_assertion"
            assert row["agent"] == "manual_agent"
            assert row["licence"] == "Maier2018-unstated"
            assert row["pubs"] == [PUBLICATION] == ["PMID:29555994"]
            assert row["pmid"] == 29555994


def test_the_licence_is_stated_as_unknown_rather_than_invented(graph):
    """Journal supplementary material with no separate data licence. Writing
    `CC-BY-4.0` here would put a redistribution claim in the graph that nobody
    made, on more edges than any other source contributes. G3's per-edge licence
    is what stops that one token contaminating everything else."""
    licences = {
        r["licence"]
        for r in rows(
            graph,
            "MATCH ()-[r]->() WHERE r.source_licence IS NOT NULL "
            "RETURN DISTINCT r.source_licence AS licence",
        )
    }
    assert "Maier2018-unstated" in licences
    shippable = one(
        graph,
        f"MATCH ()-[r:{RELATION_INHIBITS}|{RELATION_NO_EFFECT}]->() "
        "WHERE r.source_licence <> 'Maier2018-unstated' RETURN count(r) AS n",
    )
    assert shippable["n"] == 0, (
        "every edge of this source must carry the unstated licence, so one "
        "WHERE clause is the redistributable cut"
    )


def test_the_growth_contract_is_a_rule_that_can_fail(graph):
    """Every field is written by this prep rather than read from upstream, so
    the rule *should* sit at zero — and a rule at zero is only worth having if
    it could move. The contract is the applicable subset: a monoculture growth
    screen has no direction, no cohort and no sequencing assay, and requiring
    those would report a permanent 100% meaning "this is not an abundance
    study"."""
    audit = {
        r["rule"]: r
        for r in rows(
            graph,
            "CALL ontology_audit() YIELD rule, violations, total "
            "RETURN rule, violations, total",
        )
    }
    for relationship in (RELATION_INHIBITS, RELATION_NO_EFFECT):
        rule = audit[f"{relationship}.required_properties"]
        assert rule["total"] > 0, (
            f"{relationship} audits nothing — a gate that cannot fail"
        )
        assert rule["violations"] == 0, f"{relationship} violates its own contract"
    assert "direction" not in GROWTH_CONTRACT
    assert "group_0_size" not in GROWTH_CONTRACT
    assert "sequencing_type" not in GROWTH_CONTRACT
    assert {"effect", "evidence_level", "publications"} <= set(GROWTH_CONTRACT)


# --------------------------------------------------------------------------
# C18 accounting and the prep's own report
# --------------------------------------------------------------------------


def test_every_screen_cell_is_an_edge_or_a_counted_reason(graph, csv_dir, prep_output):
    """Input cells = edges + unmeasured cells + the cells on an isolate that
    reached no taxon. A silent drop cannot hide in the difference, and the last
    term is the one a per-cell ledger would have buried: it is reported as a
    count instead."""
    edges = sum(
        one(
            graph,
            f"MATCH ()-[r:{rel}]->() WHERE r.primary_source = '{SOURCE}' "
            "RETURN count(r) AS n",
        )["n"]
        for rel in (RELATION_INHIBITS, RELATION_NO_EFFECT)
    )
    assert edges == EDGES
    assert len(table(csv_dir, "unresolved_maier2018.csv")) == LEDGER_ROWS
    reported = re.search(
        r"not loaded: ([\d,]+) cells the screen wrote NA for, "
        r"([\d,]+) on an isolate that reached no taxon, "
        r"([\d,]+) on a drug with no identifier",
        prep_output,
    )
    assert reported, prep_output
    na, no_taxon, no_drug = (int(g.replace(",", "")) for g in reported.groups())
    assert (na, no_taxon, no_drug) == (NOT_MEASURED, UNUSABLE_CELLS, 0)
    assert edges + na + no_taxon + no_drug == CELLS


def test_the_prep_reports_what_it_did_not_load(prep_output):
    for phrase in (
        "by relationship:",
        "measured non-hits kept as",
        "pairs carrying the dose-response follow-up",
        "drug join:",
        "isolate join:",
        "organism resolution:",
        "not loaded:",
        "minted",
        "claimed by two library entries",
    ):
        assert phrase in prep_output


def test_an_atc_code_two_library_entries_claim_identifies_neither():
    """The Prestwick library screens stereoisomers and prodrug/active pairs as
    separate compounds, and an ATC code names the *substance* — so `(R)-` and
    `(S)-propranolol hydrochloride` share C07AA05. Joining both to the one
    ChEMBL node that code names is not a coarse answer but a wrong one: it
    attributes the R-enantiomer's measurement to the molecule ChEMBL keys as
    propranolol. Dropping the contested code is the same rule the ChEMBL side
    already applies to a code two ChEMBL nodes claim, and on the real file it
    is what takes the library from 1,180 distinct `Drug` nodes to 1,197 — one
    per entry, with no false merge."""
    from microbiomekg.preps import prep_maier2018 as prep

    contested = prep.contested_atc_codes(
        {
            "Prestw-1075": {"ATC codes": "C07AA05"},
            "Prestw-1081": {"ATC codes": "C07AA05"},
            "Prestw-45": {"ATC codes": "M01AE02"},
        }
    )
    assert contested == {"C07AA05": ["Prestw-1075", "Prestw-1081"]}
    # A code one entry carries twice is not contested — the same row, not two.
    assert (
        prep.contested_atc_codes({"Prestw-1": {"ATC codes": "C07AA05 C07AA05"}}) == {}
    )


@pytest.mark.fixture
def test_the_fixture_keeps_the_real_workbook_shape():
    """The loader finds table 2's header by searching for `NT data base`,
    because the real sheet opens with a title line and a blank and interleaves
    sub-headings among its rows; and it finds table 3's species columns by
    their `(NT####)` suffix rather than by counting the four metadata columns.
    A tidied fixture would exercise neither, and a fixed row skip would survive
    here and break on the real file."""
    import openpyxl

    book = openpyxl.load_workbook(
        MAIER_MINI / "NIHMS76168-supplement-Supplementary_table_2.xlsx"
    )
    try:
        assert book.sheetnames == ["S2. Species selection"]
        grid = list(book["S2. Species selection"].iter_rows(values_only=True))
    finally:
        book.close()
    assert grid[0][0].startswith("Isolates of the human microbiota")
    assert all(cell is None for cell in grid[1])
    assert grid[2][0] == "NT data base"
    # The sub-heading row the real sheet carries: an NT-less label among the
    # data, which the reader must skip without counting it as a lost isolate.
    assert any(row[0] == "Laboratory E. coli strains" for row in grid)

    book = openpyxl.load_workbook(
        MAIER_MINI / "NIHMS76168-supplement-Supplementary_table_3.xlsx"
    )
    try:
        grid = list(book["S3a. Adjusted p-values"].iter_rows(values_only=True))
    finally:
        book.close()
    header = [str(c) for c in grid[0]]
    assert header[:4] == ["prestwick_ID", "chemical_name", "drug_class", "n_hit"]
    assert [nt_code_of(c) for c in header[4:]] == [
        "NT5004",
        "NT5003",
        "NT5033",
        "NT5084",
        "NT5028",
        "NT5099",
    ]
    assert len(grid) - 1 == DRUGS
    # The `NA` cell is a *string*, which is what makes `float()` the wrong tool.
    assert any(cell == "NA" for row in grid[1:] for cell in row)
