"""NJC19: the consumption edge, the negatives that must stay countable, and the
name join that decides whether D6 has an answer at all.

The fixture (``tests/fixtures/njc19_mini/``, generated by
``tests/fixtures/make_njc19_mini.py``, which names every row and its trap) is
loaded through the real preps and the real blueprint alongside HMDB's and
MiMeDB's, because three of the things worth asserting here are *joins* to what
those two wrote:

* ``Butyrate`` must reach HMDB's ``Butyric acid`` node. If it does not, the
  producers are on one node and the consumers on another and D6's MES —
  **2·P·C / (P + C)** — is 0 for both halves of every short-chain fatty acid in
  the graph, which looks exactly like "no source has this";
* ``Pectin`` must reach the node **MiMeDB** wrote, which is the entire
  measurable contribution MiMeDB makes to this graph;
* ``Mucin`` must be minted, because nothing holds it and a dropped compound
  would remove a degradation claim the source did curate.

And the two that are about not inventing anything: the 6 host cell types must
not become ``UnresolvedTaxon`` tombstones, and a refutation must not be
reachable by a query for an observation.
"""

from __future__ import annotations

import csv
import json
import subprocess
import sys
from pathlib import Path

import pytest

from conftest import TAXDUMP_MINI

kglite = pytest.importorskip("kglite")

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parent / "fixtures"
NJC19_MINI = FIXTURES / "njc19_mini" / "41597_2020_516_MOESM1_ESM.xlsx"
MIMEDB_MINI = FIXTURES / "mimedb_mini"
HMDB_MINI = FIXTURES / "hmdb_mini" / "hmdb_metabolites.xml"
REACTOME_MINI = FIXTURES / "reactome_mini"
SCRIPTS = ROOT / "scripts"
PREP = SCRIPTS / "prep_njc19.py"

sys.path.insert(0, str(SCRIPTS))

for _needed in (PREP, NJC19_MINI, HMDB_MINI, MIMEDB_MINI / "mimedb_metabolites_v1.csv"):
    if not _needed.exists():
        pytest.skip(f"{_needed} does not exist yet", allow_module_level=True)

from microbiomekg.ontology import EVIDENCE_LEVEL_VALUES, EXCHANGE_CONTRACT  # noqa: E402
from microbiomekg.ontology.njc19 import (  # noqa: E402
    EVIDENCE_LEVEL,
    HOST_CELL_TYPES,
    activity_relations,
    name_variants,
    split_references,
)

SOURCE = "njc19"

# --------------------------------------------------------------------------
# Golden values, derived from the fixture by hand and asserted exactly.
# --------------------------------------------------------------------------

DATA_ROWS = 16  # rows under the header in the fixture sheet
EDGES = 11  # before dedupe; the byte-identical duplicate is one of them
PRODUCES = 4  # NJC19's own, after dedupe. HMDB adds 13 to the same table.
CONSUMES = 3
DEGRADES = 2
NO_EXCHANGE = 1
LEDGER_ROWS = 6  # host cell 1 + unresolved 2 + too broad 1 + unknown 1 + empty 1
UNRESOLVED_TAXA = 2  # Bacillus (ambiguous) and Mycoplasma pneumoniae

#: HMDB's butyric acid record in the mini fixture. The real file's is
#: CHEBI:30772; what matters here is that *one* node carries both sources.
BUTYRIC_ACID = "CHEBI:17968"
ACETIC_ACID = "CHEBI:30089"
DEOXYCHOLIC_ACID = "CHEBI:28834"


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    """HMDB, MiMeDB and NJC19 through their real preps, then the real blueprint."""
    work = tmp_path_factory.mktemp("njc19")
    csv_dir = work / "csv"
    csv_dir.mkdir()

    def run(script, *args):
        proc = subprocess.run(
            [sys.executable, str(script), *args],
            capture_output=True,
            text=True,
            cwd=ROOT,
        )
        assert proc.returncode == 0, (
            f"{script.name} failed:\n{proc.stdout}\n{proc.stderr}"
        )
        return proc

    # Prep order is the build's: `prep_njc19` declares DEPENDS_ON = [hmdb, mimedb]
    # because its compound join reads every Metabolite node that already exists.
    run(
        SCRIPTS / "prep_hmdb.py",
        "--xml",
        str(HMDB_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--reactome",
        str(REACTOME_MINI),
        "--out",
        str(csv_dir),
    )
    run(
        SCRIPTS / "prep_mimedb.py",
        "--metabolites",
        str(MIMEDB_MINI / "mimedb_metabolites_v1.csv"),
        "--microbes",
        str(MIMEDB_MINI / "mimedb_microbes_v1.csv"),
        "--njc19",
        str(NJC19_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
    )
    prep = run(
        PREP,
        "--xlsx",
        str(NJC19_MINI),
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
    )
    run(
        SCRIPTS / "prep_reactome.py",
        "--reactome",
        str(REACTOME_MINI),
        "--out",
        str(csv_dir),
    )
    run(
        SCRIPTS / "prep_taxonomy.py",
        "--taxdump",
        str(TAXDUMP_MINI),
        "--out",
        str(csv_dir),
        "--scope",
        "cited",
        "--cited-from",
        str(csv_dir / "cited_taxa.csv"),
    )

    from build_blueprint import compose

    from microbiomekg.ontology import ontology_for, write_json

    sources = [SOURCE, "hmdb", "mimedb", "reactome"]
    blueprint = compose(ROOT / "blueprints", sources)
    settings = blueprint.setdefault("settings", {})
    settings["root"] = str(csv_dir)
    for key in ("output", "output_path", "output_file"):
        settings.pop(key, None)
    write_json(csv_dir / "ontology.json", ontology_for(sources))
    blueprint["ontology"] = str(csv_dir / "ontology.json")
    local = csv_dir / "blueprint.test.json"
    local.write_text(json.dumps(blueprint))

    return kglite.from_blueprint(local, verbose=False, save=False), csv_dir, prep.stdout


@pytest.fixture(scope="module")
def graph(built):
    return built[0]


@pytest.fixture(scope="module")
def csv_dir(built):
    return built[1]


@pytest.fixture(scope="module")
def prep_output(built):
    return built[2]


def rows(graph, query):
    return list(graph.cypher(query))


def one(graph, query):
    result = rows(graph, query)
    assert result, f"query returned no rows:\n{query}"
    return result[0]


def table(csv_dir, name):
    with (csv_dir / name).open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


# --------------------------------------------------------------------------
# The vocabulary, as unit tests: these run without a graph
# --------------------------------------------------------------------------


def test_a_combined_activity_is_two_relations_and_a_bare_one_is_one():
    """180 real rows carry both directions. The parse that shipped first split
    the cell on its joining comma and rebuilt each atom by re-appending a
    closing bracket — which silently turned every one of the 477
    `Macromolecule degradation` rows, the only atom with no bracket, into an
    unrecognised activity and dropped `DEGRADES` to **zero edges**."""
    assert activity_relations("Consumption (import)") == [("CONSUMES", False)]
    assert activity_relations("Macromolecule degradation") == [("DEGRADES", False)]
    assert activity_relations("Macromolecule degradation (-)") == [("DEGRADES", True)]
    assert activity_relations("Consumption (import), Production (export)") == [
        ("CONSUMES", False),
        ("PRODUCES", False),
    ]
    assert activity_relations("Cross-feeding (unspecified)") == []
    assert activity_relations(None) == []


def test_a_negative_marker_negates_the_whole_cell():
    for cell in ("Consumption (import) (-)", "Production (export) (-)"):
        ((_relation, negated),) = activity_relations(cell)
        assert negated is True


def test_a_scoped_reference_cell_splits_by_direction():
    """`import:415, 418;export:417` — one row, two literatures. Carrying the
    whole cell on both edges attributes the import to the export's paper."""
    assert split_references("import:415, 418;export:417", "CONSUMES") == (
        ["415", "418"],
        False,
    )
    assert split_references("import:415, 418;export:417", "PRODUCES") == (
        ["417"],
        False,
    )
    # A plain cell belongs entirely to its single relationship.
    assert split_references("12, 197, 214", "PRODUCES") == (["12", "197", "214"], False)
    assert split_references(424, "PRODUCES") == (["424"], False)
    assert split_references(None, "PRODUCES") == ([], False)


def test_genus_level_evidence_is_all_and_not_any():
    """2,426 of the real file's 9,136 rows stand on nothing but `(G)` sources.
    "Any" would be the wrong quantifier — one species-level source makes the
    row a species-level claim with extra context."""
    assert split_references("217(G)", "PRODUCES") == (["217(G)"], True)
    assert split_references("205(G), 650(G)", "PRODUCES") == (
        ["205(G)", "650(G)"],
        True,
    )
    assert split_references("205(G), 650", "PRODUCES")[1] is False


def test_the_name_variants_try_what_the_source_wrote_before_anything_derived():
    """The order is the policy. `Formate` must not be answered by `Formic acid`
    while a node actually named `Formate` exists — the graph holds conjugate
    pairs as two identities (D5's key note) and merging them silently would be
    a claim this project has decided not to make."""
    routes = name_variants("Butyrate")
    assert routes[0] == ("Butyrate", "exact")
    assert routes[1] == ("Butyric acid", "conjugate")

    spellings = [
        s for s, _ in name_variants("L-Lactate ([S]-Lactate, Lactate, D-Lactate)")
    ]
    assert spellings[0] == "L-Lactate"
    # every derivation of the head name comes before the first synonym
    assert spellings.index("Lactic acid") < spellings.index("D-Lactate")

    # An acid name derives its conjugate base too — the rule runs both ways.
    assert ("Cholate", "conjugate") in name_variants("Cholic acid")


# --------------------------------------------------------------------------
# The three relationships, and the table PRODUCES shares with HMDB
# --------------------------------------------------------------------------


def test_consumes_exists_at_all_which_is_the_whole_point(graph):
    """No source in the profiled seven carries consumption. D6's MES is the
    harmonic mean of a producer and a consumer count and is identically zero
    while either is; this relationship existing is the use case."""
    assert one(graph, "MATCH ()-[r:CONSUMES]->() RETURN count(r) AS n")["n"] == CONSUMES


def test_the_metabolite_exchange_score_is_non_zero_for_acetate(graph):
    """D6's golden shape, at fixture scale: one producer and one consumer on
    **one** node. Split the acid from its conjugate base and both counts halve
    to zero and MES with them."""
    row = one(
        graph,
        f"MATCH (m:Metabolite {{id: '{ACETIC_ACID}'}}) "
        "OPTIONAL MATCH (p:Taxon)-[:PRODUCES]->(m) "
        "OPTIONAL MATCH (c:Taxon)-[:CONSUMES]->(m) "
        "RETURN count(DISTINCT p) AS producers, count(DISTINCT c) AS consumers",
    )
    assert row["producers"] >= 1 and row["consumers"] >= 1
    mes = (
        2.0
        * row["producers"]
        * row["consumers"]
        / (row["producers"] + row["consumers"])
    )
    assert mes > 0.0


def test_butyrate_reaches_hmdbs_butyric_acid_by_the_conjugate_route(graph):
    """The single most consequential join in this loader. HMDB records the acid,
    NJC19 says the anion, and without the `-ate` <-> `-ic acid` step every SCFA
    in the graph is two nodes with half the evidence each."""
    row = one(
        graph,
        f"MATCH (t:Taxon)-[r:PRODUCES]->(m:Metabolite {{id: '{BUTYRIC_ACID}'}}) "
        f"WHERE r.primary_source = '{SOURCE}' "
        "RETURN r.metabolite_join AS route, r.reported_compound AS said, t.id AS tax_id",
    )
    assert row["route"] == "conjugate"
    assert row["said"] == "Butyrate"
    assert row["tax_id"] == 853  # Faecalibacterium prausnitzii


def test_an_exact_name_beats_every_derived_spelling(graph):
    """`Deoxycholic acid` is spelled the same in both sources, and the route
    recorded on the edge says the join did not need a derivation to get there."""
    assert (
        one(
            graph,
            f"MATCH ()-[r:CONSUMES]->(m:Metabolite {{id: '{DEOXYCHOLIC_ACID}'}}) "
            "RETURN r.metabolite_join AS route",
        )["route"]
        == "exact"
    )


def test_produces_is_one_table_two_sources(graph, csv_dir):
    """`taxon_metabolite.csv` is HMDB's file and NJC19 appends to it — a shared
    table is how a second source contributes to one relationship, not a second
    relationship (microbiomekg.tables). `primary_source` is what tells them
    apart, and it is on every edge."""
    counts = {
        r["source"]: r["n"]
        for r in rows(
            graph,
            "MATCH ()-[r:PRODUCES]->() RETURN r.primary_source AS source, count(r) AS n",
        )
    }
    assert counts[SOURCE] == PRODUCES
    assert counts["hmdb"] > 0, "HMDB's rows must survive the merge"
    written = {r["primary_source"] for r in table(csv_dir, "taxon_metabolite.csv")}
    assert written == {"hmdb", SOURCE}


def test_degradation_is_its_own_relationship(graph):
    """Extracellular breakdown of a polymer and uptake of a small molecule are
    different claims about a community, and the source separates them."""
    got = {
        r["compound"]
        for r in rows(
            graph,
            "MATCH ()-[r:DEGRADES]->(m:Metabolite) RETURN m.title AS compound",
        )
    }
    assert got == {"Pectin", "Mucin"}
    assert one(graph, "MATCH ()-[r:DEGRADES]->() RETURN count(r) AS n")["n"] == DEGRADES


# --------------------------------------------------------------------------
# The negatives — 912 in the real file, and they must stay countable
# --------------------------------------------------------------------------


def test_a_refutation_is_never_reachable_as_an_observation(graph):
    """The fixture's `Succinate` row says *Bacteroides thetaiotaomicron does
    not export succinate*. Folding it into a property of a `PRODUCES` edge
    would make every `MATCH (t)-[:PRODUCES]->(m)` count it as a production
    claim — silently, for anyone who did not know to add a WHERE clause."""
    succinate = one(
        graph, "MATCH (m:Metabolite {title: 'Succinic acid'}) RETURN m.id AS id"
    )["id"]
    assert not rows(
        graph,
        f"MATCH (t:Taxon {{id: 818}})-[r:PRODUCES]->(m:Metabolite {{id: '{succinate}'}}) "
        f"WHERE r.primary_source = '{SOURCE}' RETURN r",
    )
    refutation = one(
        graph,
        f"MATCH (t:Taxon {{id: 818}})-[r:NO_EXCHANGE_WITH]->(m:Metabolite "
        f"{{id: '{succinate}'}}) RETURN r.source_relation AS rel",
    )
    assert refutation["rel"] == "export-negative"


def test_every_negative_names_the_activity_it_refutes(graph):
    """`NO_EXCHANGE_WITH` is shared by all three activities, so without
    `source_relation` a refuted import and a refuted degradation are one
    undifferentiated edge."""
    relations = {
        r["rel"]
        for r in rows(
            graph,
            "MATCH ()-[r:NO_EXCHANGE_WITH]->() RETURN DISTINCT r.source_relation AS rel",
        )
    }
    assert relations <= {"import-negative", "export-negative", "degrade-negative"}
    assert one(graph, "MATCH ()-[r:NO_EXCHANGE_WITH]->() RETURN count(r) AS n")[
        "n"
    ] == (NO_EXCHANGE)


# --------------------------------------------------------------------------
# Organisms: what is refused, and what is refused *without* a tombstone
# --------------------------------------------------------------------------


def test_a_host_cell_type_is_excluded_by_name_and_is_not_a_lost_taxon(graph, csv_dir):
    """NJC19's own scale line is "838 microbial species + 6 host cell types".
    Letting the six fail reconciliation writes six `UnresolvedTaxon` tombstones,
    each of which asserts NCBI has lost a taxon — a false statement about the
    taxonomy, arrived at by doing nothing."""
    unresolved = {r["raw_name"] for r in table(csv_dir, "unresolved_taxa.csv")}
    assert not (unresolved & HOST_CELL_TYPES)
    assert "human colonocyte" not in unresolved
    ledger = table(csv_dir, "unresolved_exchange.csv")
    host = [r for r in ledger if r["species"] == "human colonocyte"]
    assert len(host) == 1 and "host cell type" in host[0]["reason"]


def test_an_ambiguous_genus_is_refused_and_not_guessed(graph, csv_dir):
    """`Bacillus` is a bacterial genus **and** a genus of stick insects.
    HMDB's loader breaks that homonym with the microbial context of the term it
    came from; there is no such context here — NJC19's column is a species
    column — so the honest outcome is no edge and a tombstone carrying both
    candidates."""
    tomb = one(
        graph,
        "MATCH (u:UnresolvedTaxon) WHERE u.raw_name = 'Bacillus' "
        "RETURN u.status AS status, u.candidates AS candidates",
    )
    assert tomb["status"] == "ambiguous"
    assert set(tomb["candidates"]) == {"1386", "55087"}
    # Scoped to this source: HMDB's loader *does* write a Bacillus edge, because
    # its organism term came from a microbial-origin path and that context picks
    # the one candidate under Bacteria. NJC19's column carries no such context.
    assert not rows(
        graph,
        "MATCH (t:Taxon {id: 1386})-[r]->(:Metabolite) "
        f"WHERE r.primary_source = '{SOURCE}' RETURN r",
    )


def test_a_renamed_organism_is_a_tombstone_not_a_drop(graph, csv_dir):
    """`Mycoplasma pneumoniae` moved to *Mycoplasmoides* in 2018 and NJC19 was
    curated before that. G2: nothing is dropped."""
    assert (
        one(
            graph,
            "MATCH (u:UnresolvedTaxon) WHERE u.raw_name = 'Mycoplasma pneumoniae' "
            "RETURN u.status AS status",
        )["status"]
        == "unresolved"
    )
    assert (
        len([r for r in table(csv_dir, "unresolved_taxa.csv") if r["source"] == SOURCE])
        == UNRESOLVED_TAXA
    )


def test_a_subspecies_is_promoted_and_keeps_the_rank_it_came_from(graph):
    """G5's split: the edge is keyed on the species, and `original_rank` still
    says the source named something narrower."""
    row = one(
        graph,
        "MATCH (t:Taxon)-[r:PRODUCES]->() "
        "WHERE r.reported_name = 'Bifidobacterium longum subsp. infantis' "
        "RETURN t.id AS tax_id, r.original_rank AS original, "
        "r.resolution_status AS status",
    )
    assert row["tax_id"] == 216816  # Bifidobacterium longum, the species
    assert row["original"] == "subspecies"
    assert row["status"] == "promoted"


def test_a_family_is_broader_than_an_exchange_claim(graph, csv_dir):
    """NJC19 files every row against a species, so a resolution this broad is a
    surprise rather than a filter — and the ledger row carries the id and rank
    it did reach, so the ceiling is reversible."""
    ledger = table(csv_dir, "unresolved_exchange.csv")
    broad = [r for r in ledger if r["species"] == "Lachnospiraceae"]
    assert len(broad) == 1
    assert broad[0]["resolved_tax_id"] == "186803"
    assert broad[0]["resolved_rank"] == "family"
    assert "broader than" in broad[0]["reason"]


# --------------------------------------------------------------------------
# Compounds: joined, minted, and the MiMeDB half
# --------------------------------------------------------------------------


def test_a_compound_mimedb_carries_reaches_mimedbs_node(graph):
    """This is MiMeDB's entire measurable contribution to the graph: `Pectin`
    is a real compound NJC19 curates degradation of, and no HMDB record holds
    it. Without MiMeDB the edge lands on a minted stub with no InChIKey and no
    formula."""
    row = one(
        graph,
        "MATCH ()-[r:DEGRADES]->(m:Metabolite {title: 'Pectin'}) "
        "RETURN m.id AS id, m.source AS source, m.inchikey AS inchikey, "
        "r.metabolite_join AS route",
    )
    assert row["source"] == "mimedb"
    assert row["id"].startswith("MIMEDB:")
    assert row["route"] == "exact"
    assert row["inchikey"], (
        "the point of joining MiMeDB is that its node has an identity"
    )


def test_a_compound_no_source_holds_is_minted_not_dropped(graph):
    """A metabolome database has no reason to hold mucin. Dropping the compound
    would drop a degradation claim NJC19 did curate."""
    row = one(
        graph,
        "MATCH ()-[r:DEGRADES]->(m:Metabolite {title: 'Mucin'}) "
        "RETURN m.id AS id, m.source AS source, m.selection_rule AS rule, "
        "r.metabolite_join AS route, r.reported_compound AS said",
    )
    assert row["id"] == "NJC19:Mucin"
    assert row["source"] == SOURCE
    assert row["rule"] == ["njc19-exchange"]
    assert row["route"] == "minted"
    # The source's own spelling survives on the edge, synonym list and all.
    assert row["said"] == "Mucin (Mucus Glycoprotein)"


def test_a_minted_metabolite_does_not_claim_microbial_origin(graph):
    """`microbial_origin` is HMDB's claim that a compound *comes from* a
    microbe. "An organism exchanges this" is a different claim — pectin is a
    plant polymer — and writing `true` here would put 45 false origin flags in
    the real graph."""
    for row in rows(
        graph,
        f"MATCH (m:Metabolite) WHERE m.source = '{SOURCE}' "
        "RETURN m.microbial_origin AS origin, m.status AS status",
    ):
        assert row["origin"] is False
        assert not row["status"], "NJC19 grades no compound; a status here is invented"


# --------------------------------------------------------------------------
# C18 accounting, the evidence contract, and the audit
# --------------------------------------------------------------------------


def test_every_row_is_an_edge_or_a_counted_reason(graph, csv_dir, prep_output):
    """Input rows = edges + ledger rows + the one duplicate, with the combined
    row counted twice because it is two claims. A silent drop cannot hide in
    the difference."""
    edges = sum(
        one(
            graph,
            f"MATCH ()-[r:{rel}]->() WHERE r.primary_source = '{SOURCE}' "
            "RETURN count(r) AS n",
        )["n"]
        for rel in ("PRODUCES", "CONSUMES", "DEGRADES", "NO_EXCHANGE_WITH")
    )
    ledger = table(csv_dir, "unresolved_exchange.csv")
    assert len(ledger) == LEDGER_ROWS
    duplicate, combined = 1, 1
    assert edges + len(ledger) + duplicate - combined == DATA_ROWS
    assert f"read {DATA_ROWS} rows -> {EDGES} edges" in prep_output


def test_the_prep_reports_what_it_did_not_load(prep_output):
    for phrase in (
        "by relationship:",
        "negatives kept as NO_EXCHANGE_WITH:",
        "rows curating both directions",
        "organism resolution:",
        "not loaded:",
        "compound join:",
        "species-level rows standing on genus-level references only:",
    ):
        assert phrase in prep_output


def test_the_evidence_is_stated_and_is_the_same_on_every_edge(graph):
    """NJC19's inclusion criterion *is* its evidence tier — the file carries no
    per-row design, host or assay column that could move it. One value is not a
    missing value, and it is drawn from the pinned vocabulary rather than
    spelled at the write site."""
    assert EVIDENCE_LEVEL in EVIDENCE_LEVEL_VALUES
    for rel in ("PRODUCES", "CONSUMES", "DEGRADES", "NO_EXCHANGE_WITH"):
        for row in rows(
            graph,
            f"MATCH ()-[r:{rel}]->() WHERE r.primary_source = '{SOURCE}' "
            "RETURN DISTINCT r.evidence_level AS level, r.knowledge_level AS kl, "
            "r.agent_type AS agent, r.source_licence AS licence",
        ):
            assert row["level"] == EVIDENCE_LEVEL == "in-vitro"
            assert row["kl"] == "knowledge_assertion"
            assert row["agent"] == "manual_agent"
            assert row["licence"] == "CC0-1.0"


def test_a_species_row_on_genus_level_literature_is_marked(graph):
    """26.6% of the real table is this. Guard G5: the claim is filed at species
    level and its evidence is not, and one WHERE clause has to be able to
    separate them."""
    marked = one(
        graph,
        "MATCH ()-[r:DEGRADES]->(m:Metabolite {title: 'Pectin'}) "
        "RETURN r.genus_level_evidence AS g, r.reference_ids AS refs",
    )
    assert marked["g"] is True
    assert marked["refs"] == ["217(G)"]
    plain = one(
        graph,
        "MATCH ()-[r:CONSUMES]->() WHERE r.reported_compound = 'Deoxycholic acid' "
        "RETURN r.genus_level_evidence AS g, r.n_references AS n",
    )
    assert plain["g"] is False
    assert plain["n"] == 2


def test_the_exchange_contract_is_a_rule_that_can_fail(graph):
    """Every field is written by this prep rather than read from upstream, so
    the rule *should* sit at zero — and a rule at zero is only worth having if
    it could move."""
    audit = {
        r["rule"]: r
        for r in rows(
            graph,
            "CALL ontology_audit() YIELD rule, violations, total "
            "RETURN rule, violations, total",
        )
    }
    for rel in ("PRODUCES", "CONSUMES", "DEGRADES", "NO_EXCHANGE_WITH"):
        rule = audit[f"{rel}.required_properties"]
        assert rule["total"] > 0, f"{rel} audits nothing — a gate that cannot fail"
        assert rule["violations"] == 0, f"{rel} violates its own contract"
    # And the contract is the applicable subset: an exchange claim has no
    # direction, no assay and no cohort.
    assert "direction" not in EXCHANGE_CONTRACT
    assert "group_0_size" not in EXCHANGE_CONTRACT
    assert {"evidence_level", "reported_name"} <= set(EXCHANGE_CONTRACT)


def test_hmdb_status_is_not_required_of_a_source_that_has_no_such_column(graph):
    """It was the ninth field of `PRODUCTION_CONTRACT` and could not survive a
    second author: NJC19 has no detection status, so a required `hmdb_status`
    would report every NJC19 edge as a violation of a rule meant to read zero —
    an audit number that means "a source landed", not "evidence is missing"."""
    assert "hmdb_status" not in EXCHANGE_CONTRACT
    for row in rows(
        graph,
        f"MATCH ()-[r:PRODUCES]->() WHERE r.primary_source = '{SOURCE}' "
        "RETURN DISTINCT r.hmdb_status AS status",
    ):
        assert not row["status"]


def test_every_exchanging_taxon_is_cited_and_loaded(graph, csv_dir):
    """`cited_taxa.csv` drives which taxa the taxonomy build keeps; a source
    that did not contribute to it would have its edges point at nothing."""
    got = {
        r["tax_id"]
        for r in rows(
            graph,
            "MATCH (t:Taxon)-[r]->(:Metabolite) "
            f"WHERE r.primary_source = '{SOURCE}' RETURN DISTINCT t.id AS tax_id",
        )
    }
    cited = {
        int(r["tax_id"])
        for r in table(csv_dir, "cited_taxa.csv")
        if r["source"] == SOURCE
    }
    assert got and got <= cited


def test_a_byte_identical_row_is_one_edge_not_two(graph):
    """A duplicate fact is not a second observation. The fixture repeats its
    first row verbatim; `dedupe_full` collapses it, and the *genuinely* parallel
    edges — a taxon and a compound from two different reference sets — survive
    because their `source_record_id` and references differ."""
    assert (
        one(
            graph,
            f"MATCH (t:Taxon {{id: 853}})-[r:PRODUCES]->(m:Metabolite {{id: '{BUTYRIC_ACID}'}}) "
            f"WHERE r.primary_source = '{SOURCE}' RETURN count(r) AS n",
        )["n"]
        == 1
    )


@pytest.mark.fixture
def test_the_fixture_keeps_the_real_sheet_shape():
    """The loader finds its header by searching for `Metabolic activity`,
    because the real sheet opens with three legend lines whose column count
    matches the data's. A fixture that skipped the legend would not exercise
    that, and a fixed row skip would survive here and break on the real file."""
    import openpyxl

    book = openpyxl.load_workbook(NJC19_MINI, read_only=True)
    try:
        assert book.sheetnames == ["Online-only Table 5"]
        grid = list(book["Online-only Table 5"].iter_rows(values_only=True))
    finally:
        # `read_only=True` keeps the zip handle open; without this the whole
        # suite ends on a ResourceWarning naming this fixture.
        book.close()
    assert grid[0][0].startswith("Online-only Table 5. Metabolic associations")
    assert "(G) genus level information" in grid[2][0]
    assert grid[3] == (None, None, None, None, None)
    assert grid[4][3] == "Metabolic activity"
    assert len(grid) - 5 == DATA_ROWS
